"""Embed art/battle/px/*.png (game-ready pixel sprites) into src/07id_sprites.js as data URIs."""
import os, base64, glob, json
root = os.path.join(os.path.dirname(__file__), '..')
d = {}
SKIP = {'hero'}  # the hero keeps the field paper doll in battle (HD_HERO_DOLL), its Codex sprites stay in art/ only
for f in sorted(glob.glob(os.path.join(root, 'art', 'battle', 'px', '*.png'))):
    if os.path.basename(f)[:-4] in SKIP: continue
    if os.path.exists(os.path.join(root, 'art', 'battle', 'pxanim', os.path.basename(f))): continue  # the animated strip replaces it
    d[os.path.basename(f)[:-4]] = 'data:image/png;base64,' + base64.b64encode(open(f, 'rb').read()).decode()
js = '/* ===================== GENERATED by tools/embed_sprites.py — battle pixel sprites drawn with Codex (art/battle) ===================== */\n'
js += 'const BATTLE_PX_SRC = ' + json.dumps(d, separators=(',', ':')) + ';\n'
a, meta = {}, {}
for f in sorted(glob.glob(os.path.join(root, 'art', 'battle', 'pxanim', '*.png'))):
    k = os.path.basename(f)[:-4]
    if '_' in k or k in SKIP: continue  # previews / skipped
    a[k] = 'data:image/png;base64,' + base64.b64encode(open(f, 'rb').read()).decode(); meta[k] = json.load(open(f[:-4] + '.json'))
js += 'const BATTLE_PXA_SRC = ' + json.dumps(a, separators=(',', ':')) + ';\n'
js += 'const BATTLE_PXA_META = ' + json.dumps(meta, separators=(',', ':')) + ';\n'
fd = {}
for f in sorted(glob.glob(os.path.join(root, 'art', 'battle', 'fieldpx', '*.png'))):
    fd[os.path.basename(f)[:-4]] = 'data:image/png;base64,' + base64.b64encode(open(f, 'rb').read()).decode()
js += 'const BATTLE_FIELD_SRC = ' + json.dumps(fd, separators=(',', ':')) + ';\n'
pc, pcm = {}, {}
for f in sorted(glob.glob(os.path.join(root, 'art', 'battle', 'chibipx', '*.png'))):
    k = os.path.basename(f)[:-4]; pc[k] = 'data:image/png;base64,' + base64.b64encode(open(f, 'rb').read()).decode(); pcm[k] = json.load(open(f[:-4] + '.json'))
js += 'const BATTLE_PXC_SRC = ' + json.dumps(pc, separators=(',', ':')) + ';\n'
js += 'const BATTLE_PXC_META = ' + json.dumps(pcm, separators=(',', ':')) + ';\n'
ui = {}
for f in sorted(glob.glob(os.path.join(root, 'art', 'ui', 'px', '*.png'))):
    ui[os.path.basename(f)[:-4]] = 'data:image/png;base64,' + base64.b64encode(open(f, 'rb').read()).decode()
js += 'const UI_PX_SRC = ' + json.dumps(ui, separators=(',', ':')) + ';\n'
mp = os.path.join(root, 'art', 'ui', 'px', 'meta.json')
js += 'const UI_PX_META = ' + (open(mp).read() if os.path.exists(mp) else '{}') + ';\n'
sk = {}
for f in sorted(glob.glob(os.path.join(root, 'art', 'ui', 'battle', '*.png'))):
    n = os.path.basename(f)[:-4]
    if n != 'ui_mockup': sk[n] = 'data:image/png;base64,' + base64.b64encode(open(f, 'rb').read()).decode()
js += 'const UI_SKIN_SRC = ' + json.dumps(sk, separators=(',', ':')) + ';\n'
hr = {}
for f in sorted(glob.glob(os.path.join(root, 'art', 'hero', 'px', '*.png'))):
    hr[os.path.basename(f)[:-4]] = 'data:image/png;base64,' + base64.b64encode(open(f, 'rb').read()).decode()
hm = os.path.join(root, 'art', 'hero', 'px', 'meta.json')
js += 'const HERO_PX_SRC = ' + json.dumps(hr, separators=(',', ':')) + ';\n'
js += 'const HERO_PX_META = ' + (open(hm).read() if os.path.exists(hm) else 'null') + ';\n'
wp = {}
for f in sorted(glob.glob(os.path.join(root, 'art', 'battle', 'weapons', '*.png'))):
    k = os.path.basename(f)[:-4]
    if '_' in k or k.startswith('weapons'): continue  # previews
    wp[k] = 'data:image/png;base64,' + base64.b64encode(open(f, 'rb').read()).decode()
js += 'const WEAPON_PX_SRC = ' + json.dumps(wp, separators=(',', ':')) + ';\n'
print('weapons', len(wp))
ar = {}
for f in sorted(glob.glob(os.path.join(root, 'art', 'battle', 'armor', '*.png'))):
    k = os.path.basename(f)[:-4]
    if not (k.endswith('_back') or k.endswith('_back2') or k.endswith('_icon')): continue  # previews
    ar[k] = 'data:image/png;base64,' + base64.b64encode(open(f, 'rb').read()).decode()
js += 'const ARMOR_PX_SRC = ' + json.dumps(ar, separators=(',', ':')) + ';\n'
print('armor', len(ar))
print('animated', len(a), 'field', len(fd), 'ui', len(ui), 'chibi', len(pc), 'skin', len(sk), 'hero', len(hr))
open(os.path.join(root, 'src', '07id_sprites.js'), 'w').write(js)
print('embedded', len(d), 'sprites', sum(len(v) for v in d.values()) // 1024, 'KB')
