"""Embed art/battle/px/*.png (game-ready pixel sprites) into src/07id_sprites.js as data URIs."""
import os, base64, glob, json
root = os.path.join(os.path.dirname(__file__), '..')
d = {}
for f in sorted(glob.glob(os.path.join(root, 'art', 'battle', 'px', '*.png'))):
    d[os.path.basename(f)[:-4]] = 'data:image/png;base64,' + base64.b64encode(open(f, 'rb').read()).decode()
js = '/* ===================== GENERATED by tools/embed_sprites.py — battle pixel sprites drawn with Codex (art/battle) ===================== */\n'
js += 'const BATTLE_PX_SRC = ' + json.dumps(d, separators=(',', ':')) + ';\n'
open(os.path.join(root, 'src', '07id_sprites.js'), 'w').write(js)
print('embedded', len(d), 'sprites', sum(len(v) for v in d.values()) // 1024, 'KB')
