"""Embed art/battle/px/*.png (game-ready pixel sprites) into src/07id_sprites.js as data URIs."""
import os, base64, glob, json
root = os.path.join(os.path.dirname(__file__), '..')
d = {}
SKIP = {'hero'}  # the hero keeps the field paper doll in battle (HD_HERO_DOLL), its Codex sprites stay in art/ only
for f in sorted(glob.glob(os.path.join(root, 'art', 'battle', 'px', '*.png'))):
    if os.path.basename(f)[:-4] in SKIP: continue
    if os.path.exists(os.path.join(root, 'art', 'battle', 'pxanim', os.path.basename(f))): continue  # the animated strip replaces it
    d[os.path.basename(f)[:-4]] = 'data:image/png;base64,' + base64.b64encode(open(f, 'rb').read()).decode()
js = '/* ===================== GENERATED by tools/embed_sprites.py — battle pixel sprites drawn with Codex (art/battle) ===================== */\n'
js += 'const BATTLE_PX_SRC = ' + json.dumps(d, separators=(',', ':')) + ';\n'
a, meta = {}, {}
for f in sorted(glob.glob(os.path.join(root, 'art', 'battle', 'pxanim', '*.png'))):
    k = os.path.basename(f)[:-4]
    if '_' in k or k in SKIP: continue  # previews / skipped
    a[k] = 'data:image/png;base64,' + base64.b64encode(open(f, 'rb').read()).decode(); meta[k] = json.load(open(f[:-4] + '.json'))
js += 'const BATTLE_PXA_SRC = ' + json.dumps(a, separators=(',', ':')) + ';\n'
js += 'const BATTLE_PXA_META = ' + json.dumps(meta, separators=(',', ':')) + ';\n'
print('animated', len(a))
open(os.path.join(root, 'src', '07id_sprites.js'), 'w').write(js)
print('embedded', len(d), 'sprites', sum(len(v) for v in d.values()) // 1024, 'KB')
