const HAIR = {
  '原本': {"down":["................",".....kkkkkk.....","...kkHHHHHHkk...","..kHHhhHHHHHHk..","..kHhjjhHHHHHk..",".kHHHHHHHHHHHHk.",".kHHHHHHHHHHHHk.",".kHHkHHHHkHHHHk.",".kHkSSkHHkSSSHk.",".kHSSSSSSSSSSHk.",".kkSSkSSSSkSSkk.","..kSSkSSSSkSSk..","...ksSSSSSSsk..."],"up":["................",".....kkkkkk.....","...kkHHHHHHkk...","..kHHHhhHHHHHk..","..kHHhjjhHHHHk..",".kHHHHhhHHHHHHk.",".kHHHHHHHHHHHHk.",".kHHHHHHHHHHHHk.",".kHHHHHHHHHHHHk.",".kHHHHHHHHHHHHk.",".kkHHHHHHHHHHkk.","..kkHHHHHHHHkk..","...ksHHHHHHsk..."],"left":["................",".....kkkkk......","...kkHHHHHkk....","..kHHHHhhjHHk...",".kHHHHHHhhHHHk..",".kHHHHHHHHHHHk..",".kHHHHHHHHHHHHk.",".kHSkHHHHHHHHHk.",".kSSSSHHHHHHHk..",".kSSSSSHHHHHHk..",".kSkSSSSHHHHHk..",".kSkSSSSsHHHk...","..kSSSSskHkk...."]},
  'A 刺刺頭（套用）': {
    down: [
      '................',
      '...k...kk...k...',
      '..kHk.kHHk.kHk..',
      '.kHHHkHHHHkHHHk.',
      '.kHHHhhjHHHHHHk.',
      '.kHHHHHHHHHHHHk.',
      'kHHHHHHHHHHHHHHk',
      '.kHHkHHHHHkHHHk.',
      '.kHkSSkHHkSSkHk.',
      '.kHSSSSSSSSSSHk.',
      '.kkSSkSSSSkSSkk.',
      '..kSSkSSSSkSSk..',
      '...ksSSSSSSsk...',
    ],
    up: [
      '................',
      '...k...kk...k...',
      '..kHk.kHHk.kHk..',
      '.kHHHkHHhHkHHHk.',
      '.kHHHHHhjjhHHHk.',
      '.kHHHHHHhhHHHHk.',
      'kHHHHHHHHHHHHHHk',
      '.kHHHHHHHHHHHHk.',
      '.kHHHHHHHHHHHHk.',
      'kHHHHHHHHHHHHHHk',
      '.kkHHHHHHHHHHkk.',
      '..kkHHHHHHHHkk..',
      '...ksHkHHkHsk...',
    ],
    left: [
      '................',
      '....k..kk..k....',
      '...kHkkHHkkHk...',
      '..kHHHHhhjHHHk..',
      '.kHHHHHHhhHHHHkk',
      '.kHHHHHHHHHHHHk.',
      '.kHHHHHHHHHHHHHk',
      '.kHSkHHHHHHHHHk.',
      '.kSSSSHHHHHHHHkk',
      '.kSSSSSHHHHHHk..',
      '.kSkSSSSHHHHHk..',
      '.kSkSSSSsHHHk...',
      '..kSSSSskHkk....',
    ],
  },
  'B 側分呆毛': {
    down: [
      '................',
      '.........kk.....',
      '.....kkkkHk.....',
      '...kkHHHHHHkkk..',
      '..kHHHhhjHHHHHk.',
      '.kHHHHHHhHHHHHk.',
      '.kHHHHHHHHHHHHk.',
      '.kHHHHHHHHHHkHk.',
      '.kHHHHHHHHkSSHk.',
      '.kHHHHkkSSSSSHk.',
      '.kkSSkSSSSkSSkk.',
      '..kSSkSSSSkSSk..',
      '...ksSSSSSSsk...',
    ],
    up: [
      '................',
      '.....kk.........',
      '.....kHkkkk.....',
      '..kkkHHHHHHkk...',
      '.kHHHHHhhHHHHk..',
      '.kHHHHhjjhHHHHk.',
      '.kHHHHHhhHHHHHk.',
      '.kHHHHHHHHHHHHk.',
      '.kHHHHHHHHHHHHk.',
      '.kHHHHHHHHHHHHk.',
      '.kkHHHHHHHHHHkk.',
      '..kkHHHHHHHHkk..',
      '...ksHHHHHHsk...',
    ],
    left: [
      '................',
      '.......kk.......',
      '....kkkHkkk.....',
      '..kkHHHHhjHkk...',
      '.kHHHHHHhhHHHk..',
      '.kHHHHHHHHHHHk..',
      '.kHHHHHHHHHHHHk.',
      '.kHHHkHHHHHHHHk.',
      '.kHHSSHHHHHHHk..',
      '.kSSSSSHHHHHHk..',
      '.kSkSSSSHHHHHk..',
      '.kSkSSSSsHHHk...',
      '..kSSSSskHkk....',
    ],
  },
  'C 短髮露耳': {
    down: [
      '................',
      '................',
      '....kkkkkkkk....',
      '...kHHhhHHHHk...',
      '..kHHhjjhHHHHk..',
      '..kHHHHHHHHHHk..',
      '..kHHHHHHHHHHk..',
      '..kHkHHkHHkHHk..',
      '.kkkSSkSSkSSSkk.',
      '.ksSSSSSSSSSSsk.',
      '.kkSSkSSSSkSSkk.',
      '..kSSkSSSSkSSk..',
      '...ksSSSSSSsk...',
    ],
    up: [
      '................',
      '................',
      '....kkkkkkkk....',
      '...kHHHhhHHHk...',
      '..kHHHhjjhHHHk..',
      '..kHHHHhhHHHHk..',
      '..kHHHHHHHHHHk..',
      '..kHHHHHHHHHHk..',
      '.kkHHHHHHHHHHkk.',
      '.ksHHHHHHHHHHsk.',
      '.kkHHHHHHHHHHkk.',
      '..kkHHHHHHHHkk..',
      '...kssSSSSssk...',
    ],
    left: [
      '................',
      '................',
      '....kkkkkkk.....',
      '...kHHHHhjHk....',
      '..kHHHHHHhhHk...',
      '..kHHHHHHHHHHk..',
      '..kHHHHHHHHHHk..',
      '.kHSkHHHHHHHHk..',
      '.kSSSSSHkHHHHk..',
      '.kSSSSSSksHHHk..',
      '.kSkSSSSkkHHHk..',
      '.kSkSSSSsHHHk...',
      '..kSSSSskHkk....',
    ],
  },
};
