/* ===================== DATA ===================== */
const TYPES = ['一般', '火', '水', '草', '雷', '岩', '毒', '飛'];
const EFF = {
  '一般': { '岩': 0.5 },
  '火': { '草': 2, '火': 0.5, '水': 0.5, '岩': 0.5 },
  '水': { '火': 2, '岩': 2, '水': 0.5, '草': 0.5 },
  '草': { '水': 2, '岩': 2, '火': 0.5, '草': 0.5, '毒': 0.5, '飛': 0.5 },
  '雷': { '水': 2, '飛': 2, '雷': 0.5, '草': 0.5 },
  '岩': { '火': 2, '飛': 2 },
  '毒': { '草': 2, '毒': 0.5, '岩': 0.5 },
  '飛': { '草': 2, '雷': 0.5, '岩': 0.5 },
};
const typeMult = (atk, def) => def ? ((EFF[atk] || {})[def] ?? 1) : 1;
const STAT_NAMES = { hp: 'HP', atk: '物攻', def: '物防', spa: '魔攻', spd: '魔防', spe: '速度' };
const QUALITY = [null, ['普通', '#c9cfe4'], ['優良', '#72e39a'], ['稀有', '#86b4ff'], ['史詩', '#c58cff'], ['傳說', '#ffb454']];
// classic six attributes for the hero
const ATTRS = ['str', 'agi', 'vit', 'int', 'dex', 'luk'];
const ATTR_NAMES = { str: '力量', agi: '敏捷', vit: '體力', int: '智力', dex: '靈巧', luk: '幸運' };
const HERO_ATTR_INIT = { str: 6, agi: 5, vit: 6, int: 5, dex: 5, luk: 4 };   // at Lv5
const HERO_GROWTH = { str: 0.45, agi: 0.40, vit: 0.50, int: 0.40, dex: 0.35, luk: 0.25 }; // points per level (low growth)
const HERO_GROWTH_OFS = { str: 0.05, agi: 0.95, vit: 0.45, int: 0.35, dex: 0.9, luk: 0.85 }; // staggered so each level raises 2–3 attributes
const STAT_KEYS = ['hp', 'atk', 'def', 'spa', 'spd', 'spe'];

// cat: 物=physical 特=special 變=status
const MOVES = {
  slash: { n: '揮砍', t: '一般', cat: '物', pow: 40, acc: 100, pp: 35, fx: 'slash', d: '揮劍砍向對手。' },
  glare: { n: '瞪眼', t: '一般', cat: '變', acc: 100, pp: 30, stat: { who: 'foe', def: -1 }, fx: 'glare', d: '用銳利的眼神瞪視對手，降低對手的物防。' },
  flameSlash: { n: '火焰斬', t: '火', cat: '物', pow: 45, acc: 100, pp: 25, eff: { st: 'brn', p: 10 }, fx: 'fireSlash', d: '以燃燒的劍刃砍擊。有時會讓對手灼傷。' },
  focus: { n: '集氣', t: '一般', cat: '變', pp: 20, stat: { who: 'self', atk: 1, spa: 1 }, fx: 'buff', d: '集中精神，提高自己的物攻和魔攻。' },
  powerSlash: { n: '強力斬', t: '一般', cat: '物', pow: 70, acc: 90, pp: 10, fx: 'slash', d: '灌注全力的一擊。' },
  manaBurst: { n: '魔力爆發', t: '一般', cat: '特', pow: 65, acc: 100, pp: 10, fx: 'sound', d: '把魔力凝聚後一口氣釋放。' },
  guardStrike: { n: '盾擊', t: '一般', cat: '物', pow: 55, acc: 100, pp: 15, eff: { flinch: 1, p: 30 }, fx: 'hit', d: '用護甲撞擊對手，有時會讓對手退縮。' },
  bladeStorm: { n: '劍刃風暴', t: '一般', cat: '物', pow: 90, acc: 90, pp: 5, crit: 1, fx: 'slash', d: '捲起劍刃的風暴。容易會心。' },
  recklessSlash: { n: '捨身斬', t: '一般', cat: '物', pow: 110, acc: 95, pp: 5, recoil: 0.25, fx: 'slash', d: '不顧一切的斬擊，自己也會受到反作用力傷害。' },
  inferno: { n: '業火', t: '火', cat: '特', pow: 95, acc: 85, pp: 5, eff: { st: 'brn', p: 30 }, fx: 'fireSlash', d: '召喚吞噬一切的火焰。有時會讓對手灼傷。' },
  thunderstorm: { n: '雷暴', t: '雷', cat: '特', pow: 95, acc: 85, pp: 5, eff: { st: 'par', p: 30 }, fx: 'thunder', d: '降下猛烈的雷暴。有時會讓對手麻痺。對潮濕的對手會感電。' },
  holyLight: { n: '聖光', t: '一般', cat: '變', pp: 5, heal: 0.5, fx: 'heal', d: '恢復一半的最大HP。' },
  dawnBreak: { n: '破曉斬', t: '一般', cat: '物', pow: 120, acc: 100, pp: 5, crit: 1, fx: 'fireSlash', d: '異界勇者的奧義。劃破黑暗的一擊。' },
  crystalSpark: { n: '晶雷', t: '雷', cat: '特', pow: 70, acc: 95, pp: 10, eff: { st: 'par', p: 20 }, d: '水晶放出的電流。' },
  prismRay: { n: '稜光射線', t: '岩', cat: '特', pow: 80, acc: 90, pp: 10, d: '把光折射成七彩射線。' },
  armorBreak: { n: '破甲斬', t: '一般', cat: '物', pow: 45, acc: 95, pp: 15, eff: { stat: { def: -1 }, p: 100 }, fx: 'slash', d: '劈開對手的防具。必定降低對手的物防。' },
  barrier: { n: '魔法護盾', t: '一般', cat: '變', pp: 10, shield: 3, fx: 'guard', d: '展開魔法護盾，3回合內受到的傷害減少40%。' },
  aquaBlade: { n: '水流刃', t: '水', cat: '特', pow: 50, acc: 100, pp: 25, fx: 'water', d: '揮出激流般的水刃。會讓對手潮濕，再用雷系攻擊就能引發感電。' },
  thunder: { n: '落雷', t: '雷', cat: '特', pow: 55, acc: 95, pp: 20, eff: { st: 'par', p: 10 }, fx: 'thunder', d: '召喚雷電打向對手。對潮濕的對手會感電：傷害1.5倍並麻痺。' },
  gale: { n: '疾風刺', t: '一般', cat: '物', pow: 40, acc: 100, pp: 30, prio: 1, fx: 'quick', d: '以疾風般的速度突刺。必定能先出手。' },
  leafBlade: { n: '翠葉斬', t: '草', cat: '物', pow: 65, acc: 95, pp: 20, crit: 1, fx: 'leaf', d: '以葉片之力斬擊。容易擊中要害。' },
  heal: { n: '治癒光', t: '一般', cat: '變', pp: 10, heal: 0.5, fx: 'heal', d: '溫暖的光芒，恢復自己最大HP的一半。' },
  blaze: { n: '烈焰斬', t: '火', cat: '物', pow: 80, acc: 95, pp: 15, eff: { st: 'brn', p: 10 }, fx: 'fireSlash', d: '全力揮出熊熊燃燒的一擊。有時會讓對手灼傷。' },
  // monster moves
  tackle: { n: '撞擊', t: '一般', cat: '物', pow: 35, acc: 95, pp: 35, fx: 'hit', d: '用整個身體撞向對手。' },
  growl: { n: '叫聲', t: '一般', cat: '變', acc: 100, pp: 40, stat: { who: 'foe', atk: -1 }, fx: 'sound', d: '可愛地叫，降低對手的物攻。' },
  tailWhip: { n: '搖尾巴', t: '一般', cat: '變', acc: 100, pp: 30, stat: { who: 'foe', def: -1 }, fx: 'glare', d: '可愛地搖尾巴，降低對手的物防。' },
  scratch: { n: '抓', t: '一般', cat: '物', pow: 40, acc: 100, pp: 35, fx: 'scratch', d: '用爪子抓對手。' },
  peck: { n: '啄', t: '飛', cat: '物', pow: 35, acc: 100, pp: 35, fx: 'hit', d: '用尖嘴啄對手。' },
  gust: { n: '起風', t: '飛', cat: '特', pow: 40, acc: 100, pp: 35, fx: 'wind', d: '拍動翅膀颳起強風。' },
  absorb: { n: '吸取', t: '草', cat: '特', pow: 25, acc: 100, pp: 25, drain: 0.5, fx: 'drain', d: '吸取對手的養分，恢復自己的HP。' },
  megaDrain: { n: '超級吸取', t: '草', cat: '特', pow: 40, acc: 100, pp: 15, drain: 0.5, fx: 'drain', d: '大量吸取對手的養分，恢復自己的HP。' },
  poisonPowder: { n: '毒粉', t: '毒', cat: '變', acc: 75, pp: 35, st: 'psn', fx: 'powder', d: '撒出毒粉，讓對手中毒。' },
  sleepPowder: { n: '睡眠粉', t: '草', cat: '變', acc: 75, pp: 15, st: 'slp', fx: 'powderS', d: '撒出催眠粉，讓對手睡著。' },
  vineWhip: { n: '藤鞭', t: '草', cat: '物', pow: 45, acc: 100, pp: 25, fx: 'vine', d: '用藤蔓抽打對手。' },
  bubble: { n: '泡沫', t: '水', cat: '特', pow: 30, acc: 100, pp: 30, eff: { stat: { spe: -1 }, p: 10 }, fx: 'bubble', d: '吐出泡沫攻擊。有時會降低對手的速度。' },
  waterGun: { n: '水槍', t: '水', cat: '特', pow: 40, acc: 100, pp: 25, fx: 'water', d: '噴出強勁的水柱。' },
  ember: { n: '火花', t: '火', cat: '特', pow: 40, acc: 100, pp: 25, eff: { st: 'brn', p: 10 }, fx: 'ember', d: '噴出小小的火焰。有時會讓對手灼傷。' },
  shock: { n: '電擊', t: '雷', cat: '特', pow: 40, acc: 100, pp: 30, eff: { st: 'par', p: 10 }, fx: 'spark', d: '放出電流。有時會讓對手麻痺。' },
  thunderWave: { n: '電磁波', t: '雷', cat: '變', acc: 90, pp: 20, st: 'par', fx: 'spark', d: '放出微弱的電磁波，讓對手麻痺。' },
  poisonSting: { n: '毒針', t: '毒', cat: '物', pow: 15, acc: 100, pp: 35, eff: { st: 'psn', p: 30 }, fx: 'sting', d: '用毒針刺對手。有時會讓對手中毒。' },
  acid: { n: '溶解液', t: '毒', cat: '特', pow: 40, acc: 100, pp: 30, eff: { stat: { spd: -1 }, p: 10 }, fx: 'acid', d: '潑出強酸。有時會降低對手的魔防。' },
  harden: { n: '變硬', t: '一般', cat: '變', pp: 30, stat: { who: 'self', def: 1 }, fx: 'buff', d: '全身用力變硬，提高自己的物防。' },
  ironWall: { n: '岩壁', t: '岩', cat: '變', pp: 15, stat: { who: 'self', def: 2 }, fx: 'buff', d: '全身化為岩壁，大幅提高自己的物防。' },
  rockThrow: { n: '落石', t: '岩', cat: '物', pow: 50, acc: 90, pp: 15, fx: 'rock', d: '拋出小石頭攻擊。' },
  rockSlide: { n: '岩崩', t: '岩', cat: '物', pow: 75, acc: 90, pp: 10, eff: { flinch: 1, p: 30 }, fx: 'rock', d: '砸下大岩石。有時會讓對手退縮。' },
  bite: { n: '咬住', t: '一般', cat: '物', pow: 60, acc: 100, pp: 25, eff: { flinch: 1, p: 30 }, fx: 'bite', d: '用利牙咬住。有時會讓對手退縮。' },
  howl: { n: '嚎叫', t: '一般', cat: '變', pp: 40, stat: { who: 'self', atk: 1 }, fx: 'buff', d: '長嚎鼓舞自己，提高物攻。' },
  quickAttack: { n: '電光一閃', t: '一般', cat: '物', pow: 40, acc: 100, pp: 30, prio: 1, fx: 'quick', d: '以極快的速度撞向對手。必定能先出手。' },
  sing: { n: '催眠曲', t: '一般', cat: '變', acc: 55, pp: 15, st: 'slp', fx: 'sing', d: '唱出溫柔的歌，讓對手睡著。' },
  lick: { n: '舌舔', t: '一般', cat: '物', pow: 30, acc: 100, pp: 30, eff: { st: 'par', p: 30 }, fx: 'hit', d: '用長舌頭舔對手。有時會讓對手麻痺。' },
  agility: { n: '高速移動', t: '雷', cat: '變', pp: 30, stat: { who: 'self', spe: 2 }, fx: 'buff', d: '放鬆身體，大幅提高自己的速度。' },
  stomp: { n: '重踏', t: '一般', cat: '物', pow: 65, acc: 100, pp: 20, eff: { flinch: 1, p: 30 }, fx: 'stomp', d: '用巨大的腳踩踏。有時會讓對手退縮。' },
  ancientRoar: { n: '遠古咆哮', t: '岩', cat: '變', acc: 100, pp: 10, stat: { who: 'foe', atk: -1, spa: -1 }, fx: 'roar', d: '發出震撼大地的咆哮，降低對手的物攻和魔攻。' },
  golemFist: { n: '岩石粉碎拳', t: '岩', cat: '物', pow: 100, acc: 100, pp: 5, charge: 1, fx: 'bigRock', d: '凝聚大地之力，下一回合全力揮拳。' },
  struggle: { n: '掙扎', t: '一般', cat: '物', pow: 50, acc: 100, pp: 1, recoil: 0.25, fx: 'hit', d: '沒有PP時拼命掙扎。自己也會受傷。' },
};

const SPECIES = {
  mush: { n: '嘟嘟菇', t: '草', base: [42, 45, 50, 38, 45, 30], exp: 55, gold: 8, learn: [[1, 'tackle'], [3, 'absorb'], [6, 'poisonPowder'], [9, 'sleepPowder']], mat: 'shroomCap', dex: '蕈傘上的斑點在夜裡會發出微光。' },
  bird: { n: '啾啾鳥', t: '飛', base: [40, 45, 38, 35, 35, 58], exp: 52, gold: 8, learn: [[1, 'peck'], [1, 'growl'], [5, 'gust'], [8, 'quickAttack']], mat: 'feather', dex: '一大早就在樹梢上啾啾叫個不停。' },
  pebble: { n: '石丸', t: '岩', base: [40, 45, 58, 25, 35, 20], exp: 60, gold: 10, learn: [[1, 'tackle'], [6, 'harden'], [7, 'rockThrow']], mat: 'stone', dex: '總是一臉不高興。身上長著青苔。' },
  slime: { n: '泡泡姆', t: '水', base: [55, 35, 40, 50, 45, 30], exp: 55, gold: 9, learn: [[1, 'bubble'], [1, 'growl'], [7, 'waterGun']], mat: 'gel', dex: '由清澈的泉水聚集而成的魔物。' },
  fox: { n: '焰狐', t: '火', base: [45, 55, 42, 55, 45, 65], exp: 66, gold: 12, learn: [[1, 'scratch'], [1, 'tailWhip'], [4, 'ember'], [9, 'quickAttack']], mat: 'foxfire', dex: '興奮時尾巴的火焰會燒得更旺。' },
  bee: { n: '電電蜂', t: '雷', base: [42, 50, 40, 55, 40, 70], exp: 64, gold: 12, learn: [[1, 'poisonSting'], [1, 'shock'], [7, 'thunderWave'], [10, 'agility']], mat: 'stinger', trait: 'swift', dex: '翅膀高速振動時會產生電流。總是搶先出手。' },
  frog: { n: '紫斑蛙', t: '毒', base: [60, 50, 45, 50, 50, 40], exp: 64, gold: 12, learn: [[1, 'lick'], [4, 'acid'], [7, 'sing']], mat: 'frogSkin', dex: '身上的斑點越鮮豔，毒性就越強。' },
  wolf: { n: '狂牙狼', t: '一般', base: [60, 54, 48, 40, 46, 62], exp: 95, gold: 40, elite: 1, drop: 'fangDagger', trait: 'berserk', learn: [[1, 'tackle'], [1, 'howl'], [1, 'quickAttack'], [1, 'bite']], dex: '晨霧道路的狼群首領。臉上有一道傷疤。' },
  flower: { n: '荊棘魔花', t: '草', base: [68, 58, 62, 72, 65, 42], exp: 105, gold: 45, elite: 1, drop: 'thornRing', learn: [[1, 'vineWhip'], [1, 'sleepPowder'], [1, 'megaDrain'], [1, 'poisonPowder']], dex: '守護著森林深處果實的食人花。' },
  croc: { n: '沼澤鱷', t: '水', base: [72, 76, 70, 50, 55, 52], exp: 115, gold: 50, elite: 1, drop: 'scaleArmor', learn: [[1, 'tailWhip'], [1, 'harden'], [1, 'waterGun'], [1, 'bite']], dex: '盤據在橋頭，不讓任何人通過。' },
  thornMush: { n: '毒孢菇', t: '毒', base: [50, 48, 52, 50, 50, 32], exp: 70, gold: 14, learn: [[1, 'absorb'], [1, 'poisonPowder'], [5, 'acid'], [9, 'sleepPowder']], mat: 'spore', trait: 'healer', dex: '只生長在迷霧森林深處。孢子帶有劇毒，受傷時會吸收養分回復。' },
  nightBird: { n: '夜梟', t: '飛', base: [52, 55, 45, 50, 45, 66], exp: 72, gold: 14, learn: [[1, 'peck'], [1, 'sing'], [5, 'gust'], [9, 'quickAttack']], mat: 'feather', trait: 'swift', dex: '在森林的陰影裡也看得一清二楚。歌聲會讓人昏昏欲睡。' },
  leafFox: { n: '翠狐', t: '草', base: [52, 60, 48, 58, 50, 70], exp: 76, gold: 16, learn: [[1, 'scratch'], [1, 'vineWhip'], [6, 'absorb'], [9, 'quickAttack']], mat: 'leaf', trait: 'berserk', dex: '尾巴的葉子能吸收陽光。受傷後會變得兇暴。' },
  mossGiant: { n: '苔石巨人', t: '草', base: [80, 70, 78, 55, 60, 30], exp: 140, gold: 60, elite: 1, drop: 'mossBracer', trait: 'healer', learn: [[1, 'vineWhip'], [1, 'stomp'], [1, 'harden'], [1, 'megaDrain']], dex: '被青苔覆蓋的古老石像。守護著森林的秘密，怕火。' },
  caveBat: { n: '洞窟飛影', t: '飛', base: [55, 62, 48, 50, 48, 80], exp: 82, gold: 18, mat: 'feather', trait: 'swift', learn: [[1, 'peck'], [1, 'gust'], [1, 'quickAttack'], [10, 'sing']], dex: '棲息在地下水道的黑影。速度極快。' },
  mudSlime: { n: '泥沼姆', t: '水', base: [70, 50, 55, 55, 55, 30], exp: 82, gold: 18, mat: 'gel', trait: 'healer', learn: [[1, 'bubble'], [1, 'waterGun'], [1, 'harden'], [10, 'acid']], dex: '混著泥沙的泡泡姆。會吸收污水回復。' },
  crystalPebble: { n: '晶石丸', t: '岩', base: [55, 60, 80, 45, 55, 30], exp: 88, gold: 22, mat: 'crystal', learn: [[1, 'tackle'], [1, 'harden'], [1, 'rockThrow'], [12, 'rockSlide']], dex: '身上長滿水晶的石丸。非常堅硬。' },
  crystalGolem: { n: '水晶魔像', t: '岩', base: [90, 62, 85, 60, 65, 40], exp: 320, gold: 0, boss: 1, drop: 'crystalHeart', learn: [[1, 'rockThrow'], [1, 'stomp'], [1, 'prismRay'], [1, 'ancientRoar']], dex: '沉睡在井底深處的水晶石像。據說和異界之門同時誕生。' },
  golem: { n: '古岩魔像', t: '岩', base: [82, 48, 80, 45, 55, 35], exp: 200, gold: 0, boss: 1, drop: 'golemVisor', learn: [[1, 'rockThrow'], [1, 'stomp'], [1, 'ironWall'], [1, 'ancientRoar']], dex: '守護古代遺跡的石像。沉睡了千年後甦醒。' },
};

const HERO_LEARN = [[1, 'slash'], [1, 'glare'], [4, 'flameSlash'], [6, 'focus'], [8, 'aquaBlade'], [10, 'thunder'], [11, 'gale'], [13, 'leafBlade'], [15, 'heal'], [18, 'blaze']];

const ITEMS = {
  potion: { n: '傷藥', price: 100, d: '恢復20點HP。', use: 'heal', v: 20 },
  superPotion: { n: '好傷藥', price: 350, d: '恢復60點HP。', use: 'heal', v: 60 },
  antidote: { n: '解毒藥', price: 80, d: '治療中毒狀態。', use: 'cure', v: 'psn' },
  parlyzHeal: { n: '解麻藥', price: 100, d: '治療麻痺狀態。', use: 'cure', v: 'par' },
  awakening: { n: '醒神草', price: 120, d: '治療睡眠狀態。', use: 'cure', v: 'slp' },
  burnHeal: { n: '燙傷膏', price: 120, d: '治療灼傷狀態。', use: 'cure', v: 'brn' },
  ether: { n: '活力茶', price: 300, d: '恢復25點MP。', use: 'mp', v: 25 },
  manaPotion: { n: '魔力藥水', price: 150, d: '恢復15點MP。', use: 'mp', v: 15 },
  hiEther: { n: '高級魔力藥水', price: 700, d: '恢復50點MP。', use: 'mp', v: 50 },
  returnWing: { n: '歸鄉之羽', price: 400, once: 1, d: '緊急時使用，立刻回到萌芽鎮。戰鬥中也能用（頭目戰除外）。一次只能帶一個。', use: 'home' },
  smoke: { n: '煙霧彈', price: 150, d: '在戰鬥中使用，必定能從野生魔物身邊逃走。', use: 'escape' },
  powerFruit: { n: '力量果實', price: 2500, sell: 500, d: '神奇的果實。吃下後力量永久+2。', use: 'boost', v: { str: 2 } },
  luckClover: { n: '幸運草', price: 0, sell: 300, d: '四片葉子的幸運草。使用後幸運永久+2。', use: 'boost', v: { luk: 2 } },
  wisdomFruit: { n: '智慧果實', price: 0, sell: 500, d: '神奇的果實。吃下後智力永久+2。', use: 'boost', v: { int: 2 } },
  elixir: { n: '萬靈藥', price: 800, d: 'HP和MP完全恢復，並治好所有異常狀態。', use: 'full' },
  tpBook: { n: '天賦之書', price: 3000, d: '記載著古老修練法的書。使用後獲得1點天賦點。（每買一本會漲價）', use: 'tp' },
  herb: { n: '藥草', mat: 1, price: 0, sell: 10, d: '野外採集的藥草。可以用來調製藥品。' },
  shroomCap: { n: '蕈傘', mat: 1, price: 0, sell: 15, d: '嘟嘟菇的蕈傘。' }, feather: { n: '羽毛', mat: 1, price: 0, sell: 15, d: '輕盈的羽毛。' },
  stone: { n: '硬石', mat: 1, price: 0, sell: 15, d: '石丸身上的硬石。' }, gel: { n: '凝膠', mat: 1, price: 0, sell: 15, d: '黏黏的凝膠。' },
  foxfire: { n: '狐火毛', mat: 1, price: 0, sell: 25, d: '還帶著餘溫的狐狸毛。' }, stinger: { n: '蜂針', mat: 1, price: 0, sell: 25, d: '帶電的蜂針。' },
  frogSkin: { n: '蛙皮', mat: 1, price: 0, sell: 25, d: '有彈性的蛙皮。' }, spore: { n: '毒孢子', mat: 1, price: 0, sell: 30, d: '裝在袋子裡的毒孢子。' },
  leaf: { n: '靈葉', mat: 1, price: 0, sell: 30, d: '翠狐尾巴上的葉子。' }, crystal: { n: '水晶碎片', mat: 1, price: 0, sell: 60, d: '地下水道的水晶碎片。' },
  rope: { n: '繩索', key: 1, once: 1, price: 500, d: '結實的長繩索。可以用來下到深處。' },
  phone: { n: '手機', key: 1, use: 'phone', d: '從原本的世界帶來的手機。' },
  license: { n: '冒險者證', key: 1, d: '村長交給你的冒險者證明。持有它就能走出萌芽鎮。' },
};
const shopList = () => { const f = Game.st.flags; return SHOP_LIST.filter(k => !(k === 'superPotion' && f.caravan === 'lost' && !f.bandit)).concat(f.croc ? ['hiEther', 'knightSword', 'magusStaff', 'guardHelm', 'chainMail'] : [], f.golem ? ['elixir', 'tpBook'] : [], f.caravan === 'lost' && f.golem ? ['rope'] : []); };
const PEDDLER_LIST = ['rope', 'superPotion', 'elixir', 'ether', 'hiEther', 'powerFruit', 'tpBook', 'knightHelm', 'knightGreaves'];
const priceOf = (k, n = 0) => Math.round(((ITEMS[k] || GEAR[k]).price + (k === 'tpBook' ? 1500 * ((Game.st.tpBought || 0) + n) : 0) + (ITEMS[k] && ITEMS[k].use === 'boost' ? 1500 * ((Game.st.fruitBought || 0) + n) : 0)) * (Game.st.flags.caravan === 'saved' ? 0.9 : Game.st.flags.caravan === 'lost' && k === 'rope' ? 3 : 1));
const priceFor = (k, q) => { let t = 0; for (let i = 0; i < q; i++) t += priceOf(k, i); return t; }; // v20.7: bulk buys pay each book's rising price (天賦之書 +1500 G per book)
const RECIPES = [
  { out: 'potion', n: 2, mats: { herb: 2 } }, { out: 'superPotion', mats: { herb: 3, gel: 1 } },
  { out: 'featherBoots', mats: { feather: 4 }, gold: 300 }, { out: 'stoneMail', mats: { stone: 5 }, gold: 400 },
  { out: 'foxBlade', mats: { foxfire: 4, stinger: 2 }, gold: 800 }, { out: 'frogCloak', mats: { frogSkin: 4, gel: 2 }, gold: 600 },
  { out: 'sporeCharm', mats: { spore: 4, shroomCap: 3 }, gold: 600 }, { out: 'crystalBlade', mats: { crystal: 5, leaf: 3 }, gold: 1500 },
];
const SHOP_LIST = ['potion', 'superPotion', 'antidote', 'parlyzHeal', 'awakening', 'burnHeal', 'manaPotion', 'ether', 'smoke', 'returnWing', 'ironSword', 'apprenticeStaff', 'clothCap', 'leather', 'travelBoots', 'charm', 'swiftFeather'];
const CLASSES = {
  swordsman: { n: '劍士', tier: 1, st: { atk: 3, def: 2, crit: 3 }, move: 'powerSlash', d: '擅長近身劍術。物攻、物防、會心提升。' },
  mage: { n: '魔導士', tier: 1, st: { spa: 4, spd: 2, elem: 10 }, move: 'manaBurst', d: '操控魔力。魔攻、魔防、屬性傷害提升。' },
  guardian: { n: '守護者', tier: 1, st: { hp: 10, def: 3, spd: 3 }, move: 'guardStrike', d: '堅守不倒。HP、物防、魔防提升。' },
  swordmaster: { n: '劍聖', tier: 2, from: 'swordsman', st: { atk: 7, def: 3, crit: 9 }, move: 'bladeStorm', d: '劍術的極致。會心大幅提升。' },
  berserker: { n: '狂戰士', tier: 2, from: 'swordsman', st: { atk: 10, crit: 3, rage: 1 }, move: 'recklessSlash', d: '物攻大幅提升。HP低於一半時傷害+30%。' },
  pyromancer: { n: '火焰術士', tier: 2, from: 'mage', st: { spa: 8, spd: 3, elem: 10, fireUp: 20 }, move: 'inferno', d: '魔攻提升，火系技能傷害再+20%。' },
  stormcaller: { n: '雷霆術士', tier: 2, from: 'mage', st: { spa: 8, spd: 3, elem: 10, boltUp: 20 }, move: 'thunderstorm', d: '魔攻提升，雷系技能傷害再+20%。' },
  paladin: { n: '聖騎士', tier: 2, from: 'guardian', st: { hp: 20, def: 5, spd: 5, atk: 2 }, move: 'holyLight', d: '神聖的守護者。能用聖光治療自己。' },
  otherworlder: { n: '異界勇者', tier: 3, st: { hp: 10, atk: 5, def: 3, spa: 5, spd: 3, spe: 4, crit: 5 }, move: 'dawnBreak', d: '只屬於異界來客的隱藏職業。全能力提升。' },
};
const TALENT_LINES = ['攻擊', '魔法', '生存'];
const TALENTS = [
  { id: 'blade', n: '武器精通', line: 0, max: 3, d: '物理攻擊變強。', st: { atk: 2 } },
  { id: 'vital', n: '要害打擊', line: 0, max: 3, d: '更容易打出會心一擊（傷害×1.5）。', st: { crit: 3 } },
  { id: 'breaker', n: '破甲之心', line: 0, max: 1, d: '物理攻擊無視對手15%的物防。', st: { pierceT: 15 }, req: 'blade' },
  { id: 'mana', n: '魔力親和', line: 1, max: 3, d: '魔法攻擊和治癒變強。', st: { spa: 2 } },
  { id: 'elem', n: '元素掌握', line: 1, max: 3, d: '火、水、草、雷屬性的傷害提高。', st: { elem: 8 } },
  { id: 'barrier', n: '魔力泉湧', line: 1, max: 1, d: '戰鬥中每回合結束時回復4%最大MP。', st: { mpRegen: 4 }, req: 'mana' },
  { id: 'body', n: '強健體魄', line: 2, max: 3, d: '最大HP提高，更耐打。', st: { hp: 5 } },
  { id: 'agile', n: '身手矯健', line: 2, max: 3, d: '更容易閃開對手的攻擊。', st: { eva: 3 } },
  { id: 'counter', n: '反擊架勢', line: 2, max: 1, d: '選擇「防禦」時被攻擊，會立刻反擊對手（70%傷害）。', st: { counter: 1 }, req: 'body' },
];

/* ---------------- Maps ----------------
 T tree  . grass  , grass2  f flower(red) y flower(yellow)  : path  # tall grass  L ledge  W water  = bridge
 o rock  b bush  S sign  Y spring  F fence  s stone floor  m mossy floor  P pillar  R ruin wall  X void
 interior: x wall(top)  w window  c clock  k bookshelf-wall  h goods shelf-wall  a map picture  n floor
           B bed  Q table  K shelf  C counter  p plant  r rug  D door mat  V display case */
const MAPS = {
  town: {
    name: '萌芽鎮', music: 'town', outdoor: 1, border: 'T', road: 'cobble',
    rows: [
      'TTTTTTTTTT::TTTTTTTTTT',
      'TTTTTTTT..::..TTTTTTTT',
      'TT.f......::.....y..TT',
      'TT........::........TT',
      'TT........::........TT',
      'TT........::........TT',
      'TT........::........TT',
      'TT...::::::::::::...TT',
      'TT.f......::N.S..y..TT',
      'TT..y.....::........TT',
      'TT........::........TT',
      'TT........::........TT',
      'TT........::........TT',
      'TT........::........TT',
      'TT...::::::::::::...TT',
      'TT.f......::.....y..TT',
      'TTWWWW.,..,,..f,....TT',
      'TTWWWW..y.....FFFFF.TT',
      'TTWWW..S.......f.U..TT',
      'TTTTTTTTTTTTTTTTTTTTTT',
    ],
    buildings: [
      { kind: 'house', x: 3, y: 3, w: 5, h: 4, door: 2, to: ['home', 4, 7] },
      { kind: 'elder', x: 13, y: 3, w: 6, h: 4, door: 2, to: ['elder', 4, 7], sign: 1 },
      { kind: 'inn', x: 3, y: 10, w: 5, h: 4, door: 2, to: ['inn', 4, 7], sign: 1 },
      { kind: 'shop', x: 14, y: 10, w: 5, h: 4, door: 2, to: ['shop', 4, 7], sign: 1 },
    ],
    signs: { '14,8': '「萌芽鎮」\n新芽萌發、希望啟程的小鎮。', '7,18': '「小心池塘」\n請勿在池塘邊奔跑。' },
    connect: { n: { map: 'route', dx: 0 } },
    npcs: [
      { id: 'gatekeeper', x: 12, y: 1, dir: 'down', look: 'girl', name: '小芽' },
      { id: 'kid', x: 8, y: 9, dir: 'down', look: 'kid', walk: 2 },
      { id: 'grandpa', x: 7, y: 16, dir: 'left', look: 'old' },
      { id: 'florist', x: 16, y: 16, dir: 'down', look: 'woman2', walk: 1 },
      { id: 'smith', x: 13, y: 16, dir: 'down', look: 'man', name: '鐵匠' },
      { id: 'peddler', x: 8, y: 12, dir: 'down', look: 'clerk', name: '行商', show: st => st.flags.caravan === 'saved' },
    ],
    triggers: [{ x: 10, y: 1, id: 'exitBlock' }, { x: 11, y: 1, id: 'exitBlock' }],
  },
  home: {
    name: '瑪莎的家', music: 'town', rows: [
      'xxxxxxxxxx',
      'xwxxcxxwxx',
      'BnnnnnnnKp',
      'BnnnnnnnKn',
      'nnnQQnnnnn',
      'nnnQQnnnnn',
      'nnnnnnnnnn',
      'nnnnDnnnnn',
    ], exit: { x: 4, y: 7, to: ['town', 5, 7] }, wallPal: '',
    npcs: [{ id: 'mom', x: 6, y: 4, dir: 'left', look: 'mom', name: '瑪莎' }],
  },
  elder: {
    name: '村長的家', music: 'town', rows: [
      'xxxxxxxxxx',
      'xkkxwwxkkx',
      'pnnnnnnnnp',
      'nnnrrrrnnn',
      'nnnrrrrnnn',
      'nnnrrrrnnn',
      'nnnnnnnnnn',
      'nnnnDnnnnn',
    ], exit: { x: 4, y: 7, to: ['town', 15, 7] }, wallPal: 'g',
    npcs: [{ id: 'elder', x: 4, y: 3, dir: 'down', look: 'elder', name: '村長' }, { id: 'apprentice', x: 8, y: 5, dir: 'left', look: 'kid2', walk: 1 }],
  },
  inn: {
    name: '旅店', music: 'town', rows: [
      'xxxxxxxxxx',
      'xwxxcxxwxx',
      'BnnnnnnnnB',
      'BnCCCCCCnB',
      'nnnnnnnnnn',
      'nnnnnnnnnn',
      'pnnnnnnnnp',
      'nnnnDnnnnn',
    ], exit: { x: 4, y: 7, to: ['town', 5, 14] }, wallPal: 'g',
    npcs: [{ id: 'healer', x: 4, y: 2, dir: 'down', look: 'healer', name: '旅店老闆娘' }, { id: 'traveler', x: 7, y: 5, dir: 'left', look: 'man' }],
  },
  shop: {
    name: '道具店', music: 'town', rows: [
      'xxxxxxxxxx',
      'xhhxwwxhhx',
      'nnnnnnnnnn',
      'CCCnnnnVVn',
      'nnnnnnnVVn',
      'nnnnnnnnnn',
      'pnnnnnnnnp',
      'nnnnDnnnnn',
    ], exit: { x: 4, y: 7, to: ['town', 16, 14] }, wallPal: 'b',
    npcs: [{ id: 'clerk', x: 1, y: 2, dir: 'down', look: 'clerk', name: '店員' }, { id: 'customer', x: 5, y: 5, dir: 'up', look: 'woman2', walk: 1 }],
  },
  route: {
    name: '晨霧道路', music: 'route', outdoor: 1, border: 'T',
    rows: [
      'TTTTTTTTTR::RTTTTTTTTT',
      'TTTTTTTTTR::RTTTTTTTTT',
      'TTTT.f....::....y.TTTT',
      'TT...YY...::...S....TT',
      'TT...YY...::........TT',
      'TT.f......::..o..y..TT',
      'TTTTT.....::.....TTTTT',
      'TT###.....::.....###TT',
      'TT####....::....####TT',
      'TT####....::....####TT',
      'TT..##....::....##..TT',
      'TTWWWWWWWW=WWWWWWWWWTT',
      'TTWWWWWWWW=WWWWWWWWWTT',
      'TT........:.........TT',
      'TT..f.....::.....y..TT',
      'TTTTTT....::....TTTTTT',
      'TT...T....::...#####TT',
      'TT.,.T##..::..######TT',
      'TT...T##..::..######TT',
      'TT...T##..::...#####TT',
      'TTT.TT##..::....##..TT',
      'TT.####...::........TT',
      'TT.#####..::..###...TT',
      'TT..####..::.#####..TT',
      'TTS.......::..###...TT',
      'TTLLLLLL..::..LLLLLLTT',
      '..........::........TT',
      'TT.###....::...TTTTTTT',
      'TT####....::...T....TT',
      'TT####....::........TT',
      'TT.###....::...T....TT',
      'TT........::...TTTTTTT',
      'TTTTTT....::....TTTTTT',
      'TT........::........TT',
      'TTLLLL....::....LLLLTT',
      'TT........::........TT',
      'TT.###....::...###..TT',
      'TT####..f.::..####..TT',
      'TT####....::..####..TT',
      'TT.##.....::...##.y.TT',
      'TT....S...::........TT',
      'TT..f.....::......f.TT',
      'TTTTTTTTT.::.TTTTTTTTT',
      'TTTTTTTTTT::TTTTTTTTTT',
    ],
    edgeWarps: [{ dir: 'left', at: [26], to: ['forest', 21, 11, 'left'] }],
    gathers: [{ id: 'gr1', x: 5, y: 26, mat: 'herb' }, { id: 'gr2', x: 18, y: 14, mat: 'herb' }],
    signs: { '2,24': '「← 迷霧森林」\n樹林深處據說藏著古老的秘密。', '15,3': '「↑ 古岩遺跡」\n最近魔物暴動，魔像甦醒。非冒險者禁止進入！', '6,40': '「晨霧道路」\n↑ 古岩遺跡　↓ 萌芽鎮' },
    connect: { s: { map: 'town', dx: 0 } },
    northWarp: { x: [10, 11], to: ['ruins', 7, 13, 'up'] },
    gate: { x: 9, y: 0 },
    npcs: [
      { id: 'hiker', x: 8, y: 34, dir: 'right', look: 'man' },
      { id: 'guard', x: 12, y: 2, dir: 'down', look: 'guard', name: '守衛' },
      { id: 'girl2', x: 16, y: 13, dir: 'left', look: 'girl', walk: 1 },
      { id: 'caravan', x: 12, y: 22, dir: 'left', look: 'man', name: '商人', show: st => st.flags.wolf && !st.flags.caravan },
      { id: 'lostBoy', x: 3, y: 31, dir: 'right', look: 'kid', name: '小麥', show: st => st.flags.q1 && st.flags.q1res !== 'home' },
    ],
    elites: [
      { id: 'wolf', sp: 'wolf', lv: 8, x: 16, y: 29, dir: 'left', sight: 3 },
      { id: 'flower', sp: 'flower', lv: 11, x: 3, y: 18, dir: 'down', sight: 2 },
      { id: 'croc', sp: 'croc', lv: 12, x: 10, y: 13, dir: 'down', sight: 3 },
    ],
    items: [
      { id: 'i1', x: 18, y: 28, item: 'superPotion' },
      { id: 'i2', x: 2, y: 16, item: 'powerFruit' },
      { id: 'i3', x: 19, y: 24, item: 'potion', n: 2 },
      { id: 'i4', x: 2, y: 33, item: 'parlyzHeal' },
      { id: 'i5', x: 19, y: 5, gold: 300 },
      { id: 'i6', x: 7, y: 28, item: 'ether' },
      { id: 'i7', x: 13, y: 21, item: 'awakening' },
    ],
    springs: 1,
    gearPool: ['ironSword', 'apprenticeStaff', 'mistDagger', 'clothCap', 'leather', 'travelBoots', 'mistBoots', 'swiftFeather', 'wolfNecklace'],
    encounters: [
      { y0: 26, y1: 99, rate: 0.11, table: [['mush', 3, 5, 32], ['bird', 3, 5, 32], ['pebble', 3, 5, 12], ['slime', 4, 5, 24]] },
      { y0: 11, y1: 25, rate: 0.11, table: [['fox', 6, 8, 20], ['bee', 6, 8, 20], ['frog', 6, 8, 20], ['mush', 6, 8, 10], ['bird', 6, 8, 10], ['pebble', 6, 8, 10], ['slime', 7, 8, 10]] },
      { y0: 0, y1: 10, rate: 0.12, table: [['fox', 8, 10, 25], ['bee', 8, 10, 25], ['frog', 8, 10, 25], ['pebble', 8, 10, 15], ['slime', 8, 10, 10]] },
    ],
  },
  forest: {
    name: '迷霧森林', music: 'route', outdoor: 1, border: 'T', battleBg: 'forest',
    rows: [
      'TTTTTTTTTTTTTTTTTTTTTT',
      'T....TTTTTTTTTTTTTTTTT',
      'T.yf.TTTT###...TTTTTTT',
      'T....TTT####....T....T',
      'TTtTTTT####.....T.f..T',
      'TT..TT.....##...T....T',
      'TT.......#####..TT.TTT',
      'TT..o..######....T.TTT',
      'TTT...,,####.........T',
      'TT....,,......##.....T',
      'TT##..TTTT...####....T',
      'T####.TTTT...####.....',
      'T####...........##...T',
      'TT##....f....TTT.....T',
      'TT......TT...TTT..#..T',
      'TTT..TTTTT..........#T',
      'T.....TTT...###...##.T',
      'T.WW..TTT..####....TTT',
      'T.WW.......####.....TT',
      'T......y...##....f..TT',
      'TTTTTTTTTTTTTTTTTTTTTT',
    ],
    edgeWarps: [{ dir: 'right', at: [11], to: ['route', 0, 26, 'right'] }],
    npcs: [{ id: 'herbalist', x: 19, y: 4, dir: 'down', look: 'old', name: '藥草師' }, { id: 'tim', x: 3, y: 15, dir: 'down', look: 'kid2', name: '提姆', show: st => st.flags.q2 && st.flags.q2res !== 'home' && !st.flags.q2done }],
    elites: [{ id: 'mossGiant', sp: 'mossGiant', lv: 13, x: 4, y: 17, dir: 'right', sight: 2 }],
    items: [
      { id: 'f1', x: 14, y: 2, item: 'wisdomFruit' }, { id: 'f2', x: 4, y: 9, item: 'hunterLeather', q: 2 }, { id: 'f3', x: 19, y: 14, item: 'superPotion', n: 2 },
      { id: 'f4', x: 16, y: 19, gold: 500 }, { id: 'f5', x: 1, y: 19, item: 'luckClover' }, { id: 'f6', x: 1, y: 1, item: 'dawnSword', q: 4 },
      { id: 'f7', x: 19, y: 9, item: 'pocketWatch', show: st => st.com && st.com.c4 && st.com.c4.s === 'on' },
    ],
    gearPool: ['mistDagger', 'oakStaff', 'guardHelm', 'hunterLeather', 'mistBoots', 'wolfNecklace', 'herbPouch'],
    gathers: [{ id: 'gf1', x: 9, y: 12, mat: 'herb' }, { id: 'gf2', x: 9, y: 18, mat: 'herb' }],
    encounters: [{ y0: 0, y1: 99, rate: 0.12, table: [['thornMush', 9, 11, 25], ['nightBird', 9, 11, 25], ['leafFox', 10, 12, 25], ['frog', 9, 11, 10], ['bee', 9, 11, 15]] }],
  },
  sewer: {
    name: '地下水道', music: 'ruins', border: 'R', battleBg: 'ruins', encAll: 1,
    rows: [
      'RRRRRRRRRRRRRRRR',
      'RRRRRRsssRRRRRRR',
      'RRRRRssssssRRRRR',
      'RRRRRssssssRRRRR',
      'RRRRRRRssRRRRRRR',
      'RsssssRssRsssssR',
      'RsWWsssssssWWssR',
      'RsWWsRRssRRWWssR',
      'RssssRsssssRsssR',
      'RRsRRRsRRssRsRRR',
      'RssssssRRssssssR',
      'RsRRRRssssRRRRsR',
      'RssssssssssssYsR',
      'RRRRRRRsRRRRRRRR',
    ],
    exit: { x: 7, y: 13, to: ['town', 18, 18] },
    boss: { sp: 'crystalGolem', lv: 18, x: 7, y: 2, flag: 'crystalBoss', ev: 'hiddenBoss' },
    items: [{ id: 's1', x: 1, y: 8, item: 'ether', n: 2 }, { id: 's2', x: 14, y: 5, item: 'superPotion', n: 2 }, { id: 's3', x: 1, y: 12, gold: 800 }, { id: 's4', x: 14, y: 10, item: 'powerFruit' }],
    gearPool: ['knightSword', 'ruinStaff', 'knightHelm', 'chainMail', 'knightGreaves', 'thornRing', 'herbPouch'],
    gathers: [{ id: 'gs1', x: 4, y: 6, mat: 'crystal' }, { id: 'gs2', x: 10, y: 10, mat: 'crystal' }],
    encounters: [{ y0: 0, y1: 99, rate: 0.08, table: [['caveBat', 14, 16, 35], ['mudSlime', 14, 16, 35], ['crystalPebble', 15, 17, 30]] }],
  },
  ruins: {
    name: '古岩遺跡', music: 'ruins', border: 'X', battleBg: 'ruins',
    rows: [
      'RRRRRRRRRRRRRRRR',
      'RRRRRRRRRRRRRRRR',
      'RRsPssssssssPsRR',
      'RRsssssmssssssRR',
      'RRssssssssssmsRR',
      'RRsPssssssssPsRR',
      'RRssmsssssssssRR',
      'RRssssssssssssRR',
      'RRsPssssssssPsRR',
      'RRssssssmsssssRR',
      'RRmsssssssssssRR',
      'RRRRRRssssRRRRRR',
      'XXXXXRssssRXXXXX',
      'XXXXXXssssXXXXXX',
    ],
    southWarp: { to: ['route', 10, 1, 'down'] },
    gate: { x: 7, y: 0, big: 1 },
    boss: { sp: 'golem', lv: 14, x: 7, y: 3 },
    triggers: Array.from({ length: 12 }, (_, i) => ({ x: 2 + i, y: 7, id: 'bossLine' })),
  },
};

const ELITE_TEXT = {
  wolf: ['嗷嗚——！', '狂牙狼露出了利牙！'],
  flower: ['……沙沙沙……', '荊棘魔花張開了血盆大口！'],
  croc: ['咕嚕嚕……', '沼澤鱷擋住了橋頭，不肯讓路！'],
  mossGiant: ['……轟隆……', '苔石巨人擋住了去路！'],
};
