/* ===================== DATA ===================== */
const TYPES = ['一般', '火', '水', '草', '雷', '岩', '毒', '飛'];
const EFF = {
  '一般': { '岩': 0.5 },
  '火': { '草': 2, '火': 0.5, '水': 0.5, '岩': 0.5 },
  '水': { '火': 2, '岩': 2, '水': 0.5, '草': 0.5 },
  '草': { '水': 2, '岩': 2, '火': 0.5, '草': 0.5, '毒': 0.5, '飛': 0.5 },
  '雷': { '水': 2, '飛': 2, '雷': 0.5, '草': 0.5 },
  '岩': { '火': 2, '飛': 2 },
  '毒': { '草': 2, '毒': 0.5, '岩': 0.5 },
  '飛': { '草': 2, '雷': 0.5, '岩': 0.5 },
};
const typeMult = (atk, def) => def ? ((EFF[atk] || {})[def] ?? 1) : 1;
const STAT_NAMES = { hp: 'HP', atk: '物攻', def: '物防', spa: '魔攻', spd: '魔防', spe: '速度' };
const QUALITY = [null, ['普通', '#c9cfe4'], ['優良', '#72e39a'], ['稀有', '#86b4ff'], ['史詩', '#c58cff'], ['傳說', '#ffb454']];
// classic six attributes for the hero
const ATTRS = ['str', 'agi', 'vit', 'int', 'dex', 'luk'];
const ATTR_NAMES = { str: '力量', agi: '敏捷', vit: '體力', int: '智力', dex: '靈巧', luk: '幸運' };
const HERO_ATTR_INIT = { str: 6, agi: 5, vit: 6, int: 5, dex: 5, luk: 4 };   // at Lv5
const HERO_GROWTH = { str: 0.45, agi: 0.40, vit: 0.50, int: 0.40, dex: 0.35, luk: 0.25 }; // points per level (low growth)
const HERO_GROWTH_OFS = { str: 0.05, agi: 0.95, vit: 0.45, int: 0.35, dex: 0.9, luk: 0.85 }; // staggered so each level raises 2–3 attributes
const STAT_KEYS = ['hp', 'atk', 'def', 'spa', 'spd', 'spe'];

// cat: 物=physical 特=special 變=status
const MOVES = {
  slash: { n: '揮砍', t: '一般', cat: '物', pow: 40, acc: 100, pp: 35, fx: 'slash', d: '揮劍砍向對手。' },
  glare: { n: '瞪眼', t: '一般', cat: '變', acc: 100, pp: 30, stat: { who: 'foe', def: -1 }, fx: 'glare', d: '用銳利的眼神瞪視對手，降低對手的物防。' },
  flameSlash: { n: '火焰斬', t: '火', cat: '物', pow: 45, acc: 100, pp: 25, eff: { st: 'brn', p: 10 }, fx: 'fireSlash', d: '以燃燒的劍刃砍擊。有時會讓對手灼傷。' },
  focus: { n: '集氣', t: '一般', cat: '變', pp: 20, stat: { who: 'self', atk: 1, spa: 1 }, fx: 'buff', d: '集中精神，提高自己的物攻和魔攻。' },
  armorBreak: { n: '破甲斬', t: '一般', cat: '物', pow: 45, acc: 95, pp: 15, eff: { stat: { def: -1 }, p: 100 }, fx: 'slash', d: '劈開對手的防具。必定降低對手的物防。' },
  barrier: { n: '魔法護盾', t: '一般', cat: '變', pp: 10, shield: 3, fx: 'guard', d: '展開魔法護盾，3回合內受到的傷害減少40%。' },
  aquaBlade: { n: '水流刃', t: '水', cat: '特', pow: 50, acc: 100, pp: 25, fx: 'water', d: '揮出激流般的水刃。會讓對手潮濕，再用雷系攻擊就能引發感電。' },
  thunder: { n: '落雷', t: '雷', cat: '特', pow: 55, acc: 95, pp: 20, eff: { st: 'par', p: 10 }, fx: 'thunder', d: '召喚雷電打向對手。對潮濕的對手會感電：傷害1.5倍並麻痺。' },
  gale: { n: '疾風刺', t: '一般', cat: '物', pow: 40, acc: 100, pp: 30, prio: 1, fx: 'quick', d: '以疾風般的速度突刺。必定能先出手。' },
  leafBlade: { n: '翠葉斬', t: '草', cat: '物', pow: 65, acc: 95, pp: 20, crit: 1, fx: 'leaf', d: '以葉片之力斬擊。容易擊中要害。' },
  heal: { n: '治癒光', t: '一般', cat: '變', pp: 10, heal: 0.5, fx: 'heal', d: '溫暖的光芒，恢復自己最大HP的一半。' },
  blaze: { n: '烈焰斬', t: '火', cat: '物', pow: 80, acc: 95, pp: 15, eff: { st: 'brn', p: 10 }, fx: 'fireSlash', d: '全力揮出熊熊燃燒的一擊。有時會讓對手灼傷。' },
  // monster moves
  tackle: { n: '撞擊', t: '一般', cat: '物', pow: 35, acc: 95, pp: 35, fx: 'hit', d: '用整個身體撞向對手。' },
  growl: { n: '叫聲', t: '一般', cat: '變', acc: 100, pp: 40, stat: { who: 'foe', atk: -1 }, fx: 'sound', d: '可愛地叫，降低對手的物攻。' },
  tailWhip: { n: '搖尾巴', t: '一般', cat: '變', acc: 100, pp: 30, stat: { who: 'foe', def: -1 }, fx: 'glare', d: '可愛地搖尾巴，降低對手的物防。' },
  scratch: { n: '抓', t: '一般', cat: '物', pow: 40, acc: 100, pp: 35, fx: 'scratch', d: '用爪子抓對手。' },
  peck: { n: '啄', t: '飛', cat: '物', pow: 35, acc: 100, pp: 35, fx: 'hit', d: '用尖嘴啄對手。' },
  gust: { n: '起風', t: '飛', cat: '特', pow: 40, acc: 100, pp: 35, fx: 'wind', d: '拍動翅膀颳起強風。' },
  absorb: { n: '吸取', t: '草', cat: '特', pow: 25, acc: 100, pp: 25, drain: 0.5, fx: 'drain', d: '吸取對手的養分，恢復自己的HP。' },
  megaDrain: { n: '超級吸取', t: '草', cat: '特', pow: 40, acc: 100, pp: 15, drain: 0.5, fx: 'drain', d: '大量吸取對手的養分，恢復自己的HP。' },
  poisonPowder: { n: '毒粉', t: '毒', cat: '變', acc: 75, pp: 35, st: 'psn', fx: 'powder', d: '撒出毒粉，讓對手中毒。' },
  sleepPowder: { n: '睡眠粉', t: '草', cat: '變', acc: 75, pp: 15, st: 'slp', fx: 'powderS', d: '撒出催眠粉，讓對手睡著。' },
  vineWhip: { n: '藤鞭', t: '草', cat: '物', pow: 45, acc: 100, pp: 25, fx: 'vine', d: '用藤蔓抽打對手。' },
  bubble: { n: '泡沫', t: '水', cat: '特', pow: 30, acc: 100, pp: 30, eff: { stat: { spe: -1 }, p: 10 }, fx: 'bubble', d: '吐出泡沫攻擊。有時會降低對手的速度。' },
  waterGun: { n: '水槍', t: '水', cat: '特', pow: 40, acc: 100, pp: 25, fx: 'water', d: '噴出強勁的水柱。' },
  ember: { n: '火花', t: '火', cat: '特', pow: 40, acc: 100, pp: 25, eff: { st: 'brn', p: 10 }, fx: 'ember', d: '噴出小小的火焰。有時會讓對手灼傷。' },
  shock: { n: '電擊', t: '雷', cat: '特', pow: 40, acc: 100, pp: 30, eff: { st: 'par', p: 10 }, fx: 'spark', d: '放出電流。有時會讓對手麻痺。' },
  thunderWave: { n: '電磁波', t: '雷', cat: '變', acc: 90, pp: 20, st: 'par', fx: 'spark', d: '放出微弱的電磁波，讓對手麻痺。' },
  poisonSting: { n: '毒針', t: '毒', cat: '物', pow: 15, acc: 100, pp: 35, eff: { st: 'psn', p: 30 }, fx: 'sting', d: '用毒針刺對手。有時會讓對手中毒。' },
  acid: { n: '溶解液', t: '毒', cat: '特', pow: 40, acc: 100, pp: 30, eff: { stat: { spd: -1 }, p: 10 }, fx: 'acid', d: '潑出強酸。有時會降低對手的魔防。' },
  harden: { n: '變硬', t: '一般', cat: '變', pp: 30, stat: { who: 'self', def: 1 }, fx: 'buff', d: '全身用力變硬，提高自己的物防。' },
  ironWall: { n: '岩壁', t: '岩', cat: '變', pp: 15, stat: { who: 'self', def: 2 }, fx: 'buff', d: '全身化為岩壁，大幅提高自己的物防。' },
  rockThrow: { n: '落石', t: '岩', cat: '物', pow: 50, acc: 90, pp: 15, fx: 'rock', d: '拋出小石頭攻擊。' },
  rockSlide: { n: '岩崩', t: '岩', cat: '物', pow: 75, acc: 90, pp: 10, eff: { flinch: 1, p: 30 }, fx: 'rock', d: '砸下大岩石。有時會讓對手退縮。' },
  bite: { n: '咬住', t: '一般', cat: '物', pow: 60, acc: 100, pp: 25, eff: { flinch: 1, p: 30 }, fx: 'bite', d: '用利牙咬住。有時會讓對手退縮。' },
  howl: { n: '嚎叫', t: '一般', cat: '變', pp: 40, stat: { who: 'self', atk: 1 }, fx: 'buff', d: '長嚎鼓舞自己，提高物攻。' },
  quickAttack: { n: '電光一閃', t: '一般', cat: '物', pow: 40, acc: 100, pp: 30, prio: 1, fx: 'quick', d: '以極快的速度撞向對手。必定能先出手。' },
  sing: { n: '催眠曲', t: '一般', cat: '變', acc: 55, pp: 15, st: 'slp', fx: 'sing', d: '唱出溫柔的歌，讓對手睡著。' },
  lick: { n: '舌舔', t: '一般', cat: '物', pow: 30, acc: 100, pp: 30, eff: { st: 'par', p: 30 }, fx: 'hit', d: '用長舌頭舔對手。有時會讓對手麻痺。' },
  agility: { n: '高速移動', t: '雷', cat: '變', pp: 30, stat: { who: 'self', spe: 2 }, fx: 'buff', d: '放鬆身體，大幅提高自己的速度。' },
  stomp: { n: '重踏', t: '一般', cat: '物', pow: 65, acc: 100, pp: 20, eff: { flinch: 1, p: 30 }, fx: 'stomp', d: '用巨大的腳踩踏。有時會讓對手退縮。' },
  ancientRoar: { n: '遠古咆哮', t: '岩', cat: '變', acc: 100, pp: 10, stat: { who: 'foe', atk: -1, spa: -1 }, fx: 'roar', d: '發出震撼大地的咆哮，降低對手的物攻和魔攻。' },
  golemFist: { n: '岩石粉碎拳', t: '岩', cat: '物', pow: 100, acc: 100, pp: 5, charge: 1, fx: 'bigRock', d: '凝聚大地之力，下一回合全力揮拳。' },
  struggle: { n: '掙扎', t: '一般', cat: '物', pow: 50, acc: 100, pp: 1, recoil: 0.25, fx: 'hit', d: '沒有PP時拼命掙扎。自己也會受傷。' },
};

const SPECIES = {
  mush: { n: '嘟嘟菇', t: '草', base: [42, 45, 50, 38, 45, 30], exp: 55, gold: 8, learn: [[1, 'tackle'], [3, 'absorb'], [6, 'poisonPowder'], [9, 'sleepPowder']], dex: '蕈傘上的斑點在夜裡會發出微光。' },
  bird: { n: '啾啾鳥', t: '飛', base: [40, 45, 38, 35, 35, 58], exp: 52, gold: 8, learn: [[1, 'peck'], [1, 'growl'], [5, 'gust'], [8, 'quickAttack']], dex: '一大早就在樹梢上啾啾叫個不停。' },
  pebble: { n: '石丸', t: '岩', base: [40, 45, 58, 25, 35, 20], exp: 60, gold: 10, learn: [[1, 'tackle'], [6, 'harden'], [7, 'rockThrow']], dex: '總是一臉不高興。身上長著青苔。' },
  slime: { n: '泡泡姆', t: '水', base: [55, 35, 40, 50, 45, 30], exp: 55, gold: 9, learn: [[1, 'bubble'], [1, 'growl'], [7, 'waterGun']], dex: '由清澈的泉水聚集而成的魔物。' },
  fox: { n: '焰狐', t: '火', base: [45, 55, 42, 55, 45, 65], exp: 66, gold: 12, learn: [[1, 'scratch'], [1, 'tailWhip'], [4, 'ember'], [9, 'quickAttack']], dex: '興奮時尾巴的火焰會燒得更旺。' },
  bee: { n: '電電蜂', t: '雷', base: [42, 50, 40, 55, 40, 70], exp: 64, gold: 12, learn: [[1, 'poisonSting'], [1, 'shock'], [7, 'thunderWave'], [10, 'agility']], dex: '翅膀高速振動時會產生電流。' },
  frog: { n: '紫斑蛙', t: '毒', base: [60, 50, 45, 50, 50, 40], exp: 64, gold: 12, learn: [[1, 'lick'], [4, 'acid'], [7, 'sing']], dex: '身上的斑點越鮮豔，毒性就越強。' },
  wolf: { n: '狂牙狼', t: '一般', base: [60, 54, 48, 40, 46, 62], exp: 95, gold: 40, elite: 1, drop: 'fangDagger', learn: [[1, 'tackle'], [1, 'howl'], [1, 'quickAttack'], [1, 'bite']], dex: '晨霧道路的狼群首領。臉上有一道傷疤。' },
  flower: { n: '荊棘魔花', t: '草', base: [68, 58, 62, 72, 65, 42], exp: 105, gold: 45, elite: 1, drop: 'thornRing', learn: [[1, 'vineWhip'], [1, 'sleepPowder'], [1, 'megaDrain'], [1, 'poisonPowder']], dex: '守護著森林深處果實的食人花。' },
  croc: { n: '沼澤鱷', t: '水', base: [72, 76, 70, 50, 55, 52], exp: 115, gold: 50, elite: 1, drop: 'scaleArmor', learn: [[1, 'tailWhip'], [1, 'harden'], [1, 'waterGun'], [1, 'bite']], dex: '盤據在橋頭，不讓任何人通過。' },
  thornMush: { n: '毒孢菇', t: '毒', base: [50, 48, 52, 50, 50, 32], exp: 70, gold: 14, learn: [[1, 'absorb'], [1, 'poisonPowder'], [5, 'acid'], [9, 'sleepPowder']], dex: '只生長在迷霧森林深處。孢子帶有劇毒。' },
  nightBird: { n: '夜梟', t: '飛', base: [52, 55, 45, 50, 45, 66], exp: 72, gold: 14, learn: [[1, 'peck'], [1, 'sing'], [5, 'gust'], [9, 'quickAttack']], dex: '在森林的陰影裡也看得一清二楚。歌聲會讓人昏昏欲睡。' },
  leafFox: { n: '翠狐', t: '草', base: [52, 60, 48, 58, 50, 70], exp: 76, gold: 16, learn: [[1, 'scratch'], [1, 'vineWhip'], [6, 'absorb'], [9, 'quickAttack']], dex: '尾巴的葉子能吸收陽光。和焰狐是遠親。' },
  mossGiant: { n: '苔石巨人', t: '草', base: [80, 70, 78, 55, 60, 30], exp: 140, gold: 60, elite: 1, drop: 'mossBracer', learn: [[1, 'vineWhip'], [1, 'stomp'], [1, 'harden'], [1, 'megaDrain']], dex: '被青苔覆蓋的古老石像。守護著森林的秘密，怕火。' },
  golem: { n: '古岩魔像', t: '岩', base: [82, 48, 80, 45, 55, 35], exp: 200, gold: 0, boss: 1, drop: 'golemCore', learn: [[1, 'rockThrow'], [1, 'stomp'], [1, 'ironWall'], [1, 'ancientRoar']], dex: '守護古代遺跡的石像。沉睡了千年後甦醒。' },
};

const HERO_LEARN = [[1, 'slash'], [1, 'glare'], [4, 'flameSlash'], [6, 'focus'], [8, 'aquaBlade'], [10, 'thunder'], [11, 'gale'], [13, 'leafBlade'], [15, 'heal'], [18, 'blaze']];

const ITEMS = {
  potion: { n: '傷藥', price: 100, d: '恢復20點HP。', use: 'heal', v: 20 },
  superPotion: { n: '好傷藥', price: 350, d: '恢復60點HP。', use: 'heal', v: 60 },
  antidote: { n: '解毒藥', price: 80, d: '治療中毒狀態。', use: 'cure', v: 'psn' },
  parlyzHeal: { n: '解麻藥', price: 100, d: '治療麻痺狀態。', use: 'cure', v: 'par' },
  awakening: { n: '醒神草', price: 120, d: '治療睡眠狀態。', use: 'cure', v: 'slp' },
  burnHeal: { n: '燙傷膏', price: 120, d: '治療灼傷狀態。', use: 'cure', v: 'brn' },
  ether: { n: '活力茶', price: 300, d: '所有技能的PP各恢復10點。', use: 'pp', v: 10 },
  smoke: { n: '煙霧彈', price: 150, d: '在戰鬥中使用，必定能從野生魔物身邊逃走。', use: 'escape' },
  powerFruit: { n: '力量果實', price: 0, sell: 500, d: '神奇的果實。吃下後力量永久+2。', use: 'boost', v: { str: 2 } },
  fangDagger: { n: '狼牙短劍', q: 2, price: 0, sell: 400, equip: 'weapon', bonus: { atk: 5 }, aff: { crit: 6, vs: ['一般', 20] }, d: '用狂牙狼的尖牙磨成的短劍。' },
  thornRing: { n: '荊棘指環', q: 3, price: 0, sell: 600, equip: 'acc', bonus: { spa: 2 }, aff: { drain: 12, hit: 5 }, d: '纏著活荊棘的指環。攻擊時會吸取生命。' },
  scaleArmor: { n: '鱷鱗甲', q: 3, price: 0, sell: 700, equip: 'armor', bonus: { def: 4, spd: 3 }, aff: { resist: ['水', 30] }, d: '用沼澤鱷的鱗片做成的鎧甲。' },
  golemCore: { n: '古岩之心', q: 4, price: 0, sell: 0, equip: 'acc', bonus: { hp: 10, def: 3 }, aff: { crit: 4, resist: ['岩', 20] }, d: '魔像核心的碎片，仍有微弱的脈動。' },
  knightSword: { n: '騎士長劍', q: 2, price: 2600, equip: 'weapon', bonus: { atk: 7 }, aff: { hit: 5 }, d: '王都騎士團制式的長劍。' },
  chainMail: { n: '鎖子甲', q: 2, price: 2000, equip: 'armor', bonus: { def: 5, spd: 3 }, d: '細密鐵環編成的鎧甲。' },
  hunterLeather: { n: '獵人皮甲', q: 2, price: 0, sell: 500, equip: 'armor', bonus: { def: 3, spd: 2 }, aff: { eva: 5 }, d: '森林獵人穿的輕便皮甲。' },
  mossBracer: { n: '苔石護腕', q: 3, price: 0, sell: 600, equip: 'acc', bonus: { def: 3, hp: 8 }, aff: { resist: ['草', 20] }, d: '苔石巨人身上剝落的石環。' },
  dawnSword: { n: '晨曦之劍', q: 5, price: 0, sell: 0, equip: 'weapon', bonus: { atk: 9 }, aff: { crit: 8, vs: ['岩', 25] }, d: '藏在森林深處的古劍，劍身映著黎明的光。' },
  luckClover: { n: '幸運草', price: 0, sell: 300, d: '四片葉子的幸運草。使用後幸運永久+2。', use: 'boost', v: { luk: 2 } },
  wisdomFruit: { n: '智慧果實', price: 0, sell: 500, d: '神奇的果實。吃下後智力永久+2。', use: 'boost', v: { int: 2 } },
  ironSword: { n: '鐵劍', price: 1200, equip: 'weapon', bonus: { atk: 4 }, d: '堅固的鐵劍。物攻+4' },
  woodSword: { n: '木劍', price: 0, sell: 50, equip: 'weapon', bonus: { atk: 1 }, d: '練習用的木劍。物攻+1' },
  clothes: { n: '旅行布衣', price: 0, sell: 50, equip: 'armor', bonus: { def: 1 }, d: '輕便的旅行服裝。物防+1' },
  leather: { n: '皮甲', price: 900, equip: 'armor', bonus: { def: 3, spd: 2 }, d: '結實的皮甲。物防+3 魔防+2' },
  moonCharm: { n: '月光護符', q: 4, price: 0, sell: 0, equip: 'acc', bonus: { spa: 3, spe: 3 }, d: '從井底撈起的古老護符，散發著淡淡月光。魔攻+3 速度+3' },
  charm: { n: '魔法護符', price: 1000, equip: 'acc', bonus: { spa: 4 }, d: '注入魔力的護符。魔攻+4' },
  boots: { n: '疾風靴', price: 800, equip: 'acc', bonus: { spe: 4 }, d: '穿上後腳步變得輕快。速度+4' },
  uniform: { n: '學生制服', price: 0, equip: 'armor', bonus: { def: 1 }, d: '原本世界學校的制服。在這裡好像很少見。物防+1' },
  phone: { n: '手機', key: 1, use: 'phone', d: '從原本的世界帶來的手機。' },
  license: { n: '冒險者證', key: 1, d: '村長交給你的冒險者證明。持有它就能走出萌芽鎮。' },
};
const shopList = () => SHOP_LIST.concat(Game.st.flags.croc ? ['knightSword', 'chainMail'] : []);
const SHOP_LIST = ['potion', 'superPotion', 'antidote', 'parlyzHeal', 'awakening', 'burnHeal', 'ether', 'smoke', 'ironSword', 'leather', 'charm', 'boots'];
const TALENT_LINES = ['劍術', '魔法', '生存'];
const TALENTS = [
  { id: 'blade', n: '劍術精通', line: 0, max: 3, d: '物攻+2／級', st: { atk: 2 } },
  { id: 'vital', n: '要害打擊', line: 0, max: 3, d: '會心+3%／級', st: { crit: 3 } },
  { id: 'breaker', n: '破甲斬', line: 0, max: 1, d: '習得技能「破甲斬」：造成傷害並必定降低對手物防。', move: 'armorBreak', req: 'blade' },
  { id: 'mana', n: '魔力親和', line: 1, max: 3, d: '魔攻+2／級', st: { spa: 2 } },
  { id: 'elem', n: '元素掌握', line: 1, max: 3, d: '火、水、雷等屬性技能的傷害+8%／級', st: { elem: 8 } },
  { id: 'barrier', n: '魔法護盾', line: 1, max: 1, d: '習得技能「魔法護盾」：3回合內受到的傷害減少40%。', move: 'barrier', req: 'mana' },
  { id: 'body', n: '強健體魄', line: 2, max: 3, d: '最大HP+5／級', st: { hp: 5 } },
  { id: 'agile', n: '身手矯健', line: 2, max: 3, d: '迴避+3%／級', st: { eva: 3 } },
  { id: 'counter', n: '反擊架勢', line: 2, max: 1, d: '選擇「防禦」時被攻擊，會立刻反擊對手。', st: { counter: 1 }, req: 'body' },
];
const EQUIP_SLOTS = { weapon: '武器', armor: '防具', acc: '飾品' };

/* ---------------- Maps ----------------
 T tree  . grass  , grass2  f flower(red) y flower(yellow)  : path  # tall grass  L ledge  W water  = bridge
 o rock  b bush  S sign  Y spring  F fence  s stone floor  m mossy floor  P pillar  R ruin wall  X void
 interior: x wall(top)  w window  c clock  k bookshelf-wall  h goods shelf-wall  a map picture  n floor
           B bed  Q table  K shelf  C counter  p plant  r rug  D door mat  V display case */
const MAPS = {
  town: {
    name: '萌芽鎮', music: 'town', outdoor: 1, border: 'T', road: 'cobble',
    rows: [
      'TTTTTTTTTT::TTTTTTTTTT',
      'TTTTTTTT..::..TTTTTTTT',
      'TT.f......::.....y..TT',
      'TT........::........TT',
      'TT........::........TT',
      'TT........::........TT',
      'TT........::........TT',
      'TT...::::::::::::...TT',
      'TT.f......::..S..y..TT',
      'TT..y.....::........TT',
      'TT........::........TT',
      'TT........::........TT',
      'TT........::........TT',
      'TT........::........TT',
      'TT...::::::::::::...TT',
      'TT.f......::.....y..TT',
      'TTWWWW.,..,,..f,....TT',
      'TTWWWW..y.....FFFFF.TT',
      'TTWWW..S.......f.U..TT',
      'TTTTTTTTTTTTTTTTTTTTTT',
    ],
    buildings: [
      { kind: 'house', x: 3, y: 3, w: 5, h: 4, door: 2, to: ['home', 4, 7] },
      { kind: 'elder', x: 13, y: 3, w: 6, h: 4, door: 2, to: ['elder', 4, 7], sign: 1 },
      { kind: 'inn', x: 3, y: 10, w: 5, h: 4, door: 2, to: ['inn', 4, 7], sign: 1 },
      { kind: 'shop', x: 14, y: 10, w: 5, h: 4, door: 2, to: ['shop', 4, 7], sign: 1 },
    ],
    signs: { '14,8': '「萌芽鎮」\n新芽萌發、希望啟程的小鎮。', '7,18': '「小心池塘」\n請勿在池塘邊奔跑。' },
    connect: { n: { map: 'route', dx: 0 } },
    npcs: [
      { id: 'gatekeeper', x: 12, y: 1, dir: 'down', look: 'girl', name: '小芽' },
      { id: 'kid', x: 8, y: 9, dir: 'down', look: 'kid', walk: 2 },
      { id: 'grandpa', x: 7, y: 16, dir: 'left', look: 'old' },
      { id: 'florist', x: 16, y: 16, dir: 'down', look: 'woman', walk: 1 },
    ],
    triggers: [{ x: 10, y: 1, id: 'exitBlock' }, { x: 11, y: 1, id: 'exitBlock' }],
  },
  home: {
    name: '瑪莎的家', music: 'town', rows: [
      'xxxxxxxxxx',
      'xwxxcxxwxx',
      'BnnnnnnnKp',
      'BnnnnnnnKn',
      'nnnQQnnnnn',
      'nnnQQnnnnn',
      'nnnnnnnnnn',
      'nnnnDnnnnn',
    ], exit: { x: 4, y: 7, to: ['town', 5, 7] }, wallPal: '',
    npcs: [{ id: 'mom', x: 6, y: 4, dir: 'left', look: 'mom', name: '瑪莎' }],
  },
  elder: {
    name: '村長的家', music: 'town', rows: [
      'xxxxxxxxxx',
      'xkkxwwxkkx',
      'pnnnnnnnnp',
      'nnnrrrrnnn',
      'nnnrrrrnnn',
      'nnnrrrrnnn',
      'nnnnnnnnnn',
      'nnnnDnnnnn',
    ], exit: { x: 4, y: 7, to: ['town', 15, 7] }, wallPal: 'g',
    npcs: [{ id: 'elder', x: 4, y: 3, dir: 'down', look: 'elder', name: '村長' }, { id: 'apprentice', x: 8, y: 5, dir: 'left', look: 'kid2', walk: 1 }],
  },
  inn: {
    name: '旅店', music: 'town', rows: [
      'xxxxxxxxxx',
      'xwxxcxxwxx',
      'BnnnnnnnnB',
      'BnCCCCCCnB',
      'nnnnnnnnnn',
      'nnnnnnnnnn',
      'pnnnnnnnnp',
      'nnnnDnnnnn',
    ], exit: { x: 4, y: 7, to: ['town', 5, 14] }, wallPal: 'g',
    npcs: [{ id: 'healer', x: 4, y: 2, dir: 'down', look: 'healer', name: '旅店老闆娘' }, { id: 'traveler', x: 7, y: 5, dir: 'left', look: 'man' }],
  },
  shop: {
    name: '道具店', music: 'town', rows: [
      'xxxxxxxxxx',
      'xhhxwwxhhx',
      'nnnnnnnnnn',
      'CCCnnnnVVn',
      'nnnnnnnVVn',
      'nnnnnnnnnn',
      'pnnnnnnnnp',
      'nnnnDnnnnn',
    ], exit: { x: 4, y: 7, to: ['town', 16, 14] }, wallPal: 'b',
    npcs: [{ id: 'clerk', x: 1, y: 2, dir: 'down', look: 'clerk', name: '店員' }, { id: 'customer', x: 5, y: 5, dir: 'up', look: 'woman2', walk: 1 }],
  },
  route: {
    name: '晨霧道路', music: 'route', outdoor: 1, border: 'T',
    rows: [
      'TTTTTTTTTR::RTTTTTTTTT',
      'TTTTTTTTTR::RTTTTTTTTT',
      'TTTT.f....::....y.TTTT',
      'TT...YY...::...S....TT',
      'TT...YY...::........TT',
      'TT.f......::..o..y..TT',
      'TTTTT.....::.....TTTTT',
      'TT###.....::.....###TT',
      'TT####....::....####TT',
      'TT####....::....####TT',
      'TT..##....::....##..TT',
      'TTWWWWWWWW=WWWWWWWWWTT',
      'TTWWWWWWWW=WWWWWWWWWTT',
      'TT........:.........TT',
      'TT..f.....::.....y..TT',
      'TTTTTT....::....TTTTTT',
      'TT...T....::...#####TT',
      'TT.,.T##..::..######TT',
      'TT...T##..::..######TT',
      'TT...T##..::...#####TT',
      'TTT.TT##..::....##..TT',
      'TT.####...::........TT',
      'TT.#####..::..###...TT',
      'TT..####..::.#####..TT',
      'TTS.......::..###...TT',
      'TTLLLLLL..::..LLLLLLTT',
      '..........::........TT',
      'TT.###....::...TTTTTTT',
      'TT####....::...T....TT',
      'TT####....::........TT',
      'TT.###....::...T....TT',
      'TT........::...TTTTTTT',
      'TTTTTT....::....TTTTTT',
      'TT........::........TT',
      'TTLLLL....::....LLLLTT',
      'TT........::........TT',
      'TT.###....::...###..TT',
      'TT####..f.::..####..TT',
      'TT####....::..####..TT',
      'TT.##.....::...##.y.TT',
      'TT....S...::........TT',
      'TT..f.....::......f.TT',
      'TTTTTTTTT.::.TTTTTTTTT',
      'TTTTTTTTTT::TTTTTTTTTT',
    ],
    edgeWarps: [{ dir: 'left', at: [26], to: ['forest', 21, 11, 'left'] }],
    signs: { '2,24': '「← 迷霧森林」\n樹林深處據說藏著古老的秘密。', '15,3': '「↑ 古岩遺跡」\n傳說中的異界之門就在遺跡深處。危險！', '6,40': '「晨霧道路」\n↑ 古岩遺跡　↓ 萌芽鎮' },
    connect: { s: { map: 'town', dx: 0 } },
    northWarp: { x: [10, 11], to: ['ruins', 7, 13, 'up'] },
    gate: { x: 9, y: 0 },
    npcs: [
      { id: 'hiker', x: 8, y: 34, dir: 'right', look: 'man' },
      { id: 'guard', x: 12, y: 2, dir: 'down', look: 'guard', name: '守衛' },
      { id: 'girl2', x: 16, y: 13, dir: 'left', look: 'girl', walk: 1 },
      { id: 'lostBoy', x: 3, y: 31, dir: 'right', look: 'kid', name: '小麥', show: st => st.flags.q1 && st.flags.q1res !== 'home' },
    ],
    elites: [
      { id: 'wolf', sp: 'wolf', lv: 8, x: 16, y: 29, dir: 'left', sight: 5 },
      { id: 'flower', sp: 'flower', lv: 11, x: 3, y: 18, dir: 'down', sight: 2 },
      { id: 'croc', sp: 'croc', lv: 12, x: 10, y: 13, dir: 'down', sight: 3 },
    ],
    items: [
      { id: 'i1', x: 18, y: 28, item: 'superPotion' },
      { id: 'i2', x: 2, y: 16, item: 'powerFruit' },
      { id: 'i3', x: 19, y: 24, item: 'potion', n: 2 },
      { id: 'i4', x: 2, y: 33, item: 'parlyzHeal' },
      { id: 'i5', x: 19, y: 5, gold: 300 },
      { id: 'i6', x: 7, y: 28, item: 'ether' },
      { id: 'i7', x: 13, y: 21, item: 'awakening' },
    ],
    springs: 1,
    encounters: [
      { y0: 26, y1: 99, rate: 0.11, table: [['mush', 3, 5, 32], ['bird', 3, 5, 32], ['pebble', 3, 5, 12], ['slime', 4, 5, 24]] },
      { y0: 11, y1: 25, rate: 0.11, table: [['fox', 6, 8, 20], ['bee', 6, 8, 20], ['frog', 6, 8, 20], ['mush', 6, 8, 10], ['bird', 6, 8, 10], ['pebble', 6, 8, 10], ['slime', 7, 8, 10]] },
      { y0: 0, y1: 10, rate: 0.12, table: [['fox', 8, 10, 25], ['bee', 8, 10, 25], ['frog', 8, 10, 25], ['pebble', 8, 10, 15], ['slime', 8, 10, 10]] },
    ],
  },
  forest: {
    name: '迷霧森林', music: 'route', outdoor: 1, border: 'T', battleBg: 'forest',
    rows: [
      'TTTTTTTTTTTTTTTTTTTTTT',
      'T....TTTTTTTTTTTTTTTTT',
      'T.yf.TTTT###...TTTTTTT',
      'T....TTT####....T....T',
      'TTtTTTT####.....T.f..T',
      'TT..TT.....##...T....T',
      'TT.......#####..TT.TTT',
      'TT..o..######....T.TTT',
      'TTT...,,####.........T',
      'TT....,,......##.....T',
      'TT##..TTTT...####....T',
      'T####.TTTT...####......',
      'T####...........##...T',
      'TT##....f....TTT.....T',
      'TT......TT...TTT..#..T',
      'TTT..TTTTT..........#T',
      'T.....TTT...###...##.T',
      'T.WW..TTT..####....TTT',
      'T.WW.......####.....TT',
      'T......y...##....f..TT',
      'TTTTTTTTTTTTTTTTTTTTTT',
    ],
    edgeWarps: [{ dir: 'right', at: [11], to: ['route', 0, 26, 'right'] }],
    npcs: [{ id: 'herbalist', x: 19, y: 4, dir: 'down', look: 'old', name: '藥草師' }],
    elites: [{ id: 'mossGiant', sp: 'mossGiant', lv: 13, x: 4, y: 17, dir: 'right', sight: 2 }],
    items: [
      { id: 'f1', x: 14, y: 2, item: 'wisdomFruit' }, { id: 'f2', x: 4, y: 9, item: 'hunterLeather' }, { id: 'f3', x: 19, y: 14, item: 'superPotion', n: 2 },
      { id: 'f4', x: 16, y: 19, gold: 500 }, { id: 'f5', x: 1, y: 19, item: 'luckClover' }, { id: 'f6', x: 1, y: 1, item: 'dawnSword' },
    ],
    encounters: [{ y0: 0, y1: 99, rate: 0.12, table: [['thornMush', 9, 11, 25], ['nightBird', 9, 11, 25], ['leafFox', 10, 12, 25], ['frog', 9, 11, 10], ['bee', 9, 11, 15]] }],
  },
  ruins: {
    name: '古岩遺跡', music: 'ruins', border: 'X', battleBg: 'ruins',
    rows: [
      'RRRRRRRRRRRRRRRR',
      'RRRRRRRRRRRRRRRR',
      'RRsPssssssssPsRR',
      'RRsssssmssssssRR',
      'RRssssssssssmsRR',
      'RRsPssssssssPsRR',
      'RRssmsssssssssRR',
      'RRssssssssssssRR',
      'RRsPssssssssPsRR',
      'RRssssssmsssssRR',
      'RRmsssssssssssRR',
      'RRRRRRssssRRRRRR',
      'XXXXXRssssRXXXXX',
      'XXXXXXssssXXXXXX',
    ],
    southWarp: { to: ['route', 10, 1, 'down'] },
    gate: { x: 7, y: 0, big: 1 },
    boss: { sp: 'golem', lv: 14, x: 7, y: 3 },
    triggers: Array.from({ length: 12 }, (_, i) => ({ x: 2 + i, y: 7, id: 'bossLine' })),
  },
};

const ELITE_TEXT = {
  wolf: ['嗷嗚——！', '狂牙狼露出了利牙！'],
  flower: ['……沙沙沙……', '荊棘魔花張開了血盆大口！'],
  croc: ['咕嚕嚕……', '沼澤鱷擋住了橋頭，不肯讓路！'],
  mossGiant: ['……轟隆……', '苔石巨人擋住了去路！'],
};
