/* ===================== MONSTER VFX: own particle materials + one recipe per monster skill ===================== */
// Monster effects never use the hero's materials (clean light lines, crescents, beams, hex shields).
// Their look: every shape has a dark outline, murky/sinister palette, organic forms (gouges, fangs, globs, shards, spores).
const MOL = '#12070e';
const MC = { red: '#c02838', blood: '#8a1020', bone: '#e8e0cc', rock: '#8a6a4a', dirt: '#6a4a2a', fire: '#e0481a', fire2: '#ffb040', ghost: '#60d8e0', water: '#2f7f9a', water2: '#8ad0d8', leaf: '#3a7a2a', leaf2: '#8ac040', poison: '#8a3aa0', poison2: '#b8e040', volt: '#b040f0', volt2: '#f4b0ff', dark: '#3a1a5a', dark2: '#b890ff', feather: '#9aa4bc', silk: '#e8e8f0', crystal: '#80e0ff' };
function mTaper(x, p, pts, w, col) { // filled tapered stroke along pts
  const L = [], R = []; for (let i = 0; i < pts.length; i++) { const a = pts[Math.max(0, i - 1)], b = pts[Math.min(pts.length - 1, i + 1)], dx = b[0] - a[0], dy = b[1] - a[1], l = Math.hypot(dx, dy) || 1, hw = w * Math.sin(Math.PI * i / (pts.length - 1)) / 2 + 0.3; L.push([pts[i][0] - dy / l * hw, pts[i][1] + dx / l * hw]); R.push([pts[i][0] + dy / l * hw, pts[i][1] - dx / l * hw]); }
  x.beginPath(); L.forEach(([a, b], i) => i ? x.lineTo(a, b) : x.moveTo(a, b)); for (let i = R.length - 1; i >= 0; i--) x.lineTo(R[i][0], R[i][1]); x.closePath();
  x.lineWidth = 2; x.strokeStyle = MOL; x.stroke(); x.fillStyle = col; x.fill();
}
function mPoly(x, pts, col, ol = true) { x.beginPath(); pts.forEach(([a, b], i) => i ? x.lineTo(a, b) : x.moveTo(a, b)); x.closePath(); if (ol) { x.lineWidth = 2; x.strokeStyle = MOL; x.stroke(); } x.fillStyle = col; x.fill(); }
function mCirc(x, X, Y, r, col, ol = true) { x.beginPath(); x.arc(X, Y, Math.max(0.5, r), 0, 7); if (ol) { x.lineWidth = 2; x.strokeStyle = MOL; x.stroke(); } x.fillStyle = col; x.fill(); }
const MON_PK = {
  mgouge(x, p, a) { const g = clamp(p.t / (p.grow || 4), 0, 1), dx = Math.cos(p.ang), dy = Math.sin(p.ang), nx = -dy, ny = dx, pts = []; for (let i = 0; i <= 8; i++) { const u = i / 8 * g, b = Math.sin(Math.PI * u) * (p.bend || 4); pts.push([p.x + dx * p.len * (u - 0.5) + nx * b, p.y + dy * p.len * (u - 0.5) + ny * b]); } x.globalAlpha = Math.min(1, a * 1.6); mTaper(x, p, pts, p.w || 5, p.c); if (p.c2) { x.globalAlpha = a; x.strokeStyle = p.c2; x.lineWidth = 1; x.beginPath(); pts.forEach(([u, v], i) => i ? x.lineTo(u, v) : x.moveTo(u, v)); x.stroke(); } },
  mfang(x, p, a) { const g = clamp(p.t / (p.life * 0.4), 0, 1), w = p.w || 30, gap = 14 * (1 - g) + 1, n = 5, tw = w / n; x.globalAlpha = Math.min(1, a * 2); for (const s of [-1, 1]) { const by = p.y + s * (gap + 5); mPoly(x, [[p.x - w / 2 - 2, by], [p.x + w / 2 + 2, by], [p.x + w / 2 + 2, by + s * 4], [p.x - w / 2 - 2, by + s * 4]], p.gum || '#5a1020'); for (let i = 0; i < n; i++) { const tx = p.x - w / 2 + i * tw; mPoly(x, [[tx, by], [tx + tw, by], [tx + tw / 2, by - s * (i % 2 ? 6 : 9)]], p.c || MC.bone); } } },
  mglob(x, p, a) { x.globalAlpha = Math.min(1, a * 2); const r = p.r || 4; mCirc(x, p.x, p.y, r, p.c); mCirc(x, p.x - r * 0.35, p.y - r * 0.35, r * 0.3, shade(p.c, 0.5), false); mCirc(x, p.x + r * 0.2, p.y + r + 1, r * 0.35, p.c, false); },
  mdrop(x, p, a) { x.globalAlpha = a; const r = p.r || 2; mPoly(x, [[p.x, p.y - r * 2.4], [p.x + r, p.y], [p.x, p.y + r], [p.x - r, p.y]], p.c); },
  mbubble(x, p, a) { x.globalAlpha = a; const r = p.r || 4; x.beginPath(); x.arc(p.x, p.y, r, 0, 7); x.lineWidth = 3; x.strokeStyle = MOL; x.stroke(); x.lineWidth = 1.5; x.strokeStyle = p.c; x.stroke(); x.globalAlpha = a * 0.35; x.fillStyle = p.c; x.fill(); x.globalAlpha = a; x.fillStyle = '#ffffff'; x.fillRect(Math.round(p.x - r / 2), Math.round(p.y - r / 2), 1, 1); },
  mshard(x, p, a) { const r = p.r || 4, rot = (p.rot || 0) + p.t * (p.vr ?? 0.3), pts = []; for (let i = 0; i < 5; i++) { const an = rot + i * 1.2566, rr = r * (i % 2 ? 0.55 : 1) * (1 + ((p.seed || 1) * (i + 3) % 5) / 12); pts.push([p.x + Math.cos(an) * rr, p.y + Math.sin(an) * rr]); } x.globalAlpha = Math.min(1, a * 1.8); mPoly(x, pts, p.c); x.fillStyle = shade(p.c, 0.35); x.fillRect(Math.round(pts[0][0]), Math.round(pts[0][1]), 1, 1); },
  mrock(x, p, a) { const r = p.r || 6, rot = (p.rot || 0) + p.t * (p.vr ?? 0.1), pts = []; for (let i = 0; i < 8; i++) { const an = rot + i * 0.785, rr = r * (0.8 + ((i * 7) % 5) / 12); pts.push([p.x + Math.cos(an) * rr, p.y + Math.sin(an) * rr * 0.9]); } x.globalAlpha = Math.min(1, a * 2); mPoly(x, pts, p.c || MC.rock); mCirc(x, p.x - r * 0.3, p.y - r * 0.3, r * 0.3, shade(p.c || MC.rock, 0.3), false); mCirc(x, p.x + r * 0.25, p.y + r * 0.2, r * 0.22, shade(p.c || MC.rock, -0.35), false); },
  mpuff(x, p, a) { const k = p.t / p.life, r = (p.r || 5) * (0.6 + 0.7 * k); x.globalAlpha = a * (p.op || 0.85); for (const [dx, dy, s] of [[-0.6, 0.2, 0.75], [0.6, 0.25, 0.7], [0, -0.3, 1]]) mCirc(x, p.x + dx * r, p.y + dy * r, r * s, shade(p.c, -0.35), false); for (const [dx, dy, s] of [[-0.6, 0.1, 0.55], [0.6, 0.15, 0.5], [0, -0.4, 0.8]]) mCirc(x, p.x + dx * r, p.y + dy * r, r * s, p.c, false); },
  mjag(x, p, a) { const r = lerp(p.r0, p.r1, p.t / p.life), n = p.n || 14; x.globalAlpha = a; x.beginPath(); for (let i = 0; i <= n; i++) { const an = i / n * Math.PI * 2 + (p.rot || 0), rr = r * (i % 2 ? 0.72 : 1); x.lineTo(p.x + Math.cos(an) * rr, p.y + Math.sin(an) * rr * (p.fl || 1)); } x.lineWidth = 4; x.strokeStyle = MOL; x.stroke(); x.lineWidth = 2; x.strokeStyle = p.c; x.stroke(); },
  mzap(x, p, a) { const pts = [], n = 6, x1 = p.x1 ?? p.x - 10, y1 = p.y1 ?? p.y - 10, x2 = p.x2 ?? p.x + 10, y2 = p.y2 ?? p.y + 10; for (let i = 0; i <= n; i++) pts.push([lerp(x1, x2, i / n) + (i % n ? rnd(-5, 5) : 0), lerp(y1, y2, i / n) + (i % n ? rnd(-5, 5) : 0)]); x.globalAlpha = a; x.beginPath(); pts.forEach(([u, v], i) => i ? x.lineTo(u, v) : x.moveTo(u, v)); x.lineWidth = 4; x.strokeStyle = MOL; x.stroke(); x.lineWidth = 2; x.strokeStyle = p.c || MC.volt; x.stroke(); x.lineWidth = 0.7; x.strokeStyle = p.c2 || MC.volt2; x.stroke(); },
  mflame(x, p, a) { const s = (p.s || 5) * (0.4 + 0.6 * a), X = p.x, Y = p.y; x.globalAlpha = Math.min(1, a * 1.5); x.beginPath(); x.moveTo(X, Y - s * 2.2); x.quadraticCurveTo(X + s * 1.2, Y - s * 0.4, X + s * 0.8, Y + s * 0.5); x.quadraticCurveTo(X, Y + s * 1.2, X - s * 0.8, Y + s * 0.5); x.quadraticCurveTo(X - s * 1.2, Y - s * 0.4, X, Y - s * 2.2); x.lineWidth = 2; x.strokeStyle = MOL; x.stroke(); x.fillStyle = p.c || MC.fire; x.fill(); mCirc(x, X, Y + s * 0.2, s * 0.45, p.c2 || MC.fire2, false); },
  mthorn(x, p, a) { const g = clamp(p.t / (p.grow || 6), 0, 1), X2 = lerp(p.x1, p.x2, g), Y2 = lerp(p.y1, p.y2, g), L = Math.hypot(X2 - p.x1, Y2 - p.y1) || 1, nx = -(Y2 - p.y1) / L, ny = (X2 - p.x1) / L; x.globalAlpha = Math.min(1, a * 1.8); x.lineCap = 'round'; x.beginPath(); x.moveTo(p.x1, p.y1); x.lineTo(X2, Y2); x.lineWidth = (p.w || 2) + 2; x.strokeStyle = MOL; x.stroke(); x.lineWidth = p.w || 2; x.strokeStyle = p.c; x.stroke(); for (let d = 5, s = 1; d < L; d += 5, s = -s) { const bx = lerp(p.x1, X2, d / L), by = lerp(p.y1, Y2, d / L); mPoly(x, [[bx, by], [bx + nx * 3.5 * s + (X2 - p.x1) / L * 2, by + ny * 3.5 * s + (Y2 - p.y1) / L * 2], [bx + (X2 - p.x1) / L * 2.5, by + (Y2 - p.y1) / L * 2.5]], p.c2 || p.c, false); } x.lineCap = 'butt'; },
  mfeather(x, p, a) { const rot = (p.rot || 0) + p.t * 0.2; x.globalAlpha = a; x.save(); x.translate(p.x, p.y); x.rotate(rot); x.beginPath(); x.ellipse(0, 0, 5, 1.8, 0, 0, 7); x.lineWidth = 2; x.strokeStyle = MOL; x.stroke(); x.fillStyle = p.c || MC.feather; x.fill(); x.fillStyle = shade(p.c || MC.feather, -0.4); x.fillRect(-5, 0, 10, 0.6); x.restore(); },
  mnote(x, p, a) { x.globalAlpha = a; const X = p.x, Y = p.y; mCirc(x, X, Y, 2.3, p.c); x.fillStyle = MOL; x.fillRect(X + 1.5, Y - 8, 2, 8); x.fillStyle = p.c; x.fillRect(X + 2, Y - 8, 1, 8); mPoly(x, [[X + 2, Y - 8], [X + 6, Y - 6], [X + 6, Y - 4], [X + 2, Y - 6]], p.c); },
  mweb(x, p, a) { const r = (p.r || 22) * clamp(p.t / 8, 0.2, 1); x.globalAlpha = a; x.lineWidth = 2.5; x.strokeStyle = MOL; const draw = () => { x.beginPath(); for (let i = 0; i < 8; i++) { const an = i * 0.785; x.moveTo(p.x, p.y); x.lineTo(p.x + Math.cos(an) * r, p.y + Math.sin(an) * r); } for (const k of [0.35, 0.65, 1]) for (let i = 0; i <= 8; i++) { const an = i * 0.785; const X = p.x + Math.cos(an) * r * k, Y = p.y + Math.sin(an) * r * k; i ? x.lineTo(X, Y) : x.moveTo(X, Y); } x.stroke(); }; draw(); x.lineWidth = 1; x.strokeStyle = p.c || MC.silk; draw(); },
  mskull(x, p, a) { x.globalAlpha = a; const X = p.x, Y = p.y, s = p.s || 1; mCirc(x, X, Y, 4 * s, p.c || MC.bone); mPoly(x, [[X - 2.5 * s, Y + 2 * s], [X + 2.5 * s, Y + 2 * s], [X + 2 * s, Y + 5 * s], [X - 2 * s, Y + 5 * s]], p.c || MC.bone); x.fillStyle = MOL; x.fillRect(Math.round(X - 2.5 * s), Math.round(Y - 1 * s), Math.ceil(1.6 * s), Math.ceil(2 * s)); x.fillRect(Math.round(X + 1 * s), Math.round(Y - 1 * s), Math.ceil(1.6 * s), Math.ceil(2 * s)); if (p.tail) { x.globalAlpha = a * 0.5; mPoly(x, [[X - 3 * s, Y + 3 * s], [X + 3 * s, Y + 3 * s], [X, Y + 12 * s]], p.c || MC.bone, false); } },
  mrune(x, p, a) { const rot = (p.rot || 0) + p.t * 0.08, s = p.s || 5; x.globalAlpha = a; x.save(); x.translate(p.x, p.y); x.rotate(rot); for (const [lw, c] of [[3.5, MOL], [1.5, p.c || '#60e8ff']]) { x.lineWidth = lw; x.strokeStyle = c; x.beginPath(); x.rect(-s, -s, s * 2, s * 2); x.moveTo(-s, 0); x.lineTo(0, -s * 0.5); x.lineTo(s, 0); x.moveTo(0, -s * 0.5); x.lineTo(0, s); x.stroke(); } x.restore(); },
  mbone(x, p, a) { const rot = (p.rot || 0) + p.t * (p.vr ?? 0.4), L = p.L || 7; x.globalAlpha = Math.min(1, a * 2); x.save(); x.translate(p.x, p.y); x.rotate(rot); x.lineWidth = 5; x.strokeStyle = MOL; x.beginPath(); x.moveTo(-L, 0); x.lineTo(L, 0); x.stroke(); x.lineWidth = 3; x.strokeStyle = p.c || MC.bone; x.stroke(); for (const e of [-L, L]) for (const o of [-1.6, 1.6]) mCirc(x, e, o, 2, p.c || MC.bone); x.restore(); },
  mknife(x, p, a) { const rot = p.rot ?? Math.atan2((p.ty ?? p.y) - p.y + 0.01, (p.tx ?? p.x) - p.x + 0.01) + p.t * (p.vr || 0); x.globalAlpha = Math.min(1, a * 2); x.save(); x.translate(p.x, p.y); x.rotate(rot); mPoly(x, [[-2, -1.6], [7, 0], [-2, 1.6]], p.c || '#c8d0dc'); mPoly(x, [[-6, -1.2], [-2, -1.2], [-2, 1.2], [-6, 1.2]], '#5a3a20'); x.restore(); },
  mcoin(x, p, a) { x.globalAlpha = a; const rx = Math.max(0.6, Math.abs(Math.cos(p.t / 3)) * 3); x.beginPath(); x.ellipse(p.x, p.y, rx, 3, 0, 0, 7); x.lineWidth = 2; x.strokeStyle = MOL; x.stroke(); x.fillStyle = '#ffd040'; x.fill(); },
  maura(x, p, a) { const r = lerp(p.r0 || 10, p.r1 || 36, p.t / p.life), [cr, cg, cb] = hex2rgb(p.c || '#a01030'), g = x.createRadialGradient(p.x, p.y, r * 0.2, p.x, p.y, r); g.addColorStop(0, `rgba(${cr},${cg},${cb},0)`); g.addColorStop(0.7, `rgba(${cr},${cg},${cb},${0.55 * a})`); g.addColorStop(1, `rgba(${cr},${cg},${cb},0)`); x.fillStyle = g; x.fillRect(p.x - r, p.y - r, r * 2, r * 2); },
  mglint(x, p, a) { x.globalAlpha = a; const s = 2 + 4 * Math.sin(Math.PI * p.t / p.life); mPoly(x, [[p.x, p.y - s], [p.x + 1, p.y - 1], [p.x + s, p.y], [p.x + 1, p.y + 1], [p.x, p.y + s], [p.x - 1, p.y + 1], [p.x - s, p.y], [p.x - 1, p.y - 1]], p.c || '#ff3040'); },
  mcrack(x, p, a) { const g = clamp(p.t / 6, 0, 1); x.globalAlpha = a; if (!p.br) { p.br = []; for (let i = 0; i < (p.n || 5); i++) { const an = Math.PI + i / ((p.n || 5) - 1) * Math.PI + rnd(-2, 2) / 10, pts = [[p.x, p.y]]; let X = p.x, Y = p.y; for (let k = 0; k < 4; k++) { X += Math.cos(an) * 6 + rnd(-2, 2); Y += Math.sin(an) * 2.2 + rnd(-1, 1); pts.push([X, Y]); } p.br.push(pts); } p.br.push(p.br[0].map(([u, v]) => [2 * p.x - u, v])); } for (const pts of p.br) { const m = Math.max(1, Math.round(pts.length * g)); for (const [lw, c] of [[3, MOL], [1.4, p.c || '#3a2a1a']]) { x.lineWidth = lw; x.strokeStyle = c; x.beginPath(); pts.slice(0, m).forEach(([u, v], i) => i ? x.lineTo(u, v) : x.moveTo(u, v)); x.stroke(); } } },
  mhand(x, p, a) { x.globalAlpha = a * 0.9; const X = p.x, Y = p.y, c = p.c || MC.ghost; mPoly(x, [[X - 4, Y + 10], [X - 4, Y], [X + 4, Y], [X + 4, Y + 10]], c); mCirc(x, X, Y, 4.5, c); for (let i = 0; i < 4; i++) { const fx = X - 3.5 + i * 2.3; mPoly(x, [[fx - 0.8, Y - 2], [fx + 0.8, Y - 2], [fx + 0.4, Y - 8 - (i % 2) * 2], [fx - 0.4, Y - 8 - (i % 2) * 2]], c); } },
  mcurse(x, p, a) { const r = lerp(p.r0 || 26, p.r1 || 6, p.t / p.life), rot = p.t * 0.25; x.globalAlpha = a; for (let k = 0; k < 3; k++) { const a0 = rot + k * 2.094; for (const [lw, c] of [[4.5, MOL], [2.5, p.c || MC.dark], [0.8, p.c2 || MC.dark2]]) { x.lineWidth = lw; x.strokeStyle = c; x.beginPath(); x.arc(p.x, p.y, r, a0, a0 + 1.4); x.stroke(); } } },
  mleaf(x, p, a) { const rot = p.t * 0.5; x.globalAlpha = Math.min(1, a * 2); x.save(); x.translate(p.x, p.y); x.rotate(rot); mPoly(x, [[-6, 0], [0, -2.5], [6, 0], [0, 2.5]], p.c || MC.leaf2); x.fillStyle = MC.leaf; x.fillRect(-5, -0.3, 10, 0.6); x.restore(); },
  mbeam(x, p, a) { const g = clamp(p.t / (p.grow || 5), 0, 1), X2 = lerp(p.x1, p.x2, g), Y2 = lerp(p.y1, p.y2, g), L = Math.hypot(X2 - p.x1, Y2 - p.y1) || 1, nx = -(Y2 - p.y1) / L, ny = (X2 - p.x1) / L, w = (p.w || 3) * (p.pulse ? 0.7 + 0.3 * Math.sin(p.t) : 1), pts = []; for (let i = 0; i <= 10; i++) { const u = i / 10, wob = p.wob ? Math.sin(u * 12 + p.t) * p.wob : 0; pts.push([lerp(p.x1, X2, u) + nx * wob, lerp(p.y1, Y2, u) + ny * wob]); } x.globalAlpha = a; for (const [lw, c] of [[w + 3, MOL], [w, p.c], [Math.max(0.6, w / 3), p.c2 || shade(p.c, 0.5)]]) { x.lineWidth = lw; x.strokeStyle = c; x.lineCap = 'round'; x.beginPath(); pts.forEach(([u, v], i) => i ? x.lineTo(u, v) : x.moveTo(u, v)); x.stroke(); } x.lineCap = 'butt'; },
  manger(x, p, a) { x.globalAlpha = a; const s = 3 + Math.sin(p.t / 2); for (let i = 0; i < 4; i++) { const an = i * 1.5708 + 0.785; const cx = p.x + Math.cos(an) * s, cy = p.y + Math.sin(an) * s; for (const [lw, c] of [[3.5, MOL], [1.8, p.c || '#ff3040']]) { x.lineWidth = lw; x.strokeStyle = c; x.beginPath(); x.arc(cx, cy, 2.4, an + 2.2, an + 4.1); x.stroke(); } } },
  mflash(x, p, a) { const [cr, cg, cb] = hex2rgb(p.c || '#400010'), g = x.createRadialGradient(W / 2, BH / 2, 20, W / 2, BH / 2, 140); g.addColorStop(0, `rgba(${cr},${cg},${cb},${0.15 * a * (p.a || 1)})`); g.addColorStop(1, `rgba(${cr},${cg},${cb},${0.7 * a * (p.a || 1)})`); x.fillStyle = g; x.fillRect(0, 0, W, BH); },
};
/* ---- helpers for recipes (called with this = Battle) ---- */
function mSpawn(B, k, o) { return B.spawn({ k, ...o }); }
function mProj(B, U, T, mk, n = 1, spacing = 3, frames = 16) { B.projectile(U, T, n, mk, spacing, frames); }
function mDebris(B, X, Y, n, c, k = 'mshard', spd = 2.2, r = 2.5) { for (let i = 0; i < n; i++) { const an = -Math.PI / 2 + rnd(-12, 12) / 10, v = spd * (0.6 + Math.random()); mSpawn(B, k, { x: X, y: Y, vx: Math.cos(an) * v, vy: Math.sin(an) * v, g: 0.18, r, c, vr: 0.4, life: 22 + rnd(0, 8) }); } }
function mImpact(B, T, c, r1 = 22) { mSpawn(B, 'mjag', { x: T.x, y: T.y, r0: 4, r1, c, life: 12 }); }
function mRise(B, X, Y, n, mk, spread = 18) { for (let i = 0; i < n; i++) { const p = mk(i); mSpawn(B, p.k, { x: X + rnd(-spread, spread), y: Y + rnd(-6, 10), vy: -0.6 - Math.random() * 0.6, vx: rnd(-3, 3) / 10, life: 24 + rnd(0, 10), ...p }); } }
function mClaw(B, T, c, dir = 1, n = 3, len = 30, w = 5) { for (let i = 0; i < n; i++) mSpawn(B, 'mgouge', { x: T.x + (i - (n - 1) / 2) * 7, y: T.y, ang: dir > 0 ? 1.1 : 2.04, len, w, c, c2: shade(c, 0.45), bend: 3 * dir, grow: 4, life: 16 }); }
const MFX = {
  *tell(U, T, u) { mSpawn(this, 'maura', { x: U.x, y: U.y, r0: 12, r1: 38, c: '#a01030', life: 14 }); for (const d of [-6, 6]) mSpawn(this, 'mglint', { x: U.x + d, y: U.y - 8, c: '#ff3050', life: 10 }); yield* wait(8); },
  *mbuff(U) { mSpawn(this, 'maura', { x: U.x, y: U.y, r0: 40, r1: 10, c: '#c02030', life: 18 }); mSpawn(this, 'mjag', { x: U.x, y: U.y, r0: 34, r1: 8, c: '#ff5060', life: 16 }); Sound.sfx('statUp'); yield* wait(18); },
  *mcharge(U) { Sound.sfx('charge'); for (let i = 0; i < 3; i++) { mSpawn(this, 'mjag', { x: U.x, y: U.y, r0: 40, r1: 6, c: '#ff7a20', life: 14, rot: i }); mSpawn(this, 'maura', { x: U.x, y: U.y, r0: 44, r1: 10, c: '#ff5010', life: 14 }); yield* wait(6); } yield* wait(10); },
  *regrow(U) { Sound.sfx('heal'); for (let i = 0; i < 5; i++) mSpawn(this, 'mthorn', { x1: U.x + (i - 2) * 9, y1: U.y + 26, x2: U.x + (i - 2) * 7, y2: U.y - 4, c: MC.leaf, c2: MC.leaf2, grow: 10, life: 26 }); mRise(this, U.x, U.y + 10, 8, () => ({ k: 'mglob', r: 2, c: MC.leaf2 })); yield* wait(26); },
  *steal(U, T, u) { yield* this.lunge(u, 22, 2); Sound.sfx('item'); for (let i = 0; i < 6; i++) { const p = mSpawn(this, 'mcoin', { x: T.x + rnd(-8, 8), y: T.y + rnd(-6, 6), life: 22 }); const sx = p.x, sy = p.y; p.upd = q => { const t = clamp(q.t / 18, 0, 1); q.x = lerp(sx, U.x, t); q.y = lerp(sy, U.y, t) - Math.sin(t * Math.PI) * 20; }; } yield* wait(22); },
  *knives(U, T) { Sound.sfx('slash'); for (let i = 0; i < 3; i++) { mProj(this, { x: i % 2 ? W + 6 : -6, y: T.y - 24 + i * 10 }, T, () => ({ k: 'mknife', vr: 0.6 }), 1, 0, 10); yield* wait(4); } yield* wait(10); mImpact(this, T, '#c8d0dc', 12); yield* wait(6); },
  // ---- plant ----
  *m_capBonk(U, T, u) { yield* this.lunge(u, 16, 3); Sound.sfx('hit'); mImpact(this, T, '#c8a060'); mRise(this, T.x, T.y, 4, () => ({ k: 'mpuff', r: 3, c: '#d8c8a0' })); yield* wait(14); },
  *m_poisonSpore(U, T) { Sound.sfx('wind'); mProj(this, U, T, () => ({ k: 'mpuff', r: 4, c: MC.poison, arc: 14, wob: 4, linger: 10 }), 8, 2, 16); yield* wait(30); mRise(this, T.x, T.y, 8, () => ({ k: 'mglob', r: 1.5, c: MC.poison2 })); yield* wait(12); },
  *m_rootLeech(U, T) { Sound.sfx('leaf'); for (let i = 0; i < 4; i++) mSpawn(this, 'mthorn', { x1: T.x + (i - 1.5) * 10, y1: T.y + 30, x2: T.x + (i - 1.5) * 4, y2: T.y, c: '#6a4a24', c2: '#8a6a3a', grow: 8, life: 22 }); yield* wait(14); mProj(this, T, U, () => ({ k: 'mglob', r: 2.5, c: MC.leaf2, wob: 5 }), 5, 3, 16); yield* wait(26); },
  *m_sleepPollen(U, T) { Sound.sfx('wind'); for (let i = 0; i < 14; i++) mSpawn(this, 'mpuff', { x: T.x + rnd(-24, 24), y: T.y - 50 - rnd(0, 20), vy: 1.4 + Math.random(), vx: rnd(-3, 3) / 10, r: 2.5, c: '#e8a0d0', life: 40 }); yield* wait(36); },
  *m_toxicCloud(U, T) { Sound.sfx('poison'); for (let i = 0; i < 7; i++) { mSpawn(this, 'mpuff', { x: T.x + rnd(-20, 20), y: T.y + rnd(-14, 14), r: 8 + rnd(0, 5), c: i % 2 ? MC.poison : '#6a8a30', op: 0.7, life: 30 }); yield* wait(3); } mRise(this, T.x, T.y + 10, 6, () => ({ k: 'mbubble', r: 2, c: MC.poison2 })); yield* wait(20); },
  *m_thornVine(U, T) { Sound.sfx('leaf'); for (const o of [-8, 8]) mSpawn(this, 'mthorn', { x1: U.x + o, y1: U.y + 10, x2: T.x - o, y2: T.y, c: MC.leaf, c2: MC.leaf2, grow: 8, life: 18 }); yield* wait(10); mClaw(this, T, MC.leaf2, 1, 2, 26, 4); Sound.sfx('slash'); yield* wait(12); },
  *m_thornRain(U, T) { Sound.sfx('leaf'); for (let i = 0; i < 12; i++) { const X = T.x + rnd(-26, 26); mSpawn(this, 'mthorn', { x1: X, y1: -8, x2: X + rnd(-3, 3), y2: T.y + rnd(-10, 14), c: MC.leaf, c2: MC.leaf2, grow: 6, life: 12 }); if (i % 3 === 0) yield* wait(3); } mImpact(this, T, MC.leaf2, 26); this.shake = 8; yield* wait(14); },
  *m_mossArmor(U) { Sound.sfx('statUp'); for (let i = 0; i < 6; i++) { const an = i * 1.047; mSpawn(this, 'mshard', { x: U.x + Math.cos(an) * 30, y: U.y + Math.sin(an) * 24, vx: -Math.cos(an) * 1.6, vy: -Math.sin(an) * 1.3, r: 4, c: '#6a9a40', life: 18 }); } mSpawn(this, 'mjag', { x: U.x, y: U.y, r0: 36, r1: 10, c: '#8ac040', life: 18 }); yield* wait(20); },
  *m_rootCrush(U, T) { Sound.sfx('quake'); this.shake = 14; mSpawn(this, 'mcrack', { x: T.x, y: T.y + 28, c: '#3a2a1a', life: 30 }); for (let i = 0; i < 4; i++) mSpawn(this, 'mthorn', { x1: T.x + (i - 1.5) * 9, y1: T.y + 30, x2: T.x + (i - 1.5) * 12, y2: T.y - 22, w: 4, c: '#5a3a1a', c2: '#8a6a3a', grow: 5, life: 20 }); yield* wait(8); mDebris(this, T.x, T.y + 24, 6, MC.dirt); yield* wait(16); },
  // ---- bird ----
  *m_peck(U, T, u) { yield* this.lunge(u, 10, 2); for (let i = 0; i < 3; i++) { Sound.sfx('hit'); mSpawn(this, 'mgouge', { x: T.x + rnd(-8, 8), y: T.y + rnd(-8, 6), ang: 1.4 + rnd(-3, 3) / 10, len: 10, w: 3, c: '#e0c080', life: 8 }); mSpawn(this, 'mjag', { x: T.x + rnd(-6, 6), y: T.y + rnd(-6, 6), r0: 2, r1: 8, c: '#f0e0a0', n: 8, life: 8 }); yield* wait(4); } yield* wait(6); },
  *m_featherGust(U, T) { Sound.sfx('wind'); mProj(this, U, T, i => ({ k: 'mfeather', wob: 10, rot: i, c: MC.feather }), 10, 2, 18); yield* wait(30); mImpact(this, T, '#c8d0e0'); yield* wait(8); },
  *m_chirp(U) { Sound.sfx('buzz'); for (let i = 0; i < 3; i++) { mSpawn(this, 'mjag', { x: U.x, y: U.y - 6, r0: 6, r1: 30, c: '#f0d060', n: 12, life: 14, rot: i }); yield* wait(5); } yield* wait(10); },
  *m_dive(U, T, u) { Sound.sfx('wind'); yield* this.lunge(u, 34, 4); Sound.sfx('slash'); mSpawn(this, 'mgouge', { x: T.x, y: T.y, ang: 1.0, len: 46, w: 7, c: '#3a4a8a', c2: '#8aa0e0', grow: 3, life: 16 }); mDebris(this, T.x, T.y, 6, MC.feather, 'mfeather', 1.8); this.shake = 6; yield* wait(16); },
  *m_lullaby(U, T) { Sound.sfx('buzz'); mProj(this, U, T, () => ({ k: 'mnote', c: '#9a70d0', wob: 8, linger: 8 }), 5, 5, 26); yield* wait(46); },
  *m_screech(U) { Sound.sfx('buzz'); this.shake = 6; for (let i = 0; i < 4; i++) { mSpawn(this, 'mjag', { x: U.x, y: U.y, r0: 8, r1: 56, c: '#e04050', n: 18, life: 16, rot: i * 0.3 }); yield* wait(4); } yield* wait(12); },
  *m_sonic(U, T) { Sound.sfx('buzz'); mProj(this, U, T, () => ({ k: 'mjag', r0: 3, r1: 16, c: '#a0c0e0', n: 10 }), 6, 2, 14); yield* wait(26); mImpact(this, T, '#d0e0ff', 18); yield* wait(8); },
  // ---- construct ----
  *m_roll(U, T, u) { yield* this.lunge(u, 22, 4); Sound.sfx('hit'); mImpact(this, T, '#a88a6a'); mRise(this, T.x, T.y + 18, 5, () => ({ k: 'mpuff', r: 3, c: '#9a8a7a' })); yield* wait(14); },
  *m_harden(U) { Sound.sfx('statUp'); for (let i = 0; i < 4; i++) { const an = i * 1.57 + 0.78; mSpawn(this, 'mshard', { x: U.x + Math.cos(an) * 28, y: U.y + Math.sin(an) * 24, vx: -Math.cos(an) * 1.5, vy: -Math.sin(an) * 1.3, r: 5, c: '#8a8a94', vr: 0, life: 18 }); } mSpawn(this, 'mjag', { x: U.x, y: U.y, r0: 30, r1: 12, c: '#b0b0bc', n: 6, life: 18 }); yield* wait(20); },
  *m_pebbleToss(U, T) { Sound.sfx('rock'); mProj(this, U, T, () => ({ k: 'mrock', r: 4, arc: 22, c: MC.rock }), 1, 0, 16); yield* wait(16); mDebris(this, T.x, T.y, 5, MC.rock); mImpact(this, T, '#c0a080', 16); yield* wait(12); },
  *m_quake(U, T) { Sound.sfx('quake'); this.shake = 20; mSpawn(this, 'mcrack', { x: T.x, y: T.y + 28, life: 32 }); for (let i = 0; i < 3; i++) { mDebris(this, T.x + rnd(-20, 20), T.y + 26, 3, MC.rock); mRise(this, T.x, T.y + 24, 2, () => ({ k: 'mpuff', r: 4, c: '#8a7a6a' }), 24); yield* wait(6); } yield* wait(14); },
  *m_boulder(U, T) { Sound.sfx('rock'); mProj(this, U, T, () => ({ k: 'mrock', r: 10, arc: 34, c: '#7a6a58', vr: 0.15 }), 1, 0, 22); yield* wait(22); this.shake = 14; mImpact(this, T, '#c0a080', 30); mDebris(this, T.x, T.y, 8, MC.rock, 'mshard', 2.8, 3.5); yield* wait(16); },
  *m_stoneWall(U) { Sound.sfx('rock'); for (let i = 0; i < 3; i++) { mSpawn(this, 'mrock', { x: U.x + (i - 1) * 14, y: U.y + 40, vy: -2.2, g: 0.08, r: 7, vr: 0, c: '#8a7a64', life: 22 }); yield* wait(4); } mSpawn(this, 'mjag', { x: U.x, y: U.y, r0: 38, r1: 14, c: '#a8987c', n: 8, life: 18 }); yield* wait(18); },
  *m_rumble(U) { Sound.sfx('quake'); this.shake = 12; mSpawn(this, 'mcrack', { x: U.x, y: U.y + 30, n: 4, c: '#2a1a10', life: 30 }); for (let i = 0; i < 3; i++) { mSpawn(this, 'mjag', { x: U.x, y: U.y, r0: 10, r1: 70, c: '#6a5040', n: 10, life: 24, fl: 0.6 }); yield* wait(7); } yield* wait(12); },
  *m_rockfall(U, T) { Sound.sfx('quake'); for (let i = 0; i < 6; i++) { const X = T.x + rnd(-28, 28), p = mSpawn(this, 'mrock', { x: X, y: -12, r: 5 + rnd(0, 4), c: '#7a6a58', life: 18 }); const ty = T.y + rnd(-6, 16); p.upd = q => { q.y = lerp(-12, ty, clamp(q.t / 10, 0, 1)); }; yield* wait(3); } this.shake = 16; yield* wait(8); mRise(this, T.x, T.y + 12, 6, () => ({ k: 'mpuff', r: 5, c: '#8a7a6a' }), 26); yield* wait(14); },
  *m_golemFist(U, T, u) { mSpawn(this, 'maura', { x: U.x, y: U.y, r0: 10, r1: 50, c: '#ff5010', life: 16 }); yield* wait(8); yield* this.lunge(u, 28, 4); Sound.sfx('quake'); this.shake = 26; mSpawn(this, 'mflash', { c: '#601000', life: 14 }); mSpawn(this, 'mjag', { x: T.x, y: T.y, r0: 8, r1: 48, c: '#ff8030', n: 18, life: 16 }); mSpawn(this, 'mcrack', { x: T.x, y: T.y + 28, n: 7, life: 34 }); mDebris(this, T.x, T.y + 10, 10, '#a09884', 'mshard', 3.2, 3.5); yield* wait(22); },
  *m_crystalShard(U, T) { Sound.sfx('rock'); mProj(this, U, T, i => ({ k: 'mshard', r: 4, c: MC.crystal, vr: 0.5, seed: i + 1 }), 5, 2, 12); yield* wait(22); mImpact(this, T, MC.crystal, 20); yield* wait(8); },
  *m_crystalSpark(U, T) { Sound.sfx('thunder'); for (let i = 0; i < 3; i++) { mSpawn(this, 'mzap', { x1: U.x + rnd(-8, 8), y1: U.y, x2: T.x + rnd(-8, 8), y2: T.y, c: '#8a60ff', c2: MC.crystal, life: 8 }); yield* wait(4); } mImpact(this, T, '#a080ff', 18); yield* wait(10); },
  *m_prismRay(U, T) { Sound.sfx('charge'); mSpawn(this, 'maura', { x: U.x, y: U.y, r0: 30, r1: 6, c: '#c0a0ff', life: 14 }); yield* wait(12); Sound.sfx('hitSuper'); ['#ff6080', '#80ff90', '#80a0ff'].forEach((c, i) => mSpawn(this, 'mbeam', { x1: U.x + (i - 1) * 4, y1: U.y, x2: T.x + (i - 1) * 6, y2: T.y, w: 3, c, grow: 5, life: 20 })); yield* wait(14); mImpact(this, T, '#ffffff', 26); yield* wait(10); },
  // ---- ooze ----
  *m_bounce(U, T, u) { yield* this.lunge(u, 18, 4); Sound.sfx('water'); for (let i = 0; i < 6; i++) { const an = -Math.PI / 2 + (i - 2.5) * 0.5; mSpawn(this, 'mdrop', { x: T.x, y: T.y + 4, vx: Math.cos(an) * 2, vy: Math.sin(an) * 2, g: 0.2, r: 2, c: '#5aa0e0', life: 20 }); } yield* wait(16); },
  *m_bubbleSpit(U, T) { Sound.sfx('water'); mProj(this, U, T, () => ({ k: 'mbubble', r: 3.5, c: '#4a90b0', wob: 6 }), 6, 3, 20); yield* wait(34); for (let i = 0; i < 3; i++) mImpact(this, { x: T.x + rnd(-8, 8), y: T.y + rnd(-8, 8) }, '#8ad0e8', 8); yield* wait(10); },
  *m_goo(U, T) { Sound.sfx('water'); mProj(this, U, T, () => ({ k: 'mglob', r: 3.5, c: '#7a9a60', arc: 18 }), 3, 4, 16); yield* wait(26); for (let i = 0; i < 6; i++) mSpawn(this, 'mdrop', { x: T.x + rnd(-12, 12), y: T.y + rnd(-6, 6), vy: 0.8, r: 1.8, c: '#7a9a60', life: 22 }); yield* wait(16); },
  *m_waterBomb(U, T) { Sound.sfx('water'); mProj(this, U, T, () => ({ k: 'mglob', r: 7, c: '#3a8ac0', arc: 26 }), 1, 0, 18); yield* wait(18); mImpact(this, T, MC.water2, 26); for (let i = 0; i < 10; i++) { const an = i / 10 * Math.PI * 2; mSpawn(this, 'mdrop', { x: T.x, y: T.y, vx: Math.cos(an) * 2.2, vy: Math.sin(an) * 2.2 - 1, g: 0.15, r: 2, c: '#3a8ac0', life: 22 }); } yield* wait(16); },
  *m_engulf(U, T, u) { yield* this.lunge(u, 20, 4); Sound.sfx('water'); const p = mSpawn(this, 'mbubble', { x: T.x, y: T.y, r: 6, c: '#5aa0e0', life: 26 }); p.upd = q => { q.r = 6 + Math.sin(Math.PI * q.t / q.life) * 18; }; yield* wait(20); mProj(this, T, U, () => ({ k: 'mglob', r: 2, c: '#8ad0f0', wob: 4 }), 4, 3, 14); yield* wait(22); },
  *m_oreShell(U) { Sound.sfx('statUp'); for (let i = 0; i < 6; i++) { const an = i * 1.047; mSpawn(this, 'mshard', { x: U.x + Math.cos(an) * 30, y: U.y + Math.sin(an) * 26, vx: -Math.cos(an) * 1.6, vy: -Math.sin(an) * 1.4, r: 3.5, c: i % 2 ? '#d8b040' : '#8a8a94', life: 18 }); } mSpawn(this, 'mjag', { x: U.x, y: U.y, r0: 32, r1: 10, c: '#d8b040', n: 10, life: 18 }); yield* wait(20); },
  *m_acidSpit(U, T) { Sound.sfx('poison'); mProj(this, U, T, () => ({ k: 'mglob', r: 3, c: '#b0d030', arc: 16 }), 4, 3, 16); yield* wait(26); mRise(this, T.x, T.y, 5, () => ({ k: 'mpuff', r: 4, c: '#8aa030', op: 0.6 })); for (let i = 0; i < 4; i++) mSpawn(this, 'mdrop', { x: T.x + rnd(-10, 10), y: T.y, vy: 0.9, r: 1.8, c: '#b0d030', life: 18 }); yield* wait(14); },
  // ---- beast ----
  *m_claw(U, T, u) { yield* this.lunge(u, 12, 3); Sound.sfx('slash'); mClaw(this, T, MC.red); yield* wait(16); },
  *m_foxfire(U, T) { Sound.sfx('fire'); mProj(this, U, T, () => ({ k: 'mflame', s: 5, c: '#ff5a20', c2: '#ffd070', wob: 7 }), 3, 5, 22); yield* wait(34); for (let i = 0; i < 6; i++) mSpawn(this, 'mflame', { x: T.x + rnd(-12, 12), y: T.y + rnd(-4, 10), vy: -0.8, s: 3, c: '#ff5a20', c2: '#ffd070', life: 16 }); yield* wait(12); },
  *m_pounce(U, T, u) { yield* this.lunge(u, 28, 3); Sound.sfx('slash'); for (const d of [1, -1]) mSpawn(this, 'mgouge', { x: T.x, y: T.y, ang: d > 0 ? 0.8 : 2.34, len: 24, w: 4, c: MC.red, c2: '#ff8090', life: 12 }); mImpact(this, T, '#ff8090', 14); yield* wait(12); },
  *m_blazeTail(U, T, u) { yield* this.lunge(u, 16, 3); Sound.sfx('fire'); for (let i = 0; i < 10; i++) { const an = Math.PI * (0.15 + i / 12); mSpawn(this, 'mflame', { x: T.x + Math.cos(an) * 24, y: T.y - 6 + Math.sin(an) * 12, vy: -0.5, s: 4, c: MC.fire, life: 18 }); } mSpawn(this, 'mgouge', { x: T.x, y: T.y + 4, ang: 0.1, len: 44, w: 6, c: '#ff7a20', c2: MC.fire2, bend: 8, life: 14 }); yield* wait(18); },
  *m_leafDart(U, T) { Sound.sfx('leaf'); mProj(this, U, T, () => ({ k: 'mleaf' }), 4, 3, 12); yield* wait(24); mClaw(this, T, MC.leaf2, -1, 2, 20, 3); yield* wait(10); },
  *m_bite(U, T, u) { yield* this.lunge(u, 14, 3); Sound.sfx('hit'); mSpawn(this, 'mfang', { x: T.x, y: T.y, w: 30, life: 18 }); yield* wait(10); mImpact(this, T, MC.red, 16); yield* wait(10); },
  *m_howl(U) { Sound.cry(3, 0.6, 1.2); for (let i = 0; i < 4; i++) { mSpawn(this, 'mjag', { x: U.x, y: U.y - 8, r0: 8, r1: 46, c: '#a02030', n: 16, life: 20, fl: 0.7 }); yield* wait(6); } mSpawn(this, 'maura', { x: U.x, y: U.y, r0: 20, r1: 40, c: '#c02030', life: 20 }); yield* wait(14); },
  *m_rend(U, T, u) { yield* this.lunge(u, 16, 3); Sound.sfx('slash'); mClaw(this, T, MC.red, 1, 3, 34, 6); yield* wait(8); Sound.sfx('slash'); mClaw(this, T, MC.blood, -1, 3, 34, 6); this.shake = 10; yield* wait(16); },
  // ---- insect ----
  *m_sting(U, T) { Sound.sfx('slash'); mProj(this, U, T, () => ({ k: 'mknife', c: '#e8d040' }), 1, 0, 10); yield* wait(10); mRise(this, T.x, T.y, 3, () => ({ k: 'mpuff', r: 3, c: MC.poison })); mImpact(this, T, MC.poison, 12); yield* wait(14); },
  *m_buzzShock(U, T, u) { Sound.sfx('buzz'); yield* this.shakeB(u, 10, 2); Sound.sfx('thunder'); for (let i = 0; i < 4; i++) { mSpawn(this, 'mzap', { x1: U.x + rnd(-10, 10), y1: U.y + rnd(-6, 6), x2: T.x + rnd(-10, 10), y2: T.y + rnd(-6, 6), life: 8 }); yield* wait(3); } mImpact(this, T, MC.volt, 18); yield* wait(8); },
  *m_static(U, T) { Sound.sfx('buzz'); for (let i = 0; i < 8; i++) { mSpawn(this, 'mzap', { x: T.x + rnd(-16, 16), y: T.y + rnd(-16, 16), life: 6 }); yield* wait(3); } mSpawn(this, 'mjag', { x: T.x, y: T.y, r0: 26, r1: 10, c: MC.volt2, n: 12, life: 12 }); yield* wait(10); },
  *m_swarm(U) { Sound.sfx('buzz'); for (let i = 0; i < 10; i++) mSpawn(this, 'mpuff', { x: U.x + rnd(-24, 24), y: U.y + rnd(-18, 10), r: 3, c: '#d0e8c0', op: 0.45, life: 16 }); mSpawn(this, 'mjag', { x: U.x, y: U.y, r0: 34, r1: 10, c: '#d0e8a0', n: 10, life: 14 }); yield* wait(18); },
  *m_hornCharge(U, T, u) { Sound.sfx('charge'); yield* this.lunge(u, 26, 4); Sound.sfx('hitSuper'); mSpawn(this, 'mgouge', { x: T.x, y: T.y - 4, ang: -1.57, len: 36, w: 7, c: '#c8a040', c2: '#fff0a0', bend: 2, life: 14 }); mImpact(this, T, '#f0d060', 22); this.shake = 8; yield* wait(14); },
  *m_carapace(U) { Sound.sfx('statUp'); for (let i = 0; i < 4; i++) { const an = i * 1.57; mSpawn(this, 'mshard', { x: U.x + Math.cos(an) * 28, y: U.y + Math.sin(an) * 24, vx: -Math.cos(an) * 1.5, vy: -Math.sin(an) * 1.3, r: 6, c: '#3a4aa8', vr: 0, life: 18 }); } mSpawn(this, 'mjag', { x: U.x, y: U.y, r0: 30, r1: 12, c: '#7a90f0', n: 8, life: 18 }); yield* wait(20); },
  *m_voltHorn(U, T, u) { for (let i = 0; i < 3; i++) mSpawn(this, 'mzap', { x: U.x + rnd(-6, 6), y: U.y - 14, life: 6 }); Sound.sfx('buzz'); yield* wait(8); yield* this.lunge(u, 24, 3); Sound.sfx('thunder'); mSpawn(this, 'mgouge', { x: T.x, y: T.y, ang: -1.4, len: 32, w: 6, c: MC.volt, c2: MC.volt2, life: 12 }); mSpawn(this, 'mzap', { x1: T.x, y1: T.y - 20, x2: T.x, y2: T.y + 20, life: 10 }); yield* wait(14); },
  *m_venomFang(U, T, u) { yield* this.lunge(u, 14, 3); Sound.sfx('poison'); mSpawn(this, 'mfang', { x: T.x, y: T.y, w: 22, c: '#d8b0f0', gum: '#3a1040', life: 18 }); yield* wait(10); mRise(this, T.x, T.y, 4, () => ({ k: 'mpuff', r: 3, c: MC.poison })); yield* wait(12); },
  *m_web(U, T) { Sound.sfx('wind'); mProj(this, U, T, () => ({ k: 'mglob', r: 3, c: MC.silk, arc: 10 }), 1, 0, 12); yield* wait(12); mSpawn(this, 'mweb', { x: T.x, y: T.y, r: 26, life: 30 }); yield* wait(24); },
  *m_silkShot(U, T) { Sound.sfx('wind'); mSpawn(this, 'mbeam', { x1: U.x, y1: U.y + 6, x2: T.x, y2: T.y, w: 1.5, c: MC.silk, wob: 2, grow: 6, life: 22 }); yield* wait(10); mSpawn(this, 'mweb', { x: T.x, y: T.y, r: 14, life: 18 }); yield* wait(14); },
  // ---- aquatic ----
  *m_tongue(U, T) { Sound.sfx('water'); const p = mSpawn(this, 'mbeam', { x1: U.x, y1: U.y + 6, x2: T.x, y2: T.y, w: 4, c: '#e87aa0', c2: '#ffc0d8', grow: 6, life: 16 }); yield* wait(8); mImpact(this, T, '#ffb0c8', 12); yield* wait(10); },
  *m_mudShot(U, T) { Sound.sfx('water'); mProj(this, U, T, () => ({ k: 'mglob', r: 3.5, c: MC.dirt, arc: 14 }), 3, 3, 14); yield* wait(22); for (let i = 0; i < 8; i++) { const an = -Math.PI / 2 + rnd(-14, 14) / 10; mSpawn(this, 'mdrop', { x: T.x, y: T.y, vx: Math.cos(an) * 2, vy: Math.sin(an) * 2, g: 0.2, r: 2, c: MC.dirt, life: 18 }); } yield* wait(12); },
  *m_jaw(U, T, u) { yield* this.lunge(u, 18, 4); Sound.sfx('hitSuper'); mSpawn(this, 'mfang', { x: T.x, y: T.y, w: 46, c: '#f0e8c8', gum: '#6a2020', life: 20 }); this.shake = 14; yield* wait(12); mImpact(this, T, MC.red, 24); yield* wait(10); },
  *m_tailSlam(U, T, u) { yield* this.lunge(u, 18, 3); Sound.sfx('water'); mSpawn(this, 'mgouge', { x: T.x, y: T.y + 2, ang: 0.05, len: 50, w: 8, c: '#2f7f9a', c2: MC.water2, bend: 10, life: 14 }); for (let i = 0; i < 8; i++) mSpawn(this, 'mdrop', { x: T.x + rnd(-20, 20), y: T.y, vx: rnd(-15, 15) / 10, vy: -1.5 - Math.random(), g: 0.18, r: 2, c: MC.water2, life: 20 }); yield* wait(16); },
  *m_scaleGuard(U) { Sound.sfx('statUp'); for (let i = 0; i < 8; i++) { const an = i * 0.785; mSpawn(this, 'mshard', { x: U.x + Math.cos(an) * 26, y: U.y + Math.sin(an) * 22, vx: -Math.cos(an), vy: -Math.sin(an), r: 3, c: '#3a8aa0', vr: 0.1, life: 16 }); } mSpawn(this, 'mjag', { x: U.x, y: U.y, r0: 28, r1: 10, c: '#6ac0d0', n: 12, life: 16 }); yield* wait(18); },
  // ---- human ----
  *m_knife(U, T, u) { yield* this.lunge(u, 14, 3); Sound.sfx('slash'); mSpawn(this, 'mgouge', { x: T.x, y: T.y, ang: 2.3, len: 30, w: 4, c: '#b8c0cc', c2: '#ff6070', life: 12 }); mImpact(this, T, '#d0d8e0', 12); yield* wait(12); },
  *m_dirtyKick(U, T, u) { yield* this.lunge(u, 24, 3); Sound.sfx('hit'); mImpact(this, T, '#a07a50', 16); mRise(this, T.x, T.y + 20, 4, () => ({ k: 'mpuff', r: 3, c: '#9a8a70' })); yield* wait(12); },
  *m_taunt(U, T) { Sound.sfx('buzz'); for (let i = 0; i < 3; i++) { mSpawn(this, 'manger', { x: T.x + rnd(-14, 14), y: T.y - 16 + rnd(-6, 6), life: 22 }); yield* wait(5); } yield* wait(14); },
  *m_throwDagger(U, T) { Sound.sfx('slash'); mProj(this, U, T, () => ({ k: 'mknife', vr: 0.7, rot: 0 }), 2, 4, 10); yield* wait(16); mSpawn(this, 'mgouge', { x: T.x, y: T.y, ang: 0.6, len: 18, w: 3, c: '#c8d0dc', life: 10 }); yield* wait(8); },
  *m_gutSlash(U, T, u) { yield* this.lunge(u, 20, 3); Sound.sfx('slash'); mSpawn(this, 'mgouge', { x: T.x, y: T.y, ang: 0.9, len: 52, w: 9, c: '#5a0a14', c2: '#ff4050', bend: 6, grow: 3, life: 18 }); mDebris(this, T.x, T.y, 6, '#9aa0ac'); this.shake = 12; yield* wait(18); },
  *m_warCry(U) { Sound.cry(9, 0.5, 1.2); for (let i = 0; i < 3; i++) { mSpawn(this, 'mjag', { x: U.x, y: U.y, r0: 10, r1: 44, c: '#e03020', n: 14, life: 18 }); mSpawn(this, 'manger', { x: U.x + rnd(-16, 16), y: U.y - 26 + rnd(-4, 4), life: 22 }); yield* wait(6); } yield* wait(10); },
  *m_axeSpin(U, T, u) { Sound.sfx('wind'); for (let i = 0; i < 6; i++) { mSpawn(this, 'mgouge', { x: U.x + Math.cos(i * 1.05) * 12, y: U.y + Math.sin(i * 1.05) * 8, ang: i * 1.05 + 1.57, len: 26, w: 5, c: '#9aa0ac', bend: 6, life: 10 }); yield* wait(3); } yield* this.lunge(u, 20, 3); Sound.sfx('hitSuper'); this.shake = 16; for (const d of [0.7, 2.44]) mSpawn(this, 'mgouge', { x: T.x, y: T.y, ang: d, len: 56, w: 9, c: '#6a0a10', c2: '#ff5030', life: 16 }); mSpawn(this, 'mflash', { c: '#500008', life: 10 }); yield* wait(16); },
  // ---- spirit ----
  *m_emberSpit(U, T) { Sound.sfx('fire'); mProj(this, U, T, () => ({ k: 'mflame', s: 4, c: '#ff4010', c2: '#ffc040', arc: 16 }), 3, 3, 14); yield* wait(22); mRise(this, T.x, T.y, 4, () => ({ k: 'mpuff', r: 3, c: '#3a2a2a', op: 0.7 })); yield* wait(12); },
  *m_flare(U, T) { Sound.sfx('fire'); mSpawn(this, 'mflash', { c: '#802000', life: 20, a: 0.8 }); for (let i = 0; i < 16; i++) { const an = i / 16 * Math.PI * 2; mSpawn(this, 'mflame', { x: U.x, y: U.y, vx: Math.cos(an) * 2.2 + (T.x - U.x) / 30, vy: Math.sin(an) * 1.6 + (T.y - U.y) / 24, s: 5, c: MC.fire, life: 24 }); } yield* wait(20); mImpact(this, T, '#ff7a20', 26); yield* wait(12); },
  *m_heatHaze(U, T) { Sound.sfx('fire'); for (let i = 0; i < 5; i++) { mSpawn(this, 'mjag', { x: T.x, y: T.y + 10 - i * 6, r0: 30, r1: 34, c: '#ff9a40', n: 20, life: 20, fl: 0.25 }); mSpawn(this, 'mpuff', { x: T.x + rnd(-16, 16), y: T.y + rnd(-10, 10), r: 6, c: '#ffb070', op: 0.35, life: 24 }); yield* wait(4); } yield* wait(16); },
  *m_flicker(U) { Sound.sfx('fire'); for (let i = 0; i < 8; i++) { const an = i * 0.785; mSpawn(this, 'mflame', { x: U.x + Math.cos(an) * 20, y: U.y + Math.sin(an) * 16, vx: -Math.cos(an) * 0.8, vy: -Math.sin(an) * 0.6, s: 3, c: '#ff6a20', life: 18 }); } mSpawn(this, 'maura', { x: U.x, y: U.y, r0: 34, r1: 12, c: '#ff5010', life: 18 }); yield* wait(18); },
  // ---- undead ----
  *m_boneClub(U, T, u) { yield* this.lunge(u, 16, 3); Sound.sfx('hit'); mSpawn(this, 'mbone', { x: T.x, y: T.y - 4, rot: -0.8, vr: 0.25, L: 9, life: 10 }); mImpact(this, T, MC.bone, 18); yield* wait(14); },
  *m_rattle(U, T, u) { Sound.sfx('rock'); yield* this.shakeB(u, 12, 2); for (let i = 0; i < 6; i++) mSpawn(this, 'mbone', { x: U.x + rnd(-18, 18), y: U.y + rnd(-18, 14), vy: rnd(-5, 5) / 10, L: 3, vr: 0.6, life: 14 }); mSpawn(this, 'mjag', { x: T.x, y: T.y, r0: 6, r1: 26, c: '#b0a890', n: 10, life: 14 }); yield* wait(14); },
  *m_boneThrow(U, T) { Sound.sfx('wind'); mProj(this, U, T, () => ({ k: 'mbone', vr: 0.5, arc: 18 }), 1, 0, 14); yield* wait(14); mImpact(this, T, MC.bone, 16); mProj(this, T, U, () => ({ k: 'mbone', vr: 0.5, arc: -18 }), 1, 0, 14); yield* wait(16); },
  *m_ghostFire(U, T) { Sound.sfx('fire'); mProj(this, U, T, () => ({ k: 'mflame', s: 5, c: '#3aa0c0', c2: '#e0ffff', wob: 9 }), 3, 5, 24); yield* wait(36); mRise(this, T.x, T.y, 3, () => ({ k: 'mskull', c: '#a0f0f0', tail: 1 })); yield* wait(16); },
  *m_soulSip(U, T) { Sound.sfx('charge'); mSpawn(this, 'mcurse', { x: T.x, y: T.y, r0: 24, r1: 6, life: 22 }); yield* wait(14); mProj(this, T, U, () => ({ k: 'mskull', s: 0.7, c: '#d0c0ff', tail: 1, wob: 6 }), 5, 3, 18); yield* wait(28); },
  *m_wail(U) { Sound.cry(13, 0.5, 1.4); for (let i = 0; i < 3; i++) { mSpawn(this, 'mjag', { x: U.x, y: U.y, r0: 8, r1: 60, c: '#8a78b0', n: 20, life: 22 }); yield* wait(6); } mRise(this, U.x, U.y, 4, () => ({ k: 'mskull', c: '#c8c0e0', tail: 1 }), 30); yield* wait(16); },
  *m_hex(U, T) { Sound.sfx('statDown'); mSpawn(this, 'mcurse', { x: T.x, y: T.y, r0: 30, r1: 8, life: 26 }); for (let i = 0; i < 3; i++) { const an = i * 2.09, p = mSpawn(this, 'mrune', { x: T.x, y: T.y, s: 3.5, c: '#c080ff', life: 26 }); p.upd = q => { const aa = an + q.t * 0.2, r = 22 - q.t * 0.5; q.x = T.x + Math.cos(aa) * r; q.y = T.y + Math.sin(aa) * r * 0.8; }; } yield* wait(26); },
  *m_drownHand(U, T) { Sound.sfx('water'); for (let i = 0; i < 4; i++) { const X = T.x + (i - 1.5) * 12, p = mSpawn(this, 'mhand', { x: X, y: T.y + 34, c: i % 2 ? MC.ghost : '#3a9ab0', life: 26 }); p.upd = q => { q.y = T.y + 34 - Math.sin(Math.PI * clamp(q.t / 20, 0, 1)) * 30; }; yield* wait(4); } for (let i = 0; i < 6; i++) mSpawn(this, 'mdrop', { x: T.x + rnd(-20, 20), y: T.y + 20, vy: -1.2, g: 0.08, r: 2, c: MC.water2, life: 20 }); yield* wait(22); },
  *m_chillMist(U, T) { Sound.sfx('wind'); mProj(this, U, T, () => ({ k: 'mpuff', r: 5, c: '#a8d8e0', op: 0.55, wob: 8, linger: 8 }), 8, 2, 18); yield* wait(30); mDebris(this, T.x, T.y, 4, '#e0f8ff', 'mshard', 1.5, 2); yield* wait(10); },
  *m_darkPulse(U, T) { Sound.sfx('charge'); mSpawn(this, 'mflash', { c: '#200030', life: 26, a: 0.9 }); for (let i = 0; i < 3; i++) { mSpawn(this, 'mjag', { x: U.x, y: U.y, r0: 8, r1: 110, c: '#6a3aa0', n: 22, life: 22 }); yield* wait(6); } mImpact(this, T, MC.dark2, 22); yield* wait(12); },
  *m_boneRush(U, T, u) { for (let k = 0; k < 2; k++) { yield* this.lunge(u, 14, 2); Sound.sfx('hit'); mSpawn(this, 'mfang', { x: T.x + (k ? 6 : -6), y: T.y + (k ? 4 : -4), w: 24, c: MC.bone, gum: '#2a1a2a', life: 12 }); yield* wait(6); } mDebris(this, T.x, T.y, 5, MC.bone, 'mbone', 2, 2); yield* wait(12); },
  *m_runeBeam(U, T) { for (let i = 0; i < 3; i++) { const an = i * 2.09, p = mSpawn(this, 'mrune', { x: U.x, y: U.y, s: 4, life: 16 }); p.upd = q => { const aa = an + q.t * 0.3; q.x = U.x + Math.cos(aa) * 18; q.y = U.y + Math.sin(aa) * 14; }; } Sound.sfx('charge'); yield* wait(14); Sound.sfx('thunder'); mSpawn(this, 'mbeam', { x1: U.x, y1: U.y, x2: T.x, y2: T.y, w: 5, c: '#40c8e8', c2: '#e0ffff', grow: 4, pulse: 1, life: 18 }); for (let i = 0; i < 3; i++) mSpawn(this, 'mzap', { x: T.x + rnd(-12, 12), y: T.y + rnd(-12, 12), life: 8 }); yield* wait(18); },
  *m_darkSlash(U, T, u) { mSpawn(this, 'maura', { x: U.x, y: U.y, r0: 10, r1: 40, c: '#40105a', life: 14 }); yield* wait(6); yield* this.lunge(u, 18, 3); Sound.sfx('slash'); mSpawn(this, 'mgouge', { x: T.x, y: T.y, ang: 2.2, len: 52, w: 9, c: MC.dark, c2: MC.dark2, bend: 7, life: 18 }); mSpawn(this, 'mcurse', { x: T.x, y: T.y, r0: 14, r1: 4, life: 16 }); this.shake = 10; yield* wait(18); },
  *m_boneShield(U, T, u) { yield* this.lunge(u, 20, 3); Sound.sfx('hitSuper'); mImpact(this, T, MC.bone, 28); mDebris(this, T.x, T.y, 6, MC.bone, 'mbone', 2.2, 2); this.shake = 10; yield* wait(16); },
  *m_deathCry(U) { Sound.cry(15, 0.45, 1.5); mSpawn(this, 'mjag', { x: U.x, y: U.y, r0: 10, r1: 50, c: '#8a50c0', n: 16, life: 22 }); mRise(this, U.x, U.y, 6, () => ({ k: 'mskull', c: '#e0d0ff', tail: 1 }), 24); yield* wait(22); },
};
