/* ===================== FX pack 3: class-line skills (hero materials: clean light lines, crescents, beams, hex) ===================== */
Object.assign(FX, {
  *voltSlash(U, T, u) { const pts = []; for (let y = U.y - 18; y < U.y + 4; y += 5) pts.push([U.x + rnd(-3, 3), y]); this.spawn({ k: 'bolt', pts, w: 2, life: 10 }); Sound.sfx('thunder'); yield* wait(6); yield* this.lunge(u, 14, 3); Sound.sfx('slash'); this.spawn({ k: 'cres', x: T.x, y: T.y, r: 18, ang: 0.4, c: '#fffbe0', c2: '#f8d030', w: 6, life: 12 }); for (let i = 0; i < 3; i++) { const p2 = []; let x0 = T.x + rnd(-14, 14); for (let y = T.y - 18; y < T.y + 18; y += 6) { p2.push([x0, y]); x0 += rnd(-5, 5); } this.spawn({ k: 'bolt', pts: p2, w: 2, life: 8 }); } yield* wait(14); },
  *tideSlash(U, T, u) { yield* this.lunge(u, 12, 3); Sound.sfx('water'); for (let i = 0; i < 3; i++) { this.spawn({ k: 'cres', x: T.x + (i - 1) * 8, y: T.y + (i - 1) * 3, r: 16, ang: -0.3 + i * 0.3, c: '#e8fbff', c2: '#3aa8f0', w: 5, life: 14 }); yield* wait(4); } for (let i = 0; i < 10; i++) this.spawn({ k: 'bub', x: T.x + rnd(-16, 16), y: T.y + rnd(-6, 12), vy: -0.6, r: rnd(1, 3), c: '#9ae0ff', life: 20 }); yield* wait(12); },
  *magicBolt(U, T) { Sound.sfx('charge'); this.spawn({ k: 'glow', x: U.x, y: U.y - 6, r: 14, c: '#c8e8ff', life: 10 }); yield* wait(6); this.projectile(U, T, 1, () => ({ k: 'circ', r: 3, c: '#e0f4ff', hl: '#ffffff' }), 0, 12); yield* wait(12); Sound.sfx('hit'); this.spawn({ k: 'ring', x: T.x, y: T.y, r0: 3, r1: 18, c: '#c8e8ff', w: 2, life: 10 }); this.star(T.x, T.y, '#ffffff', 10); yield* wait(10); },
  *fireBolt(U, T) { Sound.sfx('fire'); this.projectile(U, T, 1, () => ({ k: 'circ', r: 4, c: '#ff8030', hl: '#fff0a0', arc: 10 }), 0, 16); for (let i = 0; i < 8; i++) { const t = i / 8; this.spawn({ k: 'flame', x: lerp(U.x, T.x, t), y: lerp(U.y, T.y, t) - Math.sin(t * Math.PI) * 10, vy: -0.4, s: 3, life: 10 + i * 2 }); } yield* wait(16); Sound.sfx('hitSuper'); this.spawn({ k: 'ring', x: T.x, y: T.y, r0: 4, r1: 24, c: '#ffb050', w: 3, life: 12 }); for (let i = 0; i < 12; i++) this.spawn({ k: 'flame', x: T.x + rnd(-10, 10), y: T.y + rnd(-6, 8), vy: -1 - Math.random(), s: rnd(3, 6), life: 16 }); yield* wait(14); },
  *leafStorm(U, T) { Sound.sfx('leaf'); for (let i = 0; i < 18; i++) { const a0 = i / 18 * Math.PI * 2, p = this.spawn({ k: 'img', img: LEAF_IMG, x: T.x, y: T.y, life: 30 }); p.upd = q => { const a = a0 + q.t * 0.25, r = 28 - q.t * 0.6; q.x = T.x + Math.cos(a) * r; q.y = T.y + Math.sin(a) * r * 0.6; }; } for (let i = 0; i < 3; i++) this.spawn({ k: 'arc', x: T.x, y: T.y, r: 16 + i * 6, a0: i * 2, c: '#a8f0a0', life: 26 }); yield* wait(30); },
  *aquaBurst(U, T) { Sound.sfx('water'); for (let i = 0; i < 6; i++) this.spawn({ k: 'bub', x: T.x + rnd(-14, 14), y: T.y + 26, vy: -0.5, r: 2, c: '#9ae0ff', life: 14 }); yield* wait(10); Sound.sfx('hitSuper'); this.spawn({ k: 'beam', x: T.x, w: 16, y1: T.y + 28, h: 90, c: '#58c0f8', life: 22 }); this.spawn({ k: 'beam', x: T.x, w: 6, y1: T.y + 28, h: 90, c: '#e8fbff', life: 18 }); this.shake = 8; for (let i = 0; i < 16; i++) { const a = -Math.PI / 2 + rnd(-10, 10) / 10; this.spawn({ k: 'dot', x: T.x, y: T.y - 30, vx: Math.cos(a) * 2, vy: Math.sin(a) * 2, g: 0.15, c: pick(['#e8fbff', '#9ae0ff']), s: 2, life: 26 }); } yield* wait(22); },
  *flameWave(U, T) { Sound.sfx('fire'); for (let i = 0; i < 7; i++) { const x0 = T.x - 36 + i * 12; this.spawn({ k: 'beam', x: x0, w: 5, y1: T.y + 24, h: 26 + i * 3, c: '#ff9030', life: 16 }); for (let j = 0; j < 4; j++) this.spawn({ k: 'flame', x: x0 + rnd(-3, 3), y: T.y + 20 - rnd(0, 14), vy: -1.1, s: rnd(3, 6), life: 16 }); yield* wait(2); } this.spawn({ k: 'ring', x: T.x, y: T.y + 14, r0: 10, r1: 44, c: '#ffc060', w: 3, life: 16, fl: 0.35 }); yield* wait(18); },
  *ironWill(U) { Sound.sfx('statUp'); for (let i = 0; i < 2; i++) { this.spawn({ k: 'hex', x: U.x, y: U.y, r0: 12 + i * 6, r1: 30 + i * 6, c: ['#e0e8f8', '#a8c0e0'][i], life: 20 }); yield* wait(5); } this.spawn({ k: 'glow', x: U.x, y: U.y, r: 26, c: '#c8d8f0', life: 16 }); yield* wait(14); },
});
