/* ===================== v14.0 卡組職業：職業與卡牌 =====================
   四個職業（開場選，城鎮可轉職；每個職業各有一副牌組）＋共通卡＋頭目傳說卡。
   卡：[id, 職業, 名字, 種類 atk/skl/pow, 稀有度 B/C/U/R/L/T, 費用, 特效, 目標 enemy/all/self/rand, 數值, 升級後數值, 說明, 手牌短字, 效果, 選項]
   稀有度：B 基本（起始牌組）、C 普通、U 稀有、R 史詩、L 傳說（頭目）、T 衍生（飛刀） */
KD.CLASSES = {
  sw: { n: '劍士', hp: 80, wkind: '劍', c: '#e8b048', ab: '劍意', abd: '每打出 3 張攻擊卡，下一張攻擊卡傷害 ×2。', d: '格擋、反擊、易傷，最好上手。', start: [['sw_strike', 5], ['sw_defend', 4], ['sw_break', 1]] },
  rg: { n: '盜賊', hp: 70, wkind: '短刀', c: '#70d070', ab: '先手', abd: '每場戰鬥的第一回合多抽 2 張。', d: '毒、飛刀、0 費牌，一回合出很多張。', start: [['rg_stab', 5], ['rg_defend', 4], ['rg_venom', 1]] },
  mg: { n: '法師', hp: 65, wkind: '法杖', c: '#78a8ff', ab: '魔力湧動', abd: '每回合第一張技能卡打出後，抽 1 張。', d: '火燒、冰、雷，範圍魔法和蓄力大招。', start: [['mg_bolt', 5], ['mg_shield', 4], ['mg_fire', 1]] },
  bk: { n: '狂戰士', hp: 85, wkind: '斧', c: '#e06048', ab: '血怒', abd: 'HP 一半以下時，攻擊卡傷害 +3。', d: '扣自己的 HP 換傷害，力量越疊越痛。', start: [['bk_chop', 5], ['bk_defend', 4], ['bk_split', 1]] },
};
KD.CLS_ORDER = ['sw', 'rg', 'mg', 'bk'];
KD.RAR = { B: { n: '基本', c: '#9a9aaa' }, C: { n: '普通', c: '#d0d8e8' }, U: { n: '稀有', c: '#58b8ff' }, R: { n: '史詩', c: '#c878ff' }, L: { n: '傳說', c: '#ffb040' }, Q: { n: '任務', c: '#5ce0b8' }, T: { n: '衍生', c: '#9a9aaa' } };
KD.TYPE = { atk: { n: '攻擊', c: '#d05038', bg: '#3a1a1c' }, skl: { n: '技能', c: '#4a80d8', bg: '#16203a' }, pow: { n: '能力', c: '#d8a830', bg: '#33280c' } };
// v14.9: attack cards say whether they are 物理 or 魔法 (monsters' 物防／魔防 and the families' resistances go by it)
KD.typeN = c => { const C = KD.CARDS[c.id]; if (!C) return ''; const T = KD.TYPE[C.type]; if (C.type !== 'atk') return T.n; const D = DEF.skills['k14_' + c.id]; return T.n + (D && D.cat === '特' ? '（魔法）' : '（物理）'); };
KD.CARDS = {};
const KC = (id, cls, n, type, rar, cost, fx, tg, b, u, desc, short, run, o = {}) => { KD.CARDS[id] = { id, cls, n, type, rar, cost, fx, tg, b, u, desc, short, run, ...o }; };
/* ---------- helpers the cards use (cb = the battle screen, core = the battle core, tg = the chosen target(s), v = this card's numbers) ---------- */
const kFoes = core => core.alive('B');
const kRand = core => { const L = kFoes(core); return L.length ? (L.length > 1 ? core.rng.pick(L) : L[0]) : null; };
// attack: n hits on each target; a single target that falls hands the rest to another monster
function kAtk(cb, core, tg, d, n = 1, o = {}) { const H = cb.Hu(); let tot = 0; const single = tg.length === 1 && !o.all;
  for (let i = 0; i < n; i++) { let L = (o.all ? kFoes(core) : tg).filter(t => core.isUp(t)); if (!L.length && single) { const f = kFoes(core); L = f.length ? [f[0]] : []; } if (!L.length) break;
    for (const t of L) { const fb1 = cb.fb && cb.fbDone ? (cb.fbDone.has(t.id) ? 0 : (cb.fbDone.add(t.id), cb.fb)) : (i === 0 ? cb.fb || 0 : 0); // v14.10: 血怒・下一擊加成 once per target per card (random-hit cards used to add it on every hit)
      const flat = fb1 + (o.flatF ? o.flatF(t) : 0), mul = (o.mul || 1) * (o.mulF ? o.mulF(t) : 1) * (core.data.si2 ? 2 : 1);
      const got = KD.hit(core, H, t, d, { ...o, i, n, flat, mul, crit: core.data.si2 }); tot += got; cb.dealt = (cb.dealt || 0) + got;
      if (got > 0 && stkK(H, 'pwEnv14') && core.isUp(t)) KD.add(core, H, t, 'pois14', stkK(H, 'pwEnv14')); } }
  return tot; }
const kAll = (cb, core, d, n = 1, o = {}) => kAtk(cb, core, kFoes(core), d, n, { ...o, all: true });
const kRandHits = (cb, core, d, n, o = {}) => { let tot = 0; for (let i = 0; i < n; i++) { const t = kRand(core); if (!t) break; tot += kAtk(cb, core, [t], d, 1, { ...o, i }); } return tot; };
const kBlk = (cb, core, n) => KD.block(core, cb.Hu(), n);
const kDeb = (t, core) => ['pois14', 'weak15', 'vuln15', 'burn14', 'bleed15'].filter(k => stkK(t, k) > 0).length + (core.majorOf && core.majorOf(t) ? 1 : 0);
const kHalf = cb => { const H = cb.Hu(); return H.res.hp <= H.max.hp / 2; };
// skip the monster's next action (頭目 can't be stopped: 虛弱＋易傷 instead)
const kStop = (cb, core, t, n = 3) => { if (!t || !core.isUp(t)) return; if (t.boss) { KD.add(core, cb.Hu(), t, 'weak15', n); KD.add(core, cb.Hu(), t, 'vuln15', n); } else { core.removeStatus(t, 'charging', 'break'); core.applyStatus(cb.Hu(), t, 'flinch', {}); } };
/* ====================== 劍士 ====================== */
KC('sw_strike', 'sw', '斬擊', 'atk', 'B', 1, 'slash', 'enemy', { d: 6 }, { d: 9 }, v => '造成 ' + v.d + ' 傷害。', v => ['傷害 ' + v.d], (cb, core, tg, v) => kAtk(cb, core, tg, v.d));
KC('sw_defend', 'sw', '防禦', 'skl', 'B', 1, 'guard', 'self', { b: 5 }, { b: 8 }, v => '獲得 ' + v.b + ' 格擋。', v => ['格擋 ' + v.b], (cb, core, tg, v) => kBlk(cb, core, v.b));
KC('sw_break', 'sw', '斷甲斬', 'atk', 'B', 2, 't11_sdBreak', 'enemy', { d: 8, x: 2 }, { d: 10, x: 3 }, v => '造成 ' + v.d + ' 傷害，易傷 ' + v.x + '。', v => ['傷害 ' + v.d, '易傷 ' + v.x], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); for (const t of tg) KD.add(core, cb.Hu(), t, 'vuln15', v.x); });
KC('sw_twin', 'sw', '疾風二連', 'atk', 'C', 1, 't11_sdTwin', 'enemy', { d: 3 }, { d: 4 }, v => '造成 ' + v.d + ' 傷害 2 次。', v => [v.d + ' ×2'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 2));
KC('sw_gap', 'sw', '破綻突', 'atk', 'C', 1, 't11_sdGap', 'enemy', { d: 7 }, { d: 9 }, v => '造成 ' + v.d + ' 傷害；對易傷的敵人傷害加倍。', v => ['傷害 ' + v.d, '易傷加倍'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 1, { mulF: t => stkK(t, 'vuln15') ? 2 : 1 }));
KC('sw_whirl', 'sw', '旋刃', 'atk', 'C', 1, 't11_sdWhirl', 'all', { d: 5 }, { d: 7 }, v => '對全體造成 ' + v.d + ' 傷害。', v => ['全體 ' + v.d], (cb, core, tg, v) => kAll(cb, core, v.d));
KC('sw_bash', 'sw', '盾撞', 'atk', 'C', 1, 't11_osBash', 'enemy', { d: 5, b: 5 }, { d: 7, b: 7 }, v => '造成 ' + v.d + ' 傷害，獲得 ' + v.b + ' 格擋。', v => ['傷害 ' + v.d, '格擋 ' + v.b], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); kBlk(cb, core, v.b); });
KC('sw_hold', 'sw', '堅守', 'skl', 'C', 1, 't11_osHold', 'self', { b: 8 }, { b: 11 }, v => '獲得 ' + v.b + ' 格擋；下回合多抽 1 張。', v => ['格擋 ' + v.b, '下回合抽1'], (cb, core, tg, v) => { kBlk(cb, core, v.b); cb.nextDraw++; });
KC('sw_stance', 'sw', '架勢', 'skl', 'C', 1, 't11_dsParry', 'self', { b: 7 }, { b: 10 }, v => '獲得 ' + v.b + ' 格擋，劍意 +1。', v => ['格擋 ' + v.b, '劍意 +1'], (cb, core, tg, v) => { kBlk(cb, core, v.b); cb.addSi(1); });
KC('sw_qi', 'sw', '劍氣', 'atk', 'C', 0, 'quickDraw', 'enemy', { d: 3 }, { d: 5 }, v => '造成 ' + v.d + ' 傷害。', v => ['傷害 ' + v.d], (cb, core, tg, v) => kAtk(cb, core, tg, v.d));
KC('sw_breath', 'sw', '調息', 'skl', 'C', 0, 'focus', 'self', { c: 1 }, { c: 2 }, v => '抽 ' + v.c + ' 張，劍意 +1。', v => ['抽 ' + v.c, '劍意 +1'], (cb, core, tg, v) => { cb.drawN(v.c); cb.addSi(1); });
KC('sw_eye', 'sw', '心眼', 'skl', 'C', 0, 't11_sdEye', 'self', { x: 2 }, { x: 3 }, v => '劍意 +' + v.x + '。消耗。', v => ['劍意 +' + v.x, '消耗'], (cb, core, tg, v) => cb.addSi(v.x), { exhaust: 1 });
KC('sw_cleave', 'sw', '斬鐵', 'atk', 'C', 2, 'powerSlash', 'enemy', { d: 14 }, { d: 18 }, v => '造成 ' + v.d + ' 傷害。', v => ['傷害 ' + v.d], (cb, core, tg, v) => kAtk(cb, core, tg, v.d));
KC('sw_shield', 'sw', '舉盾', 'skl', 'C', 2, 'ironWall', 'self', { b: 12 }, { b: 16 }, v => '獲得 ' + v.b + ' 格擋。', v => ['格擋 ' + v.b], (cb, core, tg, v) => kBlk(cb, core, v.b));
KC('sw_tread', 'sw', '踏步斬', 'atk', 'C', 1, 'c9_sw9Tread', 'enemy', { d: 6 }, { d: 8 }, v => '造成 ' + v.d + ' 傷害，抽 1 張。', v => ['傷害 ' + v.d, '抽 1'], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); cb.drawN(1); });
KC('sw_flow', 'sw', '流光連斬', 'atk', 'U', 2, 't11_sdFlow', 'enemy', { d: 3, x: 2 }, { d: 4, x: 3 }, v => '造成 ' + v.d + ' 傷害 5 次；對易傷的敵人每次 +' + v.x + '。', v => [v.d + ' ×5', '易傷 +' + v.x], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 5, { flatF: t => stkK(t, 'vuln15') ? v.x : 0 }));
KC('sw_frenzy', 'sw', '狂刃', 'pow', 'U', 1, 't11_sdFrenzy', 'self', { x: 2 }, { x: 3 }, v => '能力：力量 +' + v.x + '。', v => ['力量 +' + v.x], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'str15', v.x));
KC('sw_counter', 'sw', '格擋反擊', 'pow', 'U', 1, 't11_osCounter', 'self', { x: 5 }, { x: 7 }, v => '能力：格擋完全擋下攻擊時，反擊 ' + v.x + ' 傷害。', v => ['擋下反擊', String(v.x)], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwCtr15', v.x));
KC('sw_wind', 'sw', '劍風', 'atk', 'U', 1, 'gale', 'all', { d: 4, x: 1 }, { d: 6, x: 2 }, v => '對全體造成 ' + v.d + ' 傷害，虛弱 ' + v.x + '。', v => ['全體 ' + v.d, '虛弱 ' + v.x], (cb, core, tg, v) => { kAll(cb, core, v.d); for (const t of kFoes(core)) KD.add(core, cb.Hu(), t, 'weak15', v.x); });
KC('sw_wall', 'sw', '鐵壁衝陣', 'atk', 'U', 2, 't11_ogShield', 'all', { d: 8, b: 8 }, { d: 11, b: 11 }, v => '對全體造成 ' + v.d + ' 傷害，獲得 ' + v.b + ' 格擋。', v => ['全體 ' + v.d, '格擋 ' + v.b], (cb, core, tg, v) => { kAll(cb, core, v.d); kBlk(cb, core, v.b); });
KC('sw_guard', 'sw', '迎擊架勢', 'pow', 'U', 1, 't11_shStance', 'self', { x: 3 }, { x: 5 }, v => '能力：每回合開始獲得 ' + v.x + ' 格擋。', v => ['每回合', '格擋 ' + v.x], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwGuard15', v.x));
KC('sw_star', 'sw', '雙星十字', 'atk', 'U', 1, 't11_dsStar', 'enemy', { d: 6 }, { d: 8 }, v => '造成 ' + v.d + ' 傷害；敵人易傷時再打一次。', v => ['傷害 ' + v.d, '易傷再一次'], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); if (tg[0] && core.isUp(tg[0]) && stkK(tg[0], 'vuln15')) kAtk(cb, core, tg, v.d, 1, { i: 1 }); });
KC('sw_tsubame', 'sw', '燕返', 'atk', 'U', 1, 'c9_sw9Tsubame', 'enemy', { d: 4 }, { d: 5 }, v => '造成 ' + v.d + ' 傷害 2 次，劍意 +1。', v => [v.d + ' ×2', '劍意 +1'], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d, 2); cb.addSi(1); });
KC('sw_riposte', 'sw', '反擊斬', 'atk', 'U', 1, 'c9_sw9Riposte', 'enemy', { d: 6, x: 6 }, { d: 8, x: 8 }, v => '造成 ' + v.d + ' 傷害；你有格擋時再 +' + v.x + '。', v => ['傷害 ' + v.d, '有格擋 +' + v.x], (cb, core, tg, v) => kAtk(cb, core, tg, v.d + (stkK(cb.Hu(), 'blk15') ? v.x : 0)));
KC('sw_sheathe', 'sw', '納刀', 'skl', 'U', 1, 'c9_sw9Sheathe', 'self', {}, {}, v => '劍意直接全滿。', v => ['劍意全滿'], (cb, core, tg, v) => cb.addSi(3), { upCost: 0 });
KC('sw_sky', 'sw', '一刀天斷', 'atk', 'R', 3, 't11_zjSky', 'enemy', { d: 32 }, { d: 42 }, v => '造成 ' + v.d + ' 傷害。', v => ['傷害 ' + v.d], (cb, core, tg, v) => kAtk(cb, core, tg, v.d));
KC('sw_meteor', 'sw', '崩星劍', 'atk', 'R', 2, 't11_sdMeteor', 'enemy', { d: 24 }, { d: 30 }, v => '造成 ' + v.d + ' 傷害；對易傷的敵人 ×1.5。消耗。', v => ['傷害 ' + v.d, '消耗'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 1, { mulF: t => stkK(t, 'vuln15') ? 1.5 : 1 }), { exhaust: 1 });
KC('sw_thousand', 'sw', '破曉千斬', 'atk', 'R', 3, 't11_ogSword', 'enemy', { d: 4 }, { d: 5 }, v => '造成 ' + v.d + ' 傷害 6 次，之後劍意直接全滿。', v => [v.d + ' ×6', '劍意全滿'], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d, 6); cb.fillSi = 1; });
KC('sw_master', 'sw', '劍聖之心', 'pow', 'R', 2, 't11_dsDance', 'self', {}, {}, v => '能力：每打出 3 張攻擊卡，抽 1 張、能量 +1。', v => ['攻擊3張', '抽1・能量1'], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwMaster15', 1), { upCost: 1 });
KC('sw_mujin', 'sw', '無塵', 'skl', 'R', 1, 'mikiri', 'self', {}, {}, v => '這回合下一張攻擊卡打兩次。', v => ['下一張攻擊', '打兩次'], (cb, core, tg, v) => { cb.twice = 1; }, { upCost: 0 });
KC('sw_tenpu', 'sw', '天風', 'atk', 'R', 2, 'c9_sw9Tenpu', 'all', { d: 7 }, { d: 9 }, v => '對全體造成 ' + v.d + ' 傷害 2 次。', v => ['全體 ' + v.d + '×2'], (cb, core, tg, v) => kAll(cb, core, v.d, 2));
/* ====================== 盜賊 ====================== */
KC('rg_stab', 'rg', '刺擊', 'atk', 'B', 1, 'quick', 'enemy', { d: 6 }, { d: 9 }, v => '造成 ' + v.d + ' 傷害。', v => ['傷害 ' + v.d], (cb, core, tg, v) => kAtk(cb, core, tg, v.d));
KC('rg_defend', 'rg', '防禦', 'skl', 'B', 1, 'guard', 'self', { b: 5 }, { b: 8 }, v => '獲得 ' + v.b + ' 格擋。', v => ['格擋 ' + v.b], (cb, core, tg, v) => kBlk(cb, core, v.b));
KC('rg_venom', 'rg', '毒風斬', 'atk', 'B', 1, 't11_dgVenom', 'enemy', { d: 3, x: 2 }, { d: 4, x: 3 }, v => '造成 ' + v.d + ' 傷害 2 次，毒 ' + v.x + '。', v => [v.d + ' ×2', '毒 ' + v.x], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d, 2); for (const t of tg) KD.add(core, cb.Hu(), t, 'pois14', v.x); });
KC('rg_quick', 'rg', '迅風斬', 'atk', 'C', 1, 't11_dgQuick', 'enemy', { d: 7 }, { d: 10 }, v => '造成 ' + v.d + ' 傷害，抽 1 張。', v => ['傷害 ' + v.d, '抽 1'], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); cb.drawN(1); });
KC('rg_fan', 'rg', '扇刃', 'skl', 'C', 1, 'agility', 'self', { x: 2 }, { x: 3 }, v => '把 ' + v.x + ' 張「飛刀」加到手牌。', v => ['飛刀 ×' + v.x], (cb, core, tg, v) => { for (let i = 0; i < v.x; i++) cb.addHand('tk_shiv'); });
KC('rg_shade', 'rg', '殘影步', 'skl', 'C', 1, 't11_dgShade', 'self', { b: 8, x: 3 }, { b: 11, x: 4 }, v => '獲得 ' + v.b + ' 格擋；下一張攻擊卡傷害 +' + v.x + '。', v => ['格擋 ' + v.b, '下次攻擊+' + v.x], (cb, core, tg, v) => { kBlk(cb, core, v.b); KD.add(core, cb.Hu(), cb.Hu(), 'nxa14', v.x); });
KC('rg_toxic', 'rg', '淬毒', 'skl', 'C', 1, 'c9_rg9Venom', 'enemy', { x: 5 }, { x: 7 }, v => '讓敵人中毒 ' + v.x + '。', v => ['毒 ' + v.x], (cb, core, tg, v) => { for (const t of tg) KD.add(core, cb.Hu(), t, 'pois14', v.x); });
KC('rg_smoke', 'rg', '煙霧彈', 'skl', 'C', 1, 'smokeBomb', 'self', { b: 6, x: 1 }, { b: 9, x: 2 }, v => '獲得 ' + v.b + ' 格擋，全體虛弱 ' + v.x + '。', v => ['格擋 ' + v.b, '全體虛弱' + v.x], (cb, core, tg, v) => { kBlk(cb, core, v.b); for (const t of kFoes(core)) KD.add(core, cb.Hu(), t, 'weak15', v.x); });
KC('rg_slip', 'rg', '閃身', 'skl', 'C', 0, 'agility', 'self', { b: 3 }, { b: 5 }, v => '獲得 ' + v.b + ' 格擋，抽 1 張。', v => ['格擋 ' + v.b, '抽 1'], (cb, core, tg, v) => { kBlk(cb, core, v.b); cb.drawN(1); });
KC('rg_backstab', 'rg', '背刺', 'atk', 'C', 0, 'backstab', 'enemy', { d: 9 }, { d: 12 }, v => '造成 ' + v.d + ' 傷害。消耗。', v => ['傷害 ' + v.d, '消耗'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d), { exhaust: 1 });
KC('rg_needle', 'rg', '雷痺斬', 'atk', 'C', 1, 't11_dgNeedle', 'enemy', { d: 6, x: 2 }, { d: 8, x: 3 }, v => '造成 ' + v.d + ' 雷屬性傷害，虛弱 ' + v.x + '。', v => ['傷害 ' + v.d, '虛弱 ' + v.x], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); for (const t of tg) KD.add(core, cb.Hu(), t, 'weak15', v.x); }, { el: '雷' });
KC('rg_prep', 'rg', '準備', 'skl', 'C', 1, 'focus', 'self', { c: 3 }, { c: 4 }, v => '抽 ' + v.c + ' 張。', v => ['抽 ' + v.c], (cb, core, tg, v) => cb.drawN(v.c));
KC('rg_mark', 'rg', '獵印', 'skl', 'C', 1, 'hunterMark', 'enemy', { x: 2, p: 3 }, { x: 3, p: 4 }, v => '讓敵人易傷 ' + v.x + '、中毒 ' + v.p + '。', v => ['易傷 ' + v.x, '毒 ' + v.p], (cb, core, tg, v) => { for (const t of tg) { KD.add(core, cb.Hu(), t, 'vuln15', v.x); KD.add(core, cb.Hu(), t, 'pois14', v.p); } });
KC('rg_rot', 'rg', '蝕毒連斬', 'atk', 'U', 1, 't11_dgRot', 'enemy', { d: 2, x: 2 }, { d: 3, x: 2 }, v => '造成 ' + v.d + ' 傷害 4 次；敵人中毒時每次 +' + v.x + '。', v => [v.d + ' ×4', '中毒 +' + v.x], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 4, { flatF: t => stkK(t, 'pois14') ? v.x : 0 }));
KC('rg_reap', 'rg', '斷命斬', 'atk', 'U', 2, 't11_dgReap', 'enemy', { d: 12 }, { d: 16 }, v => '造成 ' + v.d + ' 傷害；敵人 HP 一半以下時 ×1.5。', v => ['傷害 ' + v.d, '半血 ×1.5'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 1, { mulF: t => t.res.hp <= t.max.hp / 2 ? 1.5 : 1 }));
KC('rg_twin', 'rg', '雙影', 'atk', 'U', 1, 'c9_rg9TwinShadow', 'enemy', { d: 5 }, { d: 7 }, v => '造成 ' + v.d + ' 傷害 2 次。', v => [v.d + ' ×2'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 2));
KC('rg_lurk', 'rg', '潛伏', 'pow', 'U', 1, 'c9_rg9Lurk', 'self', {}, {}, v => '能力：每回合開始，把 1 張「飛刀」加到手牌。', v => ['每回合', '飛刀 +1'], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwLurk14', 1), { upCost: 0 });
KC('rg_knives', 'rg', '飛刀術', 'pow', 'U', 1, 'statUpFx', 'self', { x: 3 }, { x: 4 }, v => '能力：「飛刀」的傷害 +' + v.x + '。', v => ['飛刀 +' + v.x], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwKnife14', v.x));
KC('rg_dance', 'rg', '燕舞亂刃', 'atk', 'U', 2, 't11_ddDance', 'enemy', { d: 2, x: 3 }, { d: 3, x: 4 }, v => '造成 ' + v.d + ' 傷害 7 次，毒 ' + v.x + '。', v => [v.d + ' ×7', '毒 ' + v.x], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d, 7); for (const t of tg) KD.add(core, cb.Hu(), t, 'pois14', v.x); });
KC('rg_cross', 'rg', '交叉刺', 'atk', 'U', 1, 't11_ddCross', 'enemy', { d: 5, x: 1 }, { d: 6, x: 2 }, v => '造成 ' + v.d + ' 傷害 2 次，易傷 ' + v.x + '。', v => [v.d + ' ×2', '易傷 ' + v.x], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d, 2); for (const t of tg) KD.add(core, cb.Hu(), t, 'vuln15', v.x); });
KC('rg_catalyst', 'rg', '引毒', 'skl', 'U', 1, 'deathMark', 'enemy', { x: 2 }, { x: 3 }, v => '敵人身上的毒變成 ' + v.x + ' 倍。消耗。', v => ['毒層數 ×' + v.x, '消耗'], (cb, core, tg, v) => { for (const t of tg) { const p = stkK(t, 'pois14'); if (p) KD.add(core, cb.Hu(), t, 'pois14', p * (v.x - 1)); } }, { exhaust: 1 });
KC('rg_adren', 'rg', '腎上腺', 'skl', 'U', 0, 'overdrive', 'self', { e: 1, c: 2 }, { e: 2, c: 2 }, v => '能量 +' + v.e + '，抽 ' + v.c + ' 張。消耗。', v => ['能量 +' + v.e, '抽 ' + v.c], (cb, core, tg, v) => { cb.energy += v.e; cb.drawN(v.c); }, { exhaust: 1 });
KC('rg_envenom', 'rg', '淬毒之刃', 'pow', 'U', 1, 'buff', 'self', {}, {}, v => '能力：你的攻擊造成傷害時，讓敵人中毒 1。', v => ['攻擊時', '毒 +1'], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwEnv14', 1), { upCost: 0 });
KC('rg_bloom', 'rg', '千刃亂舞', 'atk', 'R', 2, 't11_dgBloom', 'enemy', { d: 2, x: 6 }, { d: 3, x: 8 }, v => '造成 ' + v.d + ' 傷害 5 次；敵人每有一種負面狀態，再造成 ' + v.x + ' 傷害。', v => [v.d + ' ×5', '狀態 +' + v.x], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d, 5); for (const t of tg) { const n = core.isUp(t) ? kDeb(t, core) : 0; for (let i = 0; i < n; i++) kAtk(cb, core, [t], v.x, 1, { i: 5 + i }); } });
KC('rg_stitch', 'rg', '縛影斬', 'atk', 'R', 2, 't11_dgStitch', 'enemy', { d: 10 }, { d: 14 }, v => '造成 ' + v.d + ' 傷害，敵人這回合不能行動（頭目改成虛弱 3、易傷 3）。消耗。', v => ['傷害 ' + v.d, '定身'], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); for (const t of tg) kStop(cb, core, t); }, { exhaust: 1 });
KC('rg_fatal', 'rg', '致命一擊', 'atk', 'R', 2, 'c9_rg9Fatal', 'enemy', { d: 15, x: 2 }, { d: 20, x: 3 }, v => '造成 ' + v.d + ' 傷害；敵人每有 1 層毒，再多 ' + v.x + ' 傷害。', v => ['傷害 ' + v.d, '+毒層×' + v.x], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 1, { flatF: t => stkK(t, 'pois14') * v.x }));
KC('rg_grave', 'rg', '影葬連刃', 'atk', 'R', 2, 't11_ogDagger', 'enemy', { d: 3 }, { d: 4 }, v => '造成 ' + v.d + ' 傷害 4 次；敵人中毒時再 3 次，虛弱或易傷時再 3 次。', v => [v.d + ' ×4〜10'], (cb, core, tg, v) => { const t = tg[0]; const n = 4 + (t && stkK(t, 'pois14') ? 3 : 0) + (t && (stkK(t, 'weak15') || stkK(t, 'vuln15')) ? 3 : 0); kAtk(cb, core, tg, v.d, n); });
KC('rg_phantom', 'rg', '幻影步', 'pow', 'R', 3, 'afterimageOn', 'self', {}, {}, v => '能力：每回合打出的第一張攻擊卡打兩次。', v => ['第一張攻擊', '打兩次'], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwPhantom14', 1), { upCost: 2 });
KC('tk_shiv', 'rg', '飛刀', 'atk', 'T', 0, 'throwKnives', 'enemy', { d: 4 }, { d: 6 }, v => '造成 ' + v.d + ' 傷害。消耗。', v => ['傷害 ' + v.d, '消耗'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d + stkK(cb.Hu(), 'pwKnife14')), { exhaust: 1 });
/* ====================== 法師 ====================== */
KC('mg_bolt', 'mg', '魔力彈', 'atk', 'B', 1, 'magicBolt', 'enemy', { d: 6 }, { d: 9 }, v => '造成 ' + v.d + ' 傷害。', v => ['傷害 ' + v.d], (cb, core, tg, v) => kAtk(cb, core, tg, v.d));
KC('mg_shield', 'mg', '護盾術', 'skl', 'B', 1, 'barrier', 'self', { b: 5 }, { b: 8 }, v => '獲得 ' + v.b + ' 格擋。', v => ['格擋 ' + v.b], (cb, core, tg, v) => kBlk(cb, core, v.b));
KC('mg_fire', 'mg', '火球', 'atk', 'B', 1, 'fireBolt', 'enemy', { d: 5, x: 2 }, { d: 7, x: 3 }, v => '造成 ' + v.d + ' 火屬性傷害，燃燒 ' + v.x + '。', v => ['傷害 ' + v.d, '燃燒 ' + v.x], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); for (const t of tg) KD.add(core, cb.Hu(), t, 'burn14', v.x); }, { el: '火' });
KC('mg_frost', 'mg', '冰霜箭', 'atk', 'C', 1, 'frostBloom', 'enemy', { d: 6, x: 1 }, { d: 8, x: 2 }, v => '造成 ' + v.d + ' 水屬性傷害，虛弱 ' + v.x + '。', v => ['傷害 ' + v.d, '虛弱 ' + v.x], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); for (const t of tg) KD.add(core, cb.Hu(), t, 'weak15', v.x); }, { el: '水' });
KC('mg_spark', 'mg', '電光', 'atk', 'C', 0, 'quickBolt', 'rand', { d: 3 }, { d: 4 }, v => '對隨機敵人造成 ' + v.d + ' 雷屬性傷害 2 次。', v => ['隨機 ' + v.d + '×2'], (cb, core, tg, v) => kRandHits(cb, core, v.d, 2), { el: '雷' });
KC('mg_arrows', 'mg', '魔力箭', 'atk', 'C', 1, 't11_stArrows', 'enemy', { d: 3 }, { d: 4 }, v => '造成 ' + v.d + ' 傷害 3 次。', v => [v.d + ' ×3'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 3));
KC('mg_wall', 'mg', '法力屏障', 'skl', 'C', 1, 't11_stWall', 'self', { b: 7 }, { b: 10 }, v => '獲得 ' + v.b + ' 格擋，抽 1 張。', v => ['格擋 ' + v.b, '抽 1'], (cb, core, tg, v) => { kBlk(cb, core, v.b); cb.drawN(1); });
KC('mg_ember', 'mg', '火花', 'skl', 'C', 1, 'ember', 'all', { x: 2 }, { x: 3 }, v => '讓全體燃燒 ' + v.x + '。', v => ['全體燃燒 ' + v.x], (cb, core, tg, v) => { for (const t of kFoes(core)) KD.add(core, cb.Hu(), t, 'burn14', v.x); }, { el: '火' });
KC('mg_chain', 'mg', '連鎖閃電', 'atk', 'C', 1, 'chainBolt', 'rand', { d: 3 }, { d: 4 }, v => '對隨機敵人造成 ' + v.d + ' 雷屬性傷害 4 次。', v => ['隨機 ' + v.d + '×4'], (cb, core, tg, v) => kRandHits(cb, core, v.d, 4), { el: '雷' });
KC('mg_lance', 'mg', '魔力槍', 'atk', 'C', 2, 't11_stLance', 'enemy', { d: 13, x: 1 }, { d: 17, x: 2 }, v => '造成 ' + v.d + ' 傷害，易傷 ' + v.x + '。', v => ['傷害 ' + v.d, '易傷 ' + v.x], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); for (const t of tg) KD.add(core, cb.Hu(), t, 'vuln15', v.x); });
KC('mg_icewall', 'mg', '冰牆', 'skl', 'C', 2, 'c9_mg9ChantWall', 'self', { b: 13 }, { b: 17 }, v => '獲得 ' + v.b + ' 格擋。', v => ['格擋 ' + v.b], (cb, core, tg, v) => kBlk(cb, core, v.b));
KC('mg_slow', 'mg', '遲滯咒', 'skl', 'C', 1, 't11_tmSlow', 'enemy', { x: 2 }, { x: 3 }, v => '讓敵人虛弱 ' + v.x + '、易傷 1。', v => ['虛弱 ' + v.x, '易傷 1'], (cb, core, tg, v) => { for (const t of tg) { KD.add(core, cb.Hu(), t, 'weak15', v.x); KD.add(core, cb.Hu(), t, 'vuln15', 1); } });
KC('mg_page', 'mg', '守護之頁', 'skl', 'C', 0, 't11_tmPage', 'self', { b: 4 }, { b: 6 }, v => '獲得 ' + v.b + ' 格擋。', v => ['格擋 ' + v.b], (cb, core, tg, v) => kBlk(cb, core, v.b));
KC('mg_storm', 'mg', '魔力風暴', 'atk', 'U', 2, 't11_stStorm', 'all', { d: 9 }, { d: 12 }, v => '對全體造成 ' + v.d + ' 傷害。', v => ['全體 ' + v.d], (cb, core, tg, v) => kAll(cb, core, v.d));
KC('mg_blaze', 'mg', '烈焰', 'atk', 'U', 2, 'flameWave', 'all', { d: 6, x: 3 }, { d: 8, x: 4 }, v => '對全體造成 ' + v.d + ' 火屬性傷害，燃燒 ' + v.x + '。', v => ['全體 ' + v.d, '燃燒 ' + v.x], (cb, core, tg, v) => { kAll(cb, core, v.d); for (const t of kFoes(core)) KD.add(core, cb.Hu(), t, 'burn14', v.x); }, { el: '火' });
KC('mg_thunder', 'mg', '落雷', 'atk', 'U', 2, 'thunder', 'enemy', { d: 16 }, { d: 21 }, v => '造成 ' + v.d + ' 雷屬性傷害。', v => ['傷害 ' + v.d], (cb, core, tg, v) => kAtk(cb, core, tg, v.d), { el: '雷' });
KC('mg_impact', 'mg', '魔力衝擊', 'atk', 'U', 1, 't11_stImpact', 'enemy', { d: 7 }, { d: 10 }, v => '造成 ' + v.d + ' 傷害；對蓄力中的敵人 ×2，並打斷蓄力。', v => ['傷害 ' + v.d, '打斷蓄力'], (cb, core, tg, v) => { for (const t of tg) { const ch = core.hasStatus(t, 'charging'); kAtk(cb, core, [t], v.d, 1, { mul: ch ? 2 : 1 }); if (ch && core.isUp(t)) core.removeStatus(t, 'charging', 'break'); } });
KC('mg_haste', 'mg', '時之加速', 'skl', 'U', 1, 't11_stHaste', 'self', { e: 2 }, { e: 2 }, v => '能量 +' + v.e + '。消耗。', v => ['能量 +' + v.e, '消耗'], (cb, core, tg, v) => { cb.energy += v.e; }, { exhaust: 1, upCost: 0 });
KC('mg_combust', 'mg', '引爆', 'atk', 'U', 1, 'combust', 'enemy', { x: 3 }, { x: 4 }, v => '敵人每有 1 層燃燒，造成 ' + v.x + ' 火屬性傷害，然後燃燒消失。', v => ['燃燒層數', '×' + v.x + ' 傷害'], (cb, core, tg, v) => { for (const t of tg) { const b = stkK(t, 'burn14'); if (b) { kAtk(cb, core, [t], b * v.x); if (core.isUp(t)) setStk15(core, t, 'burn14', 0); } } }, { el: '火' });
KC('mg_pages', 'mg', '飛頁之舞', 'atk', 'U', 1, 't11_tmPages', 'all', { d: 5 }, { d: 7 }, v => '對全體造成 ' + v.d + ' 傷害，抽 1 張。', v => ['全體 ' + v.d, '抽 1'], (cb, core, tg, v) => { kAll(cb, core, v.d); cb.drawN(1); });
KC('mg_drain', 'mg', '吸魔咒', 'atk', 'U', 2, 't11_tmDrain', 'enemy', { d: 10 }, { d: 14 }, v => '造成 ' + v.d + ' 傷害；下回合能量 +1。', v => ['傷害 ' + v.d, '下回合能量+1'], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); cb.nextEn++; });
KC('mg_kindle', 'mg', '點燃', 'pow', 'U', 1, 'flameWallOn', 'self', { x: 1 }, { x: 2 }, v => '能力：每回合開始，讓全體燃燒 ' + v.x + '。', v => ['每回合', '全體燃燒' + v.x], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwKindle14', v.x));
KC('mg_static', 'mg', '靜電場', 'pow', 'U', 1, 'staticOn', 'self', { x: 3 }, { x: 4 }, v => '能力：每打出一張技能卡，對隨機敵人造成 ' + v.x + ' 雷屬性傷害。', v => ['技能卡', '電擊 ' + v.x], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwStatic14', v.x));
KC('mg_chainc', 'mg', '詛咒連鎖', 'atk', 'U', 1, 't11_tmChain', 'enemy', { d: 3, x: 1 }, { d: 4, x: 2 }, v => '造成 ' + v.d + ' 傷害 3 次，易傷 ' + v.x + '。', v => [v.d + ' ×3', '易傷 ' + v.x], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d, 3); for (const t of tg) KD.add(core, cb.Hu(), t, 'vuln15', v.x); });
KC('mg_finale', 'mg', '魔力終曲', 'atk', 'R', 3, 't11_stFinale', 'enemy', { d: 10, x: 6 }, { d: 14, x: 8 }, v => '造成 ' + v.d + ' 傷害；這回合每打出過一張卡再 +' + v.x + '。', v => ['傷害 ' + v.d, '每張 +' + v.x], (cb, core, tg, v) => kAtk(cb, core, tg, v.d + cb.cardsN * v.x));
KC('mg_max', 'mg', '魔導極限', 'pow', 'R', 2, 't11_stMax', 'self', {}, {}, v => '能力：每回合能量 +1。', v => ['每回合', '能量 +1'], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwMax14', 1), { upCost: 1 });
KC('mg_four', 'mg', '魔力奔流', 'atk', 'R', 2, 't11_zjFourFold', 'enemy', { d: 5 }, { d: 7 }, v => '造成 ' + v.d + ' 傷害 4 次。', v => [v.d + ' ×4'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 4));
KC('mg_meteor', 'mg', '隕石術', 'skl', 'R', 3, 'charge', 'self', { d: 30 }, { d: 40 }, v => '蓄力：你下回合開始時，隕石對全體造成 ' + v.d + ' 傷害。', v => ['下回合', '全體 ' + v.d], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'chgM14', v.d));
KC('mg_stop', 'mg', '時之停滯', 'skl', 'R', 2, 't11_tmStop', 'enemy', {}, {}, v => '敵人這回合不能行動（頭目改成虛弱 3、易傷 3）。消耗。', v => ['定身', '消耗'], (cb, core, tg, v) => { for (const t of tg) kStop(cb, core, t); }, { exhaust: 1, upCost: 1 });
KC('mg_inferno', 'mg', '煉獄', 'atk', 'R', 3, 'inferno', 'all', { d: 14, x: 4 }, { d: 18, x: 5 }, v => '對全體造成 ' + v.d + ' 火屬性傷害，燃燒 ' + v.x + '。', v => ['全體 ' + v.d, '燃燒 ' + v.x], (cb, core, tg, v) => { kAll(cb, core, v.d); for (const t of kFoes(core)) KD.add(core, cb.Hu(), t, 'burn14', v.x); }, { el: '火' });
KC('mg_phoenix', 'mg', '不死鳥', 'pow', 'R', 3, 'holyLight', 'self', {}, {}, v => '能力：這場戰鬥 HP 第一次歸零時，回復到一半。', v => ['倒下時', '復活一次'], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwPhoenix14', 1), { upCost: 2 });
KC('mg_meteorHit', 'mg', '隕石', 'atk', 'T', 0, 'meteor', 'all', { d: 30 }, { d: 30 }, v => '隕石落下。', v => ['全體'], (cb, core, tg, v) => { const H = cb.Hu(), d = stkK(H, 'chgM14'); core.removeStatus(H, 'chgM14', 'used'); if (d) kAll(cb, core, d); }, { hidden: 1 });
/* ====================== 狂戰士 ====================== */
const kLose = (cb, core, n) => { const H = cb.Hu(); n = Math.min(n, H.res.hp - 1); if (n <= 0) return; core.dealDamage(null, H, n, { kind: 'fixed', cat: 'fixed', min: 1, tags: ['self', 'card14'] }); const r = stkK(H, 'pwRage14'); if (r && core.isUp(H)) KD.add(core, H, H, 'str15', r); };
KC('bk_chop', 'bk', '劈砍', 'atk', 'B', 1, 'cleave', 'enemy', { d: 6 }, { d: 9 }, v => '造成 ' + v.d + ' 傷害。', v => ['傷害 ' + v.d], (cb, core, tg, v) => kAtk(cb, core, tg, v.d));
KC('bk_defend', 'bk', '防禦', 'skl', 'B', 1, 'guard', 'self', { b: 5 }, { b: 8 }, v => '獲得 ' + v.b + ' 格擋。', v => ['格擋 ' + v.b], (cb, core, tg, v) => kBlk(cb, core, v.b));
KC('bk_split', 'bk', '劈山', 'atk', 'B', 2, 't11_axSplit', 'enemy', { d: 9, x: 2 }, { d: 12, x: 3 }, v => '造成 ' + v.d + ' 傷害，易傷 ' + v.x + '；對護盾 ×2。', v => ['傷害 ' + v.d, '易傷 ' + v.x], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d, 1, { wardSkill: 't_axSplit' }); for (const t of tg) KD.add(core, cb.Hu(), t, 'vuln15', v.x); });
KC('bk_spin', 'bk', '迴旋斧', 'atk', 'C', 1, 't11_axSpin', 'all', { d: 5 }, { d: 7 }, v => '對全體造成 ' + v.d + ' 傷害。', v => ['全體 ' + v.d], (cb, core, tg, v) => kAll(cb, core, v.d));
KC('bk_roar', 'bk', '狂吼', 'skl', 'C', 1, 't11_axRoar', 'self', { x: 2, h: 3 }, { x: 3, h: 3 }, v => '失去 ' + v.h + ' HP，力量 +' + v.x + '。', v => ['力量 +' + v.x, '失去 ' + v.h + ' HP'], (cb, core, tg, v) => { kLose(cb, core, v.h); KD.add(core, cb.Hu(), cb.Hu(), 'str15', v.x); });
KC('bk_triple', 'bk', '三連拳', 'atk', 'C', 1, 't11_fsTriple', 'enemy', { d: 3 }, { d: 4 }, v => '造成 ' + v.d + ' 傷害 3 次。', v => [v.d + ' ×3'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 3));
KC('bk_fury', 'bk', '怒濤劈', 'atk', 'C', 1, 't11_axFury', 'enemy', { d: 7 }, { d: 9 }, v => '造成 ' + v.d + ' 傷害；你的 HP 一半以下時 ×2。', v => ['傷害 ' + v.d, '半血 ×2'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 1, { mul: kHalf(cb) ? 2 : 1 }));
KC('bk_blood', 'bk', '鮮血狂斬', 'atk', 'C', 1, 'bloodBlade', 'enemy', { d: 12, h: 3 }, { d: 16, h: 3 }, v => '失去 ' + v.h + ' HP，造成 ' + v.d + ' 傷害。', v => ['傷害 ' + v.d, '失去 ' + v.h + ' HP'], (cb, core, tg, v) => { kLose(cb, core, v.h); kAtk(cb, core, tg, v.d); });
KC('bk_brace', 'bk', '硬撐', 'skl', 'C', 1, 'ironWill', 'self', { b: 7, x: 4 }, { b: 10, x: 5 }, v => '獲得 ' + v.b + ' 格擋；HP 一半以下時再 +' + v.x + '。', v => ['格擋 ' + v.b, '半血 +' + v.x], (cb, core, tg, v) => kBlk(cb, core, v.b + (kHalf(cb) ? v.x : 0)));
KC('bk_quake', 'bk', '震地擊', 'atk', 'C', 2, 't11_axQuake', 'all', { d: 9, x: 1 }, { d: 12, x: 1 }, v => '對全體造成 ' + v.d + ' 傷害，虛弱 ' + v.x + '。', v => ['全體 ' + v.d, '虛弱 ' + v.x], (cb, core, tg, v) => { kAll(cb, core, v.d); for (const t of kFoes(core)) KD.add(core, cb.Hu(), t, 'weak15', v.x); });
KC('bk_fbreak', 'bk', '破體拳', 'atk', 'C', 1, 't11_fsBreak', 'enemy', { d: 6, x: 1 }, { d: 8, x: 2 }, v => '造成 ' + v.d + ' 傷害，易傷 ' + v.x + '。', v => ['傷害 ' + v.d, '易傷 ' + v.x], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); for (const t of tg) KD.add(core, cb.Hu(), t, 'vuln15', v.x); });
KC('bk_kick', 'bk', '旋踢', 'atk', 'C', 1, 't11_fsKick', 'all', { d: 3 }, { d: 4 }, v => '對全體造成 ' + v.d + ' 傷害 2 次。', v => ['全體 ' + v.d + '×2'], (cb, core, tg, v) => kAll(cb, core, v.d, 2));
KC('bk_breath', 'bk', '吐納', 'skl', 'C', 0, 't11_fsBreath', 'self', { h: 4 }, { h: 6 }, v => '回復 ' + v.h + ' HP。消耗。', v => ['回復 ' + v.h, '消耗'], (cb, core, tg, v) => KD.heal(core, cb.Hu(), v.h), { exhaust: 1 });
KC('bk_crush', 'bk', '碎盾擊', 'atk', 'U', 2, 't11_axCrush', 'enemy', { d: 14 }, { d: 18 }, v => '造成 ' + v.d + ' 傷害；對護盾 ×3。', v => ['傷害 ' + v.d, '碎盾'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 1, { wardSkill: 't_axCrush' }));
KC('bk_bloodp', 'bk', '狂戰之血', 'pow', 'U', 1, 't11_axBlood', 'self', { x: 15 }, { x: 20 }, v => '能力：攻擊卡回復造成傷害 ' + v.x + '% 的 HP。', v => ['吸血 ' + v.x + '%'], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwBlood14', v.x));
KC('bk_rage', 'bk', '狂暴', 'pow', 'U', 1, 'howl', 'self', {}, {}, v => '能力：每次因為自己的卡失去 HP，力量 +1。', v => ['失去 HP 時', '力量 +1'], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwRage14', 1), { upCost: 0 });
KC('bk_shell', 'bk', '碎殼掌', 'atk', 'U', 1, 't11_fsShell', 'enemy', { d: 7, x: 2 }, { d: 9, x: 3 }, v => '造成 ' + v.d + ' 傷害，易傷 ' + v.x + '。', v => ['傷害 ' + v.d, '易傷 ' + v.x], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); for (const t of tg) KD.add(core, cb.Hu(), t, 'vuln15', v.x); });
KC('bk_storm', 'bk', '狂嵐拳', 'atk', 'U', 2, 't11_fsStorm', 'enemy', { d: 2 }, { d: 3 }, v => '造成 ' + v.d + ' 傷害 8 次。', v => [v.d + ' ×8'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 8));
KC('bk_iron', 'bk', '鐵律重斧', 'atk', 'U', 2, 't11_zjIronLaw', 'enemy', { d: 8 }, { d: 12 }, v => '造成 ' + v.d + ' 傷害，再加上你目前的格擋。', v => ['傷害 ' + v.d, '+格擋'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d + stkK(cb.Hu(), 'blk15')));
KC('bk_warcry', 'bk', '戰吼', 'skl', 'U', 1, 'warCry', 'self', { x: 2, s: 1 }, { x: 3, s: 1 }, v => '全體虛弱 ' + v.x + '，力量 +' + v.s + '。', v => ['全體虛弱' + v.x, '力量 +' + v.s], (cb, core, tg, v) => { for (const t of kFoes(core)) KD.add(core, cb.Hu(), t, 'weak15', v.x); KD.add(core, cb.Hu(), cb.Hu(), 'str15', v.s); });
KC('bk_reckless', 'bk', '捨身', 'skl', 'U', 0, 'dragonBlood', 'self', { h: 4, e: 2 }, { h: 2, e: 2 }, v => '失去 ' + v.h + ' HP，能量 +' + v.e + '。', v => ['能量 +' + v.e, '失去 ' + v.h + ' HP'], (cb, core, tg, v) => { kLose(cb, core, v.h); cb.energy += v.e; });
KC('bk_through', 'bk', '震山擊', 'atk', 'U', 2, 't11_fsThrough', 'enemy', { d: 16, x: 2 }, { d: 21, x: 2 }, v => '造成 ' + v.d + ' 傷害，虛弱 ' + v.x + '。', v => ['傷害 ' + v.d, '虛弱 ' + v.x], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); for (const t of tg) KD.add(core, cb.Hu(), t, 'weak15', v.x); });
KC('bk_last', 'bk', '背水', 'skl', 'U', 1, 'ironBody', 'self', { b: 6, x: 6, s: 2 }, { b: 8, x: 8, s: 3 }, v => '獲得 ' + v.b + ' 格擋；HP 一半以下時再 +' + v.x + ' 格擋、力量 +' + v.s + '。', v => ['格擋 ' + v.b, '半血更強'], (cb, core, tg, v) => { const h = kHalf(cb); kBlk(cb, core, v.b + (h ? v.x : 0)); if (h) KD.add(core, cb.Hu(), cb.Hu(), 'str15', v.s); });
KC('bk_castle', 'bk', '崩城擊', 'atk', 'R', 3, 't11_axCastle', 'enemy', { d: 28 }, { d: 36 }, v => '造成 ' + v.d + ' 傷害；對易傷的敵人 ×1.5。', v => ['傷害 ' + v.d, '易傷 ×1.5'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 1, { mulF: t => stkK(t, 'vuln15') ? 1.5 : 1 }));
KC('bk_ogaxe', 'bk', '天崩地裂', 'atk', 'R', 3, 't11_ogAxe', 'all', { d: 20, x: 2 }, { d: 26, x: 2 }, v => '對全體造成 ' + v.d + ' 傷害，虛弱 ' + v.x + '。', v => ['全體 ' + v.d, '虛弱 ' + v.x], (cb, core, tg, v) => { kAll(cb, core, v.d); for (const t of kFoes(core)) KD.add(core, cb.Hu(), t, 'weak15', v.x); });
KC('bk_upper', 'bk', '沖天拳', 'atk', 'R', 2, 't11_zjQuake', 'enemy', { d: 14 }, { d: 18 }, v => '造成 ' + v.d + ' 傷害；力量的加成算 3 次。', v => ['傷害 ' + v.d, '力量 ×3'], (cb, core, tg, v) => { const H = cb.Hu(); kAtk(cb, core, tg, v.d + 2 * (stkK(H, 'str15') + stkK(H, 'tstr14'))); });
KC('bk_hundred', 'bk', '百烈崩拳', 'atk', 'R', 3, 't11_ogFist', 'enemy', { d: 2 }, { d: 3 }, v => '造成 ' + v.d + ' 傷害 10 次。', v => [v.d + ' ×10'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 10));
KC('bk_asura', 'bk', '阿修羅', 'pow', 'R', 2, 'bloodRage', 'self', {}, {}, v => '能力：「血怒」一直生效（不管 HP 多少）。', v => ['血怒', '一直生效'], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwAsura14', 1), { upCost: 1 });
KC('bk_limit', 'bk', '極限突破', 'skl', 'R', 1, 'statUpFx', 'self', {}, {}, v => '力量變成 2 倍。消耗。', v => ['力量 ×2', '消耗'], (cb, core, tg, v) => { const H = cb.Hu(), s = stkK(H, 'str15'); if (s > 0) KD.add(core, H, H, 'str15', s); }, { exhaust: 1, upCost: 0 });
/* ====================== 共通（每個職業都能用） ====================== */
KC('nt_dash', 'nt', '疾突', 'atk', 'C', 0, 't11_spDash', 'enemy', { d: 3 }, { d: 4 }, v => '造成 ' + v.d + ' 傷害，抽 1 張。', v => ['傷害 ' + v.d, '抽 1'], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); cb.drawN(1); });
KC('nt_pierce', 'nt', '穿甲刺', 'atk', 'C', 1, 't11_spPierce', 'enemy', { d: 9 }, { d: 12 }, v => '造成 ' + v.d + ' 傷害。', v => ['傷害 ' + v.d], (cb, core, tg, v) => kAtk(cb, core, tg, v.d));
KC('nt_rapid', 'nt', '速射', 'atk', 'C', 1, 't11_gnRapid', 'enemy', { d: 4 }, { d: 5 }, v => '造成 ' + v.d + ' 傷害 2 次。', v => [v.d + ' ×2'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 2));
KC('nt_sweep', 'nt', '掃槍', 'atk', 'C', 1, 't11_spSweep', 'all', { d: 5 }, { d: 7 }, v => '對全體造成 ' + v.d + ' 傷害。', v => ['全體 ' + v.d], (cb, core, tg, v) => kAll(cb, core, v.d));
KC('nt_aid', 'nt', '急救', 'skl', 'C', 1, 'heal', 'self', { h: 8 }, { h: 12 }, v => '回復 ' + v.h + ' HP。消耗。', v => ['回復 ' + v.h, '消耗'], (cb, core, tg, v) => KD.heal(core, cb.Hu(), v.h), { exhaust: 1 });
KC('nt_tactic', 'nt', '戰術', 'skl', 'C', 1, 'focus', 'self', { c: 2 }, { c: 3 }, v => '抽 ' + v.c + ' 張。', v => ['抽 ' + v.c], (cb, core, tg, v) => cb.drawN(v.c));
KC('nt_dawn', 'nt', '晨曦之刃', 'atk', 'U', 2, 't11_cmDawn', 'enemy', { d: 12 }, { d: 16 }, v => '造成 ' + v.d + ' 傷害，回復傷害 30% 的 HP。', v => ['傷害 ' + v.d, '吸血30%'], (cb, core, tg, v) => { const t = kAtk(cb, core, tg, v.d); KD.heal(core, cb.Hu(), t * 0.3); });
KC('nt_twin', 'nt', '雙相斬', 'atk', 'U', 1, 't11_cmTwin', 'enemy', { d: 5 }, { d: 7 }, v => '造成 ' + v.d + ' 物理傷害和 ' + v.d + ' 魔法傷害。', v => [v.d + ' ×2'], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d, 1, { cat: '物' }); kAtk(cb, core, tg, v.d, 1, { cat: '特', i: 1 }); });
KC('nt_aim', 'nt', '瞄準射擊', 'atk', 'U', 2, 't11_gnAim', 'enemy', { d: 16 }, { d: 21 }, v => '造成 ' + v.d + ' 傷害。', v => ['傷害 ' + v.d], (cb, core, tg, v) => kAtk(cb, core, tg, v.d));
KC('nt_rally', 'nt', '鼓舞之歌', 'skl', 'U', 1, 't11_inRally', 'self', { x: 3 }, { x: 4 }, v => '這回合力量 +' + v.x + '。', v => ['這回合', '力量 +' + v.x], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'tstr14', v.x));
KC('nt_heal', 'nt', '療癒旋律', 'skl', 'U', 2, 't11_inHeal', 'self', { h: 12 }, { h: 16 }, v => '回復 ' + v.h + ' HP，解除異常狀態。消耗。', v => ['回復 ' + v.h, '解除異常'], (cb, core, tg, v) => { const H = cb.Hu(); KD.heal(core, H, v.h); const m = core.majorOf(H); if (m) core.removeStatus(H, m, 'cure'); setStk15(core, H, 'weak15', 0); setStk15(core, H, 'vuln15', 0); }, { exhaust: 1 });
KC('nt_wind', 'nt', '疾風之歌', 'skl', 'U', 1, 't11_inWind', 'self', { c: 2 }, { c: 3 }, v => '抽 ' + v.c + ' 張，能量 +1。消耗。', v => ['抽 ' + v.c, '能量 +1'], (cb, core, tg, v) => { cb.drawN(v.c); cb.energy++; }, { exhaust: 1 });
KC('nt_harmony', 'nt', '守護和聲', 'skl', 'U', 2, 't11_inHarmony', 'self', { b: 14 }, { b: 18 }, v => '獲得 ' + v.b + ' 格擋。', v => ['格擋 ' + v.b], (cb, core, tg, v) => kBlk(cb, core, v.b));
KC('nt_shbash', 'nt', '雙盾擊', 'atk', 'U', 2, 't11_shBash', 'enemy', { d: 10, b: 10 }, { d: 13, b: 13 }, v => '造成 ' + v.d + ' 傷害，獲得 ' + v.b + ' 格擋。', v => ['傷害 ' + v.d, '格擋 ' + v.b], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); kBlk(cb, core, v.b); });
KC('nt_echo', 'nt', '回音擊', 'atk', 'R', 1, 't11_inEcho', 'enemy', { d: 8 }, { d: 11 }, v => '造成 ' + v.d + ' 傷害；敵人有負面狀態時 ×2。', v => ['傷害 ' + v.d, '有狀態 ×2'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 1, { mulF: t => kDeb(t, core) ? 2 : 1 }));
KC('nt_roar', 'nt', '轟音', 'atk', 'R', 2, 't11_inRoar', 'all', { d: 10, x: 1 }, { d: 13, x: 2 }, v => '對全體造成 ' + v.d + ' 傷害，虛弱 ' + v.x + '。', v => ['全體 ' + v.d, '虛弱 ' + v.x], (cb, core, tg, v) => { kAll(cb, core, v.d); for (const t of kFoes(core)) KD.add(core, cb.Hu(), t, 'weak15', v.x); });
/* ====================== 頭目傳說卡（第一次擊敗頭目時得到，每張只有一張） ====================== */
KD.BOSS_CARD = {};
const KL = (boss, id, ...a) => { KC(id, 'nt', ...a); KD.CARDS[id].boss = boss; KD.BOSS_CARD[boss] = id; };
KL('banditBoss', 'lg_gren', '格倫的戰斧', 'atk', 'L', 2, 'quakeCleave', 'enemy', { d: 20, x: 2 }, { d: 26, x: 2 }, v => '造成 ' + v.d + ' 傷害，力量 +' + v.x + '。', v => ['傷害 ' + v.d, '力量 +' + v.x], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); KD.add(core, cb.Hu(), cb.Hu(), 'str15', v.x); });
KL('duneWorm', 'lg_dune', '流沙之牙', 'atk', 'L', 1, 'rockSlide', 'all', { d: 8, x: 2 }, { d: 11, x: 2 }, v => '對全體造成 ' + v.d + ' 傷害，虛弱 ' + v.x + '。', v => ['全體 ' + v.d, '虛弱 ' + v.x], (cb, core, tg, v) => { kAll(cb, core, v.d); for (const t of kFoes(core)) KD.add(core, cb.Hu(), t, 'weak15', v.x); });
KL('golem', 'lg_rock', '岩之心', 'pow', 'L', 2, 'ironWall', 'self', { x: 8 }, { x: 11 }, v => '能力：每回合開始獲得 ' + v.x + ' 格擋。', v => ['每回合', '格擋 ' + v.x], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwRock14', v.x));
KL('crystalGolem', 'lg_crystal', '水晶稜鏡', 'skl', 'L', 1, 'focus', 'self', {}, {}, v => '這回合下一張打出的卡（能力卡除外）效果發動兩次。', v => ['下一張卡', '發動兩次'], (cb, core, tg, v) => { cb.dupNext = 1; }, { upCost: 0 });
KL('silverWyrm', 'lg_wyrm', '龍鱗之潮', 'atk', 'L', 2, 'o12_tidalRage', 'all', { d: 12, b: 12 }, { d: 15, b: 15 }, v => '對全體造成 ' + v.d + ' 水屬性傷害，獲得 ' + v.b + ' 格擋。', v => ['全體 ' + v.d, '格擋 ' + v.b], (cb, core, tg, v) => { kAll(cb, core, v.d); kBlk(cb, core, v.b); }, { el: '水' });
KL('hydra', 'lg_hydra', '九頭毒牙', 'atk', 'L', 2, 'venomFang', 'rand', { d: 3 }, { d: 4 }, v => '對隨機敵人造成 ' + v.d + ' 傷害 9 次，每次毒 1。', v => ['隨機 ' + v.d + '×9', '毒'], (cb, core, tg, v) => { for (let i = 0; i < 9; i++) { const t = kRand(core); if (!t) break; kAtk(cb, core, [t], v.d, 1, { i }); KD.add(core, cb.Hu(), t, 'pois14', 1); } });
KL('ratKing', 'lg_rat', '鼠王的寶藏', 'skl', 'L', 0, 'buff', 'self', { c: 3 }, { c: 4 }, v => '抽 ' + v.c + ' 張。消耗。', v => ['抽 ' + v.c, '消耗'], (cb, core, tg, v) => cb.drawN(v.c), { exhaust: 1 });
KL('harvestGolem', 'lg_harvest', '豐收之鐮', 'atk', 'L', 1, 'w12_harvestScythe', 'enemy', { d: 10, x: 3 }, { d: 13, x: 4 }, v => '造成 ' + v.d + ' 傷害；這張卡打倒敵人時，最大 HP 永久 +' + v.x + '。消耗。', v => ['傷害 ' + v.d, '打倒 HP+' + v.x], (cb, core, tg, v) => { const t0 = tg[0], up0 = t0 && core.isUp(t0); kAtk(cb, core, tg, v.d); if (up0 && !core.isUp(t0)) cb.gainMaxHp(v.x); }, { exhaust: 1 });
KL('clockColossus', 'lg_clock', '時之齒輪', 'skl', 'L', 1, 'meditate', 'self', { e: 3, c: 2 }, { e: 3, c: 3 }, v => '能量 +' + v.e + '，抽 ' + v.c + ' 張。消耗。', v => ['能量 +' + v.e, '抽 ' + v.c], (cb, core, tg, v) => { cb.energy += v.e; cb.drawN(v.c); }, { exhaust: 1 });
KL('frostQueen', 'lg_frost', '霜后之吻', 'atk', 'L', 2, 'frostBloom', 'all', { d: 10 }, { d: 13 }, v => '對全體造成 ' + v.d + ' 水屬性傷害，全體這回合不能行動（頭目改成虛弱 3、易傷 3）。消耗。', v => ['全體 ' + v.d, '全體定身'], (cb, core, tg, v) => { kAll(cb, core, v.d); for (const t of kFoes(core)) kStop(cb, core, t); }, { el: '水', exhaust: 1 });
KL('lavaGiant', 'lg_lava', '熔岩之拳', 'atk', 'L', 2, 'o12_flameVortex', 'enemy', { d: 18, x: 5 }, { d: 24, x: 6 }, v => '造成 ' + v.d + ' 火屬性傷害，燃燒 ' + v.x + '。', v => ['傷害 ' + v.d, '燃燒 ' + v.x], (cb, core, tg, v) => { kAtk(cb, core, tg, v.d); for (const t of tg) KD.add(core, cb.Hu(), t, 'burn14', v.x); }, { el: '火' });
KL('victorDemon', 'lg_victor', '魔人契約', 'pow', 'L', 1, 'bloodRage', 'self', { h: 2 }, { h: 1 }, v => '能力：每回合開始失去 ' + v.h + ' HP，能量 +1。', v => ['HP -' + v.h, '能量 +1'], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwVictor14', v.h));
KL('shadowGeneral', 'lg_mold', '影將之刃', 'atk', 'L', 1, 'shadowDance', 'enemy', { d: 6 }, { d: 8 }, v => '造成 ' + v.d + ' 傷害 3 次。', v => [v.d + ' ×3'], (cb, core, tg, v) => kAtk(cb, core, tg, v.d, 3));
KL('starGuardian', 'lg_star', '星之守護', 'skl', 'L', 2, 'sanctuary', 'self', { b: 20 }, { b: 26 }, v => '獲得 ' + v.b + ' 格擋；下回合能量 +1。', v => ['格擋 ' + v.b, '下回合能量+1'], (cb, core, tg, v) => { kBlk(cb, core, v.b); cb.nextEn++; });
KL('siren13', 'lg_siren', '海妖之歌', 'skl', 'L', 1, 'sing', 'all', { x: 3 }, { x: 4 }, v => '全體虛弱 ' + v.x + '、易傷 ' + v.x + '。消耗。', v => ['全體虛弱' + v.x, '易傷 ' + v.x], (cb, core, tg, v) => { for (const t of kFoes(core)) { KD.add(core, cb.Hu(), t, 'weak15', v.x); KD.add(core, cb.Hu(), t, 'vuln15', v.x); } }, { exhaust: 1 });
KL('moonKing13', 'lg_moon', '月王冠', 'pow', 'L', 2, 'resonanceSong', 'self', {}, {}, v => '能力：每回合多抽 1 張。', v => ['每回合', '多抽 1'], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwMoon14', 1), { upCost: 1 });
KL('mirrorGolem13', 'lg_mirror', '鏡像', 'skl', 'L', 1, 'mirage', 'self', {}, {}, v => '複製手牌中費用最高的一張卡。', v => ['複製手牌'], (cb, core, tg, v) => cb.copyBest(), { upCost: 0 });
KL('otto14', 'lg_otto', '奧托的機關', 'pow', 'L', 2, 'turretSet', 'self', { x: 6 }, { x: 8 }, v => '能力：每回合結束時，對隨機敵人造成 ' + v.x + ' 傷害。', v => ['回合結束', '射擊 ' + v.x], (cb, core, tg, v) => KD.add(core, cb.Hu(), cb.Hu(), 'pwOtto14', v.x));
KL('riftLord13', 'lg_rift', '裂界之刃', 'atk', 'L', 3, 'riftBlade', 'enemy', { d: 40 }, { d: 55 }, v => '造成 ' + v.d + ' 傷害。', v => ['傷害 ' + v.d], (cb, core, tg, v) => kAtk(cb, core, tg, v.d));
/* ---------- card instances: { id, up } ---------- */
KD.val = c => (c.up ? KD.CARDS[c.id].u : KD.CARDS[c.id].b);
KD.cost = c => { const C = KD.CARDS[c.id]; return c.up && C.upCost != null ? C.upCost : C.cost; };
KD.name = c => KD.CARDS[c.id].n + (c.up ? '+' : '');
KD.desc = c => KD.CARDS[c.id].desc(KD.val(c));
KD.canUp = c => !c.up && KD.CARDS[c.id] && KD.CARDS[c.id].rar !== 'T';
// the cards a class can find (its own + 共通; 傳說 only from bosses)
KD.pool = (cls, rar) => Object.keys(KD.CARDS).filter(id => { const C = KD.CARDS[id]; return (C.cls === cls || C.cls === 'nt') && C.rar === rar && !C.hidden && !C.boss && !C.quest; });
/* ---------- one battle skill per card (the battle screen plays its effect; the core runs the card) ---------- */
for (const k of ['card14', 'card14end']) EFFECT_TYPES[k] = EFFECT_TYPES[k] || { exec() {} };
defPut('effects', 'k14_play', { type: 'card14' }); defPut('effects', 'k14_endfx', { type: 'card14end' });
KD.regCard = id => { const C = KD.CARDS[id], T = DEF.skills.t_sdBreak, cat = C.cat || (C.cls === 'mg' ? '特' : '物');
  defPut('skills', 'k14_' + id, { ...T, id: 'k14_' + id, name: C.n, desc: '', power: C.type === 'atk' ? 1 : 0, target: C.tg === 'enemy' ? 'enemy' : C.tg === 'self' ? 'self' : 'all_enemies', noHitRoll: true, costs: [], cooldown: 0, hits: null, charge: false, prio: 0,
    effects: ['k14_play'], after: [], mods: [], fx: C.fx, el: C.el || '一般', cat, tags: ['skill', C.type === 'atk' ? (cat === '特' ? 'magic' : 'phys') : 'support'], metadata: { card14: id }, override: true }); };
for (const id in KD.CARDS) KD.regCard(id);
defPut('skills', 'k14_end', { ...DEF.skills.t_sdBreak, id: 'k14_end', name: '結束回合', desc: '', power: 0, target: 'self', noHitRoll: true, costs: [], cooldown: 0, hits: null, charge: false, prio: 0, effects: ['k14_endfx'], after: [], mods: [], fx: null, tags: ['skill', 'support'], metadata: {}, override: true });
